### ISSUE TITLE
[known, sub]clusterblast results not shown if run locally

### ISSUE THREAD

**Issue by satriaphd** [antismash/antismash#102]
when ran locally, antiSMASH5 still retain the same bug as 4's clusterblast module: the SVGs will not be shown in the html output because it violates cross-origin resource sharing (CORS) policy.
given that we're now also store clusterblast result as an object, would it be a good idea to reimplement the html visualization e.g. by re-drawing the SVGs inline?

![image](https://user-images.githubusercontent.com/7368871/52282286-620b0780-2960-11e9-85f0-2a6c3229dd28.png)

**Comment by kblin** [comment]
This is your browser being too picky. Firefox will load these just fine. :)

**Comment by zachcp** [comment]
Alternatively

```
#  run a local webserver in the dir to view the file. 
python3 -m http.server
```

**Comment by kblin** [comment]
Closing, as there's nothing we can do about the browsers' decision to not allow CORS content from local disk.
