### ISSUE TITLE
i have some problems

### ISSUE THREAD

**Issue by byeollee** [antismash/antismash#138]
hello

when I downloaded antismash, problem coming out.
refer to this web site (https://docs.antismash.secondarymetabolites.org/install/)

my os is ubuntu 18.04

`antismash --check-prereqs`

when i insert the coding in terminal, this results coming out

ERROR   19/04 17:22:20   Failed to locate executable for 'long-orfs'
ERROR   19/04 17:22:20   Failed to locate executable for 'extract'
ERROR   19/04 17:22:20   Failed to locate executable for 'build-icm'
ERROR   19/04 17:22:20   Failed to locate executable for 'glimmer3'
ERROR   19/04 17:22:20   Failed to locate executable for 'glimmerhmm'
ERROR   19/04 17:22:20   Failed to locate executable for 'hmmpfam2'
ERROR   19/04 17:22:20   Failed to locate executable for 'hmmpfam2'
ERROR   19/04 17:22:20   Failed to locate executable for 'java'
ERROR   19/04 17:22:20   Failed to locate executable for 'hmmpfam2'
ERROR   19/04 17:22:20   Failed to locate executable for 'hmmpfam2'
ERROR   19/04 17:22:20   Not all prerequisites met

i download all they need follow the step but come out the error
help me...

thank you

**Comment by kblin** [comment]
Hi,
what version of antiSMASH is this you are trying to install here? The install instructions and this bug tracker are for antiSMASH 5, and that doesn't depend on the glimmer 3 binaries that you seem to be missing.

**Comment by kblin** [comment]
Hi,
what version of antiSMASH is this you are trying to install here? The install instructions and this bug tracker are for antiSMASH 5, and that doesn't depend on the glimmer 3 binaries that you seem to be missing.
