### ISSUE TITLE
CASSIS not working in default docker installation

### ISSUE THREAD

**Issue by max-biodatomics** [antismash/antismash#169]
**Describe the bug**

**Expected behavior**

**To Reproduce**
For analysis issues, provide an accession number or a record fragment that can reproduce the problem.

For interaction issues, also include steps to reproduce the behavior:

**Screenshots**

**System (please complete the following information):**
 - OS: [e.g. iOS, Ubuntu]
 - Browser [e.g. chrome, safari] (if relevant)

**Additional context**

**Comment by max-biodatomics** [comment]
I used the protocol for running from https://docs.antismash.secondarymetabolites.org/install/
I used Using Docker: antiSMASH standalone
running command: 
`run_antismash antismashIN/{}.fna $OUT/{} --cpus $CPU -v --taxon fungi --fullhmmer --cassis --cf-create-clusters --smcog-trees --cb-general --cb-subclusters --cb-knownclusters --asf --pfam2go --genefinding-gff3 antismashIN/{}.gff --logfile $OUTPUT/{}.log`

> INFO     05/06 05:15:07   java using executable: /usr/bin/java (1.8.0_212)
> INFO     05/06 05:15:07   hmmpress using executable: /usr/bin/hmmpress (3.1b2)
> INFO     05/06 05:15:07   fasttree using executable: /usr/bin/fasttree
> INFO     05/06 05:15:07   makeblastdb using executable: /usr/bin/makeblastdb (2.6.0+)
> INFO     05/06 05:15:07   prodigal using executable: /usr/bin/prodigal (V2.6.3)
> INFO     05/06 05:15:07   muscle using executable: /usr/bin/muscle (v3.8.31)
> INFO     05/06 05:15:07   glimmerhmm using executable: /usr/bin/glimmerhmm
> INFO     05/06 05:15:07   blastp using executable: /usr/bin/blastp (2.6.0+)
> INFO     05/06 05:15:07   hmmsearch using executable: /usr/bin/hmmsearch (3.1b2)
> INFO     05/06 05:15:07   hmmpfam2 using executable: /usr/bin/hmm2pfam (2.3.2)
> INFO     05/06 05:15:07   hmmscan using executable: /usr/bin/hmmscan (3.1b2)
> INFO     05/06 05:15:07   diamond using executable: /usr/bin/diamond-aligner (0.9.24)
> ERROR    05/06 05:15:07   antismash.detection.cassis: preqrequisite failure: Failed to locate executable for 'meme'
> ERROR    05/06 05:15:07   antismash.detection.cassis: preqrequisite failure: Failed to locate executable for 'fimo'
> Traceback (most recent call last):
>   File "/usr/local/bin/antismash", line 11, in <module>
>     sys.exit(entrypoint())
>   File "/usr/local/lib/python3.5/dist-packages/antismash/__main__.py", line 124, in entrypoint
>     sys.exit(main(sys.argv[1:]))
>   File "/usr/local/lib/python3.5/dist-packages/antismash/__main__.py", line 113, in main
>     antismash.run_antismash(sequence, options)
>   File "/usr/local/lib/python3.5/dist-packages/antismash/main.py", line 574, in run_antismash
>     result = _run_antismash(sequence_file, options)
>   File "/usr/local/lib/python3.5/dist-packages/antismash/main.py", line 603, in _run_antismash
>     check_prerequisites(options.all_enabled_modules, options)
>   File "/usr/local/lib/python3.5/dist-packages/antismash/main.py", line 511, in check_prerequisites
>     raise RuntimeError("Modules failing prerequisites")
> RuntimeError: Modules failing prerequisites

The docker installation doesn't have meme installed.

**Comment by kblin** [comment]
Ah, yes. You can't run `cassis` from the free software image the script is using, as the MEME package is not under a free software license.

If you have a MEME license, change the line in the `run_antismash` script that says
```
    antismash/standalone:5.0.0 \
```
to say 
```
    antismash/standalone-nonfree:5.0.0 \
```
instead and you'll have the missing executables available.
