### ISSUE TITLE
Bug in draw_tree (modules/smcog_trees/trees.py)

### ISSUE THREAD

**Issue by max-biodatomics** [antismash/antismash#170]
I used Manual installation from https://docs.antismash.secondarymetabolites.org/install/

execution command: 
```
ls $INPUT/*.fna | sed 's/.*\///'| sed 's/.fna//'| parallel -j $CPU "echo ============ processing {};
          time antismash --cpus $CPU -v --taxon fungi --fullhmmer --cassis --cf-create-clusters --smcog-trees --cb-general --cb-subclusters --cb-knownclusters --asf --pfam2go --output-dir $OUT/{} --genefinding-gff3 antismashIN/{}.gff --logfile $OUTPUT/{}.log  antismashIN/{}.fna"
```

I got an error message: 

> INFO     05/06 03:00:36   Analysing record: EU1_51
> INFO     05/06 03:00:36   Running antismash.detection.full_hmmer
> INFO     05/06 03:00:36   Running whole-genome PFAM search
> INFO     05/06 03:00:48   Detecting secondary metabolite clusters
> INFO     05/06 03:00:48   Running antismash.detection.hmm_detection
> INFO     05/06 03:00:49   Running antismash.detection.cassis
> INFO     05/06 03:00:49   Detecting gene cluster regions using CASSIS
> INFO     05/06 03:00:49   Running antismash.detection.clusterfinder_probabilistic
> INFO     05/06 03:00:49   Running ClusterFinder to detect probabilistic gene clusters
> INFO     05/06 03:00:49   No regions detected, skipping record
> INFO     05/06 03:00:49   Analysing record: EU1_52
> INFO     05/06 03:00:49   Running antismash.detection.full_hmmer
> INFO     05/06 03:00:49   Running whole-genome PFAM search
> INFO     05/06 03:01:03   Detecting secondary metabolite clusters
> INFO     05/06 03:01:03   Running antismash.detection.hmm_detection
> INFO     05/06 03:01:03   Running antismash.detection.cassis
> INFO     05/06 03:01:03   Detecting gene cluster regions using CASSIS
> INFO     05/06 03:01:03   Running antismash.detection.clusterfinder_probabilistic
> INFO     05/06 03:01:03   Running ClusterFinder to detect probabilistic gene clusters
> INFO     05/06 03:01:03   1 region(s) detected in record
> INFO     05/06 03:01:03   Running antismash.detection.nrps_pks_domains
> INFO     05/06 03:01:04   Running antismash.detection.genefunctions
> INFO     05/06 03:01:05   Running antismash.modules.smcog_trees
> INFO     05/06 03:01:05   Calculating and drawing phylogenetic trees of cluster genes with smCOG members
> multiprocessing.pool.RemoteTraceback:
> """
> Traceback (most recent call last):
>   File "/opt/anaconda/envs/antismash5/lib/python3.6/multiprocessing/pool.py", line 119, in worker
>     result = (True, func(*args, **kwds))
>   File "/opt/anaconda/envs/antismash5/lib/python3.6/multiprocessing/pool.py", line 47, in starmapstar
>     return list(itertools.starmap(args[0], args[1]))
>   File "/opt/anaconda/envs/antismash5/lib/python3.6/site-packages/antismash/modules/smcog_trees/trees.py", line 68, in smcog_tree_analysis
>     draw_tree(input_number, output_dir, gene_id)
>   File "/opt/anaconda/envs/antismash5/lib/python3.6/site-packages/antismash/modules/smcog_trees/trees.py", line 161, in draw_tree
>     label_func=lambda node: str(node).replace("|", " "))
>   File "/opt/anaconda/envs/antismash5/lib/python3.6/site-packages/Bio/Phylo/_utils.py", line 344, in draw
>     import matplotlib.pyplot as plt
>   File "/opt/anaconda/envs/antismash5/lib/python3.6/site-packages/matplotlib/pyplot.py", line 32, in <module>
>     import matplotlib.colorbar
>   File "/opt/anaconda/envs/antismash5/lib/python3.6/site-packages/matplotlib/colorbar.py", line 29, in <module>
>     import matplotlib.collections as collections
>   File "/opt/anaconda/envs/antismash5/lib/python3.6/site-packages/matplotlib/collections.py", line 2056, in <module>
>     docstring.interpd.update(LineCollection=artist.kwdoc(LineCollection))
>   File "/opt/anaconda/envs/antismash5/lib/python3.6/site-packages/matplotlib/artist.py", line 1583, in kwdoc
>     leadingspace=2))
>   File "/opt/anaconda/envs/antismash5/lib/python3.6/site-packages/matplotlib/artist.py", line 1354, in pprint_setters
>     accepts = self.get_valid_values(prop)
>   File "/opt/anaconda/envs/antismash5/lib/python3.6/site-packages/matplotlib/artist.py", line 1247, in get_valid_values
>     return re.sub("\n *", " ", match.group(1))
>   File "/opt/anaconda/envs/antismash5/lib/python3.6/re.py", line 191, in sub
>     return _compile(pattern, flags).sub(repl, string, count)
> TypeError: expected string or bytes-like object
> """
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/opt/anaconda/envs/antismash5/bin/antismash", line 10, in <module>
>     sys.exit(entrypoint())
>   File "/opt/anaconda/envs/antismash5/lib/python3.6/site-packages/antismash/__main__.py", line 124, in entrypoint
>     sys.exit(main(sys.argv[1:]))
>   File "/opt/anaconda/envs/antismash5/lib/python3.6/site-packages/antismash/__main__.py", line 113, in main
>     antismash.run_antismash(sequence, options)
>   File "/opt/anaconda/envs/antismash5/lib/python3.6/site-packages/antismash/main.py", line 574, in run_antismash
>     result = _run_antismash(sequence_file, options)
>   File "/opt/anaconda/envs/antismash5/lib/python3.6/site-packages/antismash/main.py", line 638, in _run_antismash
>     analysis_timings = analyse_record(record, options, analysis_modules, module_results)
>   File "/opt/anaconda/envs/antismash5/lib/python3.6/site-packages/antismash/main.py", line 264, in analyse_record
>     run_module(record, module, options, previous_result, timings)
>   File "/opt/anaconda/envs/antismash5/lib/python3.6/site-packages/antismash/main.py", line 236, in run_module
>     results = module.run_on_record(record, results, options)
>   File "/opt/anaconda/envs/antismash5/lib/python3.6/site-packages/antismash/modules/smcog_trees/__init__.py", line 128, in run_on_record
>     trees = generate_trees(smcogs_dir, record.get_cds_features_within_regions(), nrpspks_genes)
>   File "/opt/anaconda/envs/antismash5/lib/python3.6/site-packages/antismash/modules/smcog_trees/trees.py", line 48, in generate_trees
>     subprocessing.parallel_function(smcog_tree_analysis, args)
>   File "/opt/anaconda/envs/antismash5/lib/python3.6/site-packages/antismash/common/subprocessing/base.py", line 132, in parallel_function
>     results = jobs.get(timeout=timeout)
>   File "/opt/anaconda/envs/antismash5/lib/python3.6/multiprocessing/pool.py", line 670, in get
>     raise self._value
> TypeError: expected string or bytes-like object
> 
> real    60m17.158s
> user    144m35.199s
> sys     15m16.297s

The error happens not immideately. some trees were created. 

Ubuntu18.04

**Comment by SJShaw** [comment]
```
File "/opt/anaconda/envs/antismash5/lib/python3.6/site-packages/Bio/Phylo/_utils.py", line 344, in draw
import matplotlib.pyplot as plt
```
This line causing an exception indicates that it's somewhere within `matplotlib`, and that is very strange if it is called multiple times with previous successes.

What are your `matplotlib` and `biopython` versions?
