### ISSUE TITLE
Hmmscan typo when matching pfam hits with their source protein

### ISSUE THREAD

**Issue by prihoda** [antismash/antismash#172]
Hi,

I noticed this check inside the `hmmer` module:

https://github.com/antismash/antismash/blob/e6f66203fd7d0ac4f5868f7d192ae2938d4ea6e2/antismash/common/hmmer.py#L115-L118

This is always true. It should have probably said:
```python
 if hsp.query_id not in feature_by_id: 
     continue 
  
 feature = feature_by_id[hsp.query_id] 
```

Or even throw an exception since there would be something fishy going on :)

**Comment by SJShaw** [comment]
Good catch. It was probably intended to be `in feature_by_id`, but since we've been running through this for a year or more without a `KeyError` coming from the next line, I think we're safe in removing it.
