### ISSUE TITLE
Bug in GeneFunctionAnnotations assignment

### ISSUE THREAD

**Issue by zdk123** [antismash/antismash#186]
**Describe the bug**
I added a custom Resfam pHMM model that overlaps semantically with an existing smCOG annotation. I see the smCOG annotation (_other_) in the html output, (gene color is gray).

**Expected behavior**
I expect the resistance annotation to take priority (e.g. pink gene in the html output). I can see both the smCOG and resist annotations in the side panel, and the resist annotation has the higher bitscore.

According to the comments in the GeneFunctionsAnnotations class, I would expect the resfams to take priority:
https://github.com/antismash/antismash/blob/c72e99fddbc43944e54e68b3fc93bc78a29e44c4/antismash/common/secmet/qualifiers/gene_functions.py#L181-L183

However, I believe the name of tool is misspecified in line 182:
```diff
        # then priority for resfam, then smcogs
-        annotations = self._by_tool.get("resfam", self._by_tool.get("smcogs"))
+        annotations = self._by_tool.get("resist", self._by_tool.get("smcogs"))
        if annotations:
            return annotations[0].function
```
If both smcogs and resist is present, the annotation defaults to smcog.

**To Reproduce**
I can create a reproducible example if you disagree that the line above is a straight-forward bug.

**System (please complete the following information):**
- standalone docker

**Comment by kblin** [comment]
Hi there,
thanks for the analysis. The `resfam` vs. `resist` indeed looks like a simple bug.

**Comment by SJShaw** [comment]
@zdk123 , in fixing this we realised that it was a little more complicated on the visualisation side of things. Would the solution in the pull request linked above be satisfactory for you?

**Comment by zdk123** [comment]
Looks good to me and would suit our purposes well. Thanks!

**Comment by SJShaw** [comment]
The fix is now merged.

Thanks for finding this and letting us know.
