### ISSUE TITLE
Error during check_prerequisites, because antiSMASH installation directory is not writable

### ISSUE THREAD

**Issue by fbartusch** [antismash/antismash#187]
**Describe the bug**
antiSMASH throws error during check_prerequisites. It tries to update `/usr/local/lib/python3.5/dist-packages/antismash/detection/hmm_detection/data/bgc_seeds.hmm`, but this file is not writable for the user (belongs to root).

**Expected behavior**
From my point of view antiSMASH should not update any file systems file, when a user runs the tool. Is there an option for placing these prerequisities somewhere, where the user can write? Or can I disable the check_prerequisities step?

**To Reproduce**

I try to install antiSMASH on our HPC cluster. Because antiSMASH has many dependencies, I wanted to use a Singularity container. Therefore I pulled your docker container with Singularity 3.2.1:

```
singularity pull docker://antismash/standalone:5.0.0
```

In order to user the Singularity container, I changed the container executation in your wrapper script to:

```
singularity --debug run --writable-tmpfs \
    --bind ${INPUT_DIR}:${CONTAINER_SRC_DIR} \
    --bind ${OUTPUT_DIR}:${CONTAINER_DST_DIR} \
    standalone_5.0.0.sif \
    ${INPUT_FILE} \
    $@
```

Then I execute the wrapper script with a small test data set, provided by the user:

```
./run_antismash ./example_input/CP026121sequence.fasta \
    /example_output/ \
    -c 1 -v -d \
    --genefinding-tool prodigal \
    --logfile test.log
```
The error message I get is:

```
ERROR    19/07 11:05:51   antismash.detection.hmm_detection: preqrequisite failure: Failed to generate file '/usr/local/lib/python3.5/dist-packages/antismash/detection/hmm_detection/data/bgc_seeds.hmm'
Traceback (most recent call last):
  File "/usr/local/bin/antismash", line 11, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.5/dist-packages/antismash/__main__.py", line 124, in entrypoint
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/lib/python3.5/dist-packages/antismash/__main__.py", line 113, in main
    antismash.run_antismash(sequence, options)
  File "/usr/local/lib/python3.5/dist-packages/antismash/main.py", line 574, in run_antismash
    result = _run_antismash(sequence_file, options)
  File "/usr/local/lib/python3.5/dist-packages/antismash/main.py", line 603, in _run_antismash
    check_prerequisites(options.all_enabled_modules, options)
  File "/usr/local/lib/python3.5/dist-packages/antismash/main.py", line 511, in check_prerequisites
    raise RuntimeError("Modules failing prerequisites")
RuntimeError: Modules failing prerequisites
Running antiSMASH FAILED
```

**System (please complete the following information):**
 - OS: Red Hat Enterprise Linux Server release 7.5 (Maipo)
 - Singularity 3.2.1

**Additional context**
I think I would have the same problem if I install an environment module, because the installation directory also not writable for a user of our HPC cluster.

**Comment by kblin** [comment]
Hi there,

I think this is an issue in your install logic during building the container. At some point in the install process, antiSMASH needs to prepare all the databases, and we can't trigger that off setup.py installs because that is a super limited environment. The solution to this for Singularity should be pretty similar to how we do this for the Docker containers, where we do the same thing.

See https://github.com/antismash/antismash/blob/master/Dockerfile#L17 where we run the pip install and then run another small Python script to call `prepare_module_data()`.

Alternatively, running `download-antismash-databases` like specified in the install documentation would have called that function (and thus prepared the databases as well). We do that for our shared machines where we run antiSMASH from environment modules.

Disabling the prerequisite check is not the solution, because trying to run hmmscan on a non-pressed database would just fail at run time.

**Comment by fbartusch** [comment]
Hi kblin,

thanks for the fast reply. I'm not really convinced that the problem is really my install logic, as `singularity pull` pulls the Docker container from DockerHub as it is, hence also the result of `prepare_module_data()` should already be present in my container. But I'll check if you're suggestions can help me to solve this problem.

**Comment by kblin** [comment]
Good point, I missed that, I assumed you built an image from scratch, sorry.

I have to admit that I really don't know my way around Singularity well enough. But antiSMASH will only try to generate that hmm file if it can't find them, that I know for sure. So the next step would be to find out what's going on with that container. I'm absolutely sure the docker image has that file. 
```
DEBUG    25/05 06:18:45   Found file '/usr/local/lib/python3.5/dist-packages/antismash/detection/hmm_detection/data/bgc_seeds.hmm'
```
is the line from the example output we have on the website, where we use the `standalone-lite` container that the `standalone` container is based on.

**Comment by fbartusch** [comment]
I ran the same example with the original Docker container in a VM and the problem does not occur there. Now I suspect, that it's not really an antiSMASH issue, but rather an Docker to Singularity conversion issue.

The difference in behaviour is, that the Docker container finds the file and just does nothing. The Singularity container finds the file, says it is outdated and tries to regenerate it:

```
DEBUG    24/07 15:08:43   Found file '/usr/local/lib/python3.5/dist-packages/antismash/detection/hmm_detection/data/bgc_seeds.hmm'
DEBUG    24/07 15:08:43   /usr/local/lib/python3.5/dist-packages/antismash/detection/hmm_detection/data/bgc_seeds.hmm out of date, regenerating
[...]
DEBUG    24/07 15:08:43   Found file '/usr/local/lib/python3.5/dist-packages/antismash/outputs/html/css/plants.css'
ERROR    24/07 15:08:43   antismash.detection.hmm_detection: preqrequisite failure: Failed to generate file '/usr/local/lib/python3.5/dist-packages/antismash/detection/hmm_detection/data/bgc_seeds.hmm'
Traceback (most recent call last):
  File "/usr/local/bin/antismash", line 11, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.5/dist-packages/antismash/__main__.py", line 124, in entrypoint
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/lib/python3.5/dist-packages/antismash/__main__.py", line 113, in main
    antismash.run_antismash(sequence, options)
  File "/usr/local/lib/python3.5/dist-packages/antismash/main.py", line 574, in run_antismash
    result = _run_antismash(sequence_file, options)
  File "/usr/local/lib/python3.5/dist-packages/antismash/main.py", line 603, in _run_antismash
    check_prerequisites(options.all_enabled_modules, options)
  File "/usr/local/lib/python3.5/dist-packages/antismash/main.py", line 511, in check_prerequisites
    raise RuntimeError("Modules failing prerequisites")
RuntimeError: Modules failing prerequisites
```

I opened a shell in this container to check if the file is there:

```
/beegfs/work/iioba01/antiSMASH> ls -l /usr/local/lib/python3.5/dist-packages/antismash/detection/hmm_detection/data/bgc_seeds.hmm
-rw-r--r-- 1 root root 30850632 Jul 17 15:44 /usr/local/lib/python3.5/dist-packages/antismash/detection/hmm_detection/data/bgc_seeds.hmm
```

**Comment by kblin** [comment]
Now we're getting somewhere. Can you compare the timestamp on the bgc_seeds.hmm file to the timestamps on the other .hmms in that folder? We have a timestamp check at https://github.com/antismash/antismash/blob/master/antismash/detection/hmm_detection/__init__.py#L179 that obviously is triggering for some reason

**Comment by fbartusch** [comment]
Ok, you found the error. The singularity pull seems to reset the mtime of the files. I ran the python code you linked and the `bgc_seeds.hmm` is 1ms younger than the other files, hence this triggers the regeneration.

I will now ask the Singularity people how to handle this. Thank you very much!

**Comment by spock** [comment]
@fbartusch , were you able to find a good solution back in 2019? 🙂

**Comment by fbartusch** [comment]
@spock , yes, I found a solution. When Singularity converts the Docker image, the timestamps get messed up. When antismash runs, it checks if certain files are older/newer than other files. So I wrote my own Singularity recipe that touched the files in a certain order to ensure that this is met. Here is the recipe I used:

```
Bootstrap: docker
From: antismash/standalone:5.1.0

%post
    # Fix mtimes of these files, otherwise the container may not work
    # See: https://github.com/antismash/antismash/issues/187

    touch /usr/local/lib/python3.5/dist-packages/antismash/detection/hmm_detection/data/*

    # bgc_seeds.hmm has to be older than the other files
    sleep 5
    touch /usr/local/lib/python3.5/dist-packages/antismash/detection/hmm_detection/data/bgc_seeds.hmm

    # These files have to be older than bgc_seeds.hmm
    sleep 5
    touch /usr/local/lib/python3.5/dist-packages/antismash/detection/hmm_detection/data/bgc_seeds.hmm.h3f
    touch /usr/local/lib/python3.5/dist-packages/antismash/detection/hmm_detection/data/bgc_seeds.hmm.h3i
    touch /usr/local/lib/python3.5/dist-packages/antismash/detection/hmm_detection/data/bgc_seeds.hmm.h3m
    touch /usr/local/lib/python3.5/dist-packages/antismash/detection/hmm_detection/data/bgc_seeds.hmm.h3p

%environment
    LANG=C.UTF-8
```
