### ISSUE TITLE
Question: antismash summary of many genomes

### ISSUE THREAD

**Issue by alienzj** [antismash/antismash#206]
Hello, antismash development team, 
how to do large-scale analysis of antismash results of many genomes in a programmatic manner? parse *.gbk or parse *.json or parse regions.js?

**Comment by franciscozorrilla** [comment]
Hi @alienzj, 

I am wondering how you dealt with this question?
My solution so far has been to parse the main gbk file, e.g.
```
$ less ERR260137_bin.12.p.gbk|grep -A 10 'region '|grep '/product'|sed 's/^.*="//g'|sed 's/"//g'
cyclic-lactone-autoinducer
cyclic-lactone-autoinducer
RRE-containing
```
This extracts the main result types as shown by the different regions of the [index.html](https://github.com/antismash/antismash/files/7670995/index.txt) output file. 
I then repeat this for all my samples and create a presence/absence matrix to compare multiple genomes.

On a separate note, I am also wondering what parameters you have used for processing a large number of genomes in parallel on the cluster? My jobs are currently running in series on a single node using 76 cores and the following parameters:
```
antismash -v --asf --pfam2go --smcog-trees --tigrfam --rre --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --enable-genefunctions --genefinding-tool prodigal -c 76
```
However, I suspect that for analyzing on the order of thousands of genomes it will be necessary to submit a job for each genome in parallel and reduce the number of cores (~4 cores/job?).

Please let me know if you can advise me based on your experience with `antismash`.

Best wishes,
Francisco

**Comment by alienzj** [comment]
@franciscozorrilla
You can refer to https://github.com/ohmeta/oral-assembly/blob/master/notebook/antismash.ipynb for processing antismash''s output, but I am not sure what I did is right.

Based on my experience, if you need to process a large number of genomes, it is recommended to deliver tasks to the cluster to run, like `SGE` or `SLURM`.
