### ISSUE TITLE
Tab-delimited output?

### ISSUE THREAD

**Issue by adityabandla** [antismash/antismash#216]
Apologies if my request is misplaced here. I see the TSV outputs were available in v3, with JSON being the preferred output format for v5

I am looking for a simple script which can parse the antiSMASH output and return a frequency table of the detected BGC's along with feature data such as the predicted product. I am working a bunch of metagenome assembled genomes and therefore trying to aggregate results in a meaningful way.

**Comment by SJShaw** [comment]
The script you'll need will depend on exactly what you're running over and what you want in the final output. Here is a simple example of using antiSMASH to pull details from the genbank output to get you started:
```
from antismash.common.secmet import Record

for record in Record.from_genbank(filename, taxon="bacteria"):  # or fungi, if relevant
  for region in record.get_regions():
    print("\t".join[record.id, region.get_region_number(), region.get_product_string()])
```

**Comment by adityabandla** [comment]
Thanks, I was finally able to figure this out
