### ISSUE TITLE
geneclusters.txt showing no "Compound with gene cluster of highest homology"

### ISSUE THREAD

**Issue by Lamm-a** [antismash/antismash#220]
The `geneclusters.txt` outout of antismash is showing no "Compound with gene cluster of highest homology" despite the hmtl output showing most similar know clusters with a % matching. Is there a reason for this or are they two different things?

**Comment by SJShaw** [comment]
`geneclusters.txt` output files haven't been created since antiSMASH 4. The reasons for removal and adjustment are covered in #128.

**Comment by Lamm-a** [comment]
I am running in AntiSMASH v4.2 due to v5 not being avaliable on conda

**Comment by Lamm-a** [comment]
@SJShaw I have created a python script to take the html output files and generate a csv with this information in it. Pretty much just a copy of what I imagine the old geneclusters.txt would hav elooked like. Would you like me to share it so you can give to others who come lookign for this?

**Comment by tamuanand** [comment]
Hi @Lamm-a 

I have been following this thread and I think your script would definitely benefit a lot of people. 

Probably, you could put a link to your github repo that has the script?

Thanks

**Comment by tamuanand** [comment]
> I am running in AntiSMASH v4.2 due to v5 not being avaliable on conda

Antismash is available in bioconda - https://bioconda.github.io/recipes/antismash/README.html

I suggest that you should move from antismash 4 to antismash 5

**Comment by Lamm-a** [comment]
I moved to 5 after the push to get it avaliable in #222 :) I will get my script shared!
