### ISSUE TITLE
Any plans to make AntiSMASH v5 avaliable through conda?

### ISSUE THREAD

**Issue by Lamm-a** [antismash/antismash#222]
I would be very useful is those of us on clusters using conda could run the most current version of antismash, so are there any plans to update the version avaliable via conda?

**Comment by kblin** [comment]
Due to some packaging constraints on the Conda side of things, we currently don't have conda packages available. See https://github.com/bioconda/bioconda-recipes/pull/17382 for a discussion.

**Comment by Lamm-a** [comment]
Ah thank you! I assume conda have no plans to fix this?

**Comment by kblin** [comment]
Considering that their response was "we'll close this, feel free to open a new PR once you've fixed it", I guess that's a no.

That said, I think you can still use conda to install most dependencies apart from the MEME suite. We're looking into testing our install instructions for that scenario, but it might take a bit.

**Comment by Lamm-a** [comment]
Kind of ridiculous that would be their attitude seeing as that is the whole damn function of conda! and even more so as it appears to be dying out in favour of docker! Thanks for trying stleast :) I lookforward to some hopefully positive results!

**Comment by kblin** [comment]
Packaging is hard. I can see how from a packager's perspective everybody should just be using the latest version of every dependency they have. Unfortunately, in the case of MEME the output format changes, and it's not a trivial drop-in replacement.

**Comment by Lamm-a** [comment]
So when running with antismash v4 should we be getting the old geneclusters.txt output that shows Compound with gene cluster of highest homology. As if this is the case I am not getting this.

**Comment by kblin** [comment]
antiSMASH 4 really has reached its end of life, we don't really have the capacity to support it. See #128 for a suggestion on creating a similar file for antiSMASH 5.

**Comment by apcamargo** [comment]
I just started a new discussion about this: https://github.com/bioconda/bioconda-recipes/pull/20077

**Comment by kblin** [comment]
Thanks for your work @apcamargo, it looks like 5.1.1 will be available via bioconda soon.

**Comment by Lamm-a** [comment]
Just chead the bioconda thread. This is exciting :D Any idea on an ETA?

**Comment by apcamargo** [comment]
It's already available, @Lamm-a. I haven't tested it with my datasets though.

If you have any problems with it, you should create an issue in the Bioconda repository.

**Comment by kblin** [comment]
Closing this now that a bioconda package of 5.1.1 is out. We'll update our install instructions soon.
Thanks again, @apcamargo !
