### ISSUE TITLE
updatable pfam2go database

### ISSUE THREAD

**Issue by aozalevsky** [antismash/antismash#228]
The current antismash release (5.1.1) comes with an outdated version of the pfam2go database. The one which is distributed with the tarball is dated to `!version date: 2018/02/24 12:32:44` while the current one (http://current.geneontology.org/ontology/external2go/pfam2go) is dated to` !version date: 2019/12/14 15:47:44`. A lot has changed - versions differ not only in the number of lines (10570 vs. 10332 in the latter) but also in the naming of some pathways, e.g. (note the hyphen in the G-protein)
```

< Pfam:PF00001 7tm_1 > GO:G-protein coupled receptor activity ; GO:0004930
< Pfam:PF00001 7tm_1 > GO:G-protein coupled receptor signaling pathway ; GO:0007186
---
> Pfam:PF00001 7tm_1 > GO:G protein-coupled receptor activity ; GO:0004930
> Pfam:PF00001 7tm_1 > GO:G protein-coupled receptor signaling pathway ; GO:0007186

```
see the attached diff (https://pastebin.com/4pKmuzmt) for a more detailed view.

Thus it would be very convenient to have an opportunity to change the version or, at least, use the most recent one in the corresponding dir. At the moment the name of the database is hardcoded in several places:

```
modules/pfam2go/__init__.py:38:        pfam2go-march-2018.txt: mapping file for Pfam to Gene Ontology mapping
modules/pfam2go/__init__.py:41:    if path.locate_file(path.get_full_path(__file__, 'data', 'pfam2go-march-2018.txt')) is None:
modules/pfam2go/pfam2go.py:159:    full_gomap_as_ontologies = construct_mapping(path.get_full_path(__file__, 'data', 'pfam2go-march-2018.txt'))
modules/pfam2go/test/test_pfam2go.py:84:        data = path.get_full_path(os.path.dirname(__file__), 'data', 'pfam2go-march-2018.txt')
```

**Comment by kblin** [comment]
Happy to look into that for the 5.2 release, I don't want to touch this for the 5.1.x series.
