### ISSUE TITLE
Are antismash txt results 0-indexed or 1-indexed? right open or closed intervals?

### ISSUE THREAD

**Issue by surh** [antismash/antismash#230]
I am running antiSMASH 4.2 installed through conda and saving only the txt output.

I cannot find explicit documentation indicating what the values in the "BGC_range" column in the <record>_BGC.txt files means.

For example if I had `1:2` in the range, and the sequence `ACT`, which bases are included in the feature?
1. The first and second base of the sequence: `AC`.
2. The first base of the sequence: `A`.
3. The second base of the sequence: `C`.
4. The second and third base of the sequence: `CT`.
??

Thanks

**Comment by kblin** [comment]
Hi there.

Unfortunately, we don't have the resources to support antiSMASH 4 at this point.
That said, from a quick look at the old code, we're just using the start/end locations from Biopython, which are like Python array indices, so they are 0-indexed and end-exclusive. So the `1:2` range on `ACT` should be `C`.
