### ISSUE TITLE
Keep accession version information

### ISSUE THREAD

**Issue by surh** [antismash/antismash#231]
**Is your feature request related to a problem? Please describe.**
Yes, basically I run antiSMASH on some RefSeq bacterial assemblies in fasta format. Some of those have multiple fasta records within a single assembly, and each fasta record has an ID of the form ` XXXXXXXX.#`. My issue is that antiSMASH removes the last part of the accession ID (the `.#`) so that output files get names like `XXXXXXXX_BGC.txt`, and BGCs get names like `XXXXXXXX_c1`. Hence I have no direct way of matching my original fasta record IDs to the filenames. I have resorted to changing the IDs in my original input files to some custom unique values and keeping a separate table that matches my unique accessions to the original ones. Obviously this is cumbersome and far from optimal since I duplicate data and add extra steps whenever I want to match the antiSMASH results with other data.

**Describe the solution you'd like**
Simply keeping the original IDs of the input fasta records would be the ideal. This would be the best practice since software shouldn't modify the IDs of the input sequences, and the predictions technically correspond not only to an accession, but to a specific version as well.

**Describe alternatives you've considered**
I imagine there could be reasons why having a dot in the BGC_ID could cause some incompatibilities in the pipeline. An alternative would be to add a column to the output files that have the original unmodified ID of the input fasta record where a BGC is found.

Great software
Sur

**Comment by kblin** [comment]
We'll no longer be changing antiSMASH 4, please consider using antiSMASH 5 instead.
