### ISSUE TITLE
Extract module co-ordinates from antismash output.

### ISSUE THREAD

**Issue by somakchowdhury** [antismash/antismash#236]
**Is your feature request related to a problem? Please describe.**
Extract module nucleotide co-ordinates for NRPS coding ORFs. Since v5 module co-ordinate inference has become difficult due to lack of the txt folder from v4.1.2

**Describe the solution you'd like**
Ideally, get a text file with tab separated output stating ORF-ID, Module-number, module.start, module.end  

**Describe alternatives you've considered**
1. An alternative would be to run antismash v4.1.2 and use the text files where the information exists and create a table using the CAT domain co-ordinates. (Highly mistake prone)
2. Since I am a complete programming newbie, parsing the json file is difficult, though I guess the information is located in it from the web output. 
3. Partial solve but low throughput: using a json editor for mac like : `Smart JSON Editor` `http://www.smartjsoneditor.com/` and extracting per ORF the co-ordinates from the modules section of the `json tree` (Note: This gives only amino acid positions and not nucleic acid)

**Additional context**
I need to apply the alternative to a large number of geneclusters with long NRPSs which makes manual co-ordinate extraction tedious and mistake prone. This need not be a standard output but if there is a flag in the antismash offline run to output this info it would be great.

**Advantages**
This will enable meta-analysis on evolution of modules and help understand diversification mechanisms in NRPS.

**Comment by SJShaw** [comment]
We deliberately removed this sort of text output file from antiSMASH 5, as everyone has different needs and we can't satisfy everyone with just one file and maintaining many extra files will inevitably go wrong.

The JSON has the core data from which the locations can be derived, but for your case, you may want to use the annotations from the genbank file instead, as the details you need are reasonably simple.

Here's a python snippet that will print out the equivalent of the table you'd like (you'll want to install biopython with `pip install biopython`, if not already installed). You can use it as a starting point.
```from collections import defaultdict
import json

from Bio import SeqIO

module_counts = defaultdict(int)

for record in SeqIO.parse("your_genbank_file.gbk", "genbank"):
    for feature in record.features:
        if feature.type != "aSModule":
            continue
        locus = feature.qualifiers["locus_tags"][0]
        module_counts[locus] += 1
        columns = [locus, module_counts[locus], feature.location.start, feature.location.end]
        print("\t".join(map(str, columns)))```

**Comment by somakchowdhury** [comment]
Thank you for taking the time to sort this out. Indeed many ancillary result files is a recipe for disaster. 
I shall implement your suggestion. Closing the issue.

**Comment by TaehyungKwon** [comment]
@SJShaw Hi, I'm trying to investigate sequential order of biosynthetic domains from the GBK output from antismash 5.1.2. 
Using SeqIO, I extracted domains annotated by "/NRPS_PKS=" features, whereas I failed to resolve how to deal with "/gene_functions="biosynthetic (rule-based-clusters)"". The latter annotations do not include coordinates, and I could not align them with /NRPS_PKS domain information.
Is there any workaround to figure out all annotated domains and their order in each CDS using all "NRPS_PKS", "gene_functions="biosynthetic (rule-based-clusters)"", and "sec_met_domain"?

Thanks,
Taehyung

**Comment by SJShaw** [comment]
The NRPS/PKS domains are annotated as `aSDomain` features in the genbank outputs, so you can find the `aSDomain` feature with the matching `domain_id` from the CDS anntoations and use the protein locations annotated there.

The `sec_met_domain` annotations aren't handled in the same way, as they only really indicate the presence of at least one domain of that type (e.g. antiSMASH doesn't annotate each individual condensations domain as a unique `sec_met_domain` in the CDS feature annotations).
