### ISSUE TITLE
error in download-antismash-databases step

### ISSUE THREAD

**Issue by qinglong89** [antismash/antismash#243]
Hi,

Got an error during database building:

(antismash) qinglong@tcmc-dataana-02:~$ download-antismash-databases

/home/DataAnalysis/miniconda2/envs/antismash/lib/python3.7/site-packages/sklearn/externals/joblib/__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)
/home/DataAnalysis/miniconda2/envs/antismash/lib/python3.7/site-packages/scss/selector.py:54: FutureWarning: Possible nested set at position 329
  ''', re.VERBOSE | re.MULTILINE)
Creating checksum of Pfam-A.hmm
PFAM file present and ok for version 27.0
Creating checksum of Pfam-A.hmm
PFAM file present and ok for version 31.0
Resfams database present and checked
Creating checksum of proteins.fasta
ClusterBlast fasta file present and checked
Pre-building all databases...
Error encountered while preparing module data: [Errno 13] Permission denied: '/home/DataAnalysis/miniconda2/envs/antismash/lib/python3.7/site-packages/antismash/modules/lanthipeptides/data/lanthipeptide.scaler.pkl'

**Comment by SJShaw** [comment]
`Permission denied` indicates that you don't have write access to the directory in question. If you fix that, you shouldn't have any further issues.

**Comment by qinglong89** [comment]
> `Permission denied` indicates that you don't have write access to the directory in question. If you fix that, you shouldn't have any further issues.

Solved after recursively changing the conda antismash env permission.
Thanks.
