### ISSUE TITLE
How to interprate when type has more that one result?

### ISSUE THREAD

**Issue by Lamm-a** [antismash/antismash#244]
For example I have `NRPS and ladderane` with the most known cluster being `CDA1b / CDA2a / CDA2b / CDA3a / CDA3b / CDA4a / CDA4b | NRP:Ca+-dependent lipopeptide`. Is this becuase the cluster has multiple secondary metabolites produced in it?

**Comment by SJShaw** [comment]
antiSMASH can't differentiate between true hybrids and distinct but interleaved/neighbouring clusters. This is something you need to use either physical experimentation or familiarity with the genome in question to work out.

There's quite a bit of documentation available when you click the `Help` link in the top bar of your antiSMASH results, for example: https://docs.antismash.secondarymetabolites.org/understanding_output/

Github issues should really be used for bug reports or feature enhancements regarding the analyses and outputs regarding the code contained in the repository. For general inquiries, the contact page on the website would be better.
