### ISSUE TITLE
Unable to install AntiSMASH via BioConda when FTP access blocked

### ISSUE THREAD

**Issue by tamuanand** [antismash/antismash#245]
**Describe the bug**
I get an error when trying to install antiSMASH 5.1.1 via bioconda

**Expected behavior**
A clean install during an interactive session on the command line

**To Reproduce**
Set up channels as mentioned in https://bioconda.github.io/recipes/antismash/README.html
```
conda create -n antismash
conda activate antismash
conda install antismash
```

**Error on command line**
```
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
ERROR conda.core.link:_execute(700): An error occurred while installing package 'bioconda::antismash-5.1.1-py_0'.
Rolling back transaction: done

LinkError: post-link script failed for package bioconda::antismash-5.1.1-py_0
location of failed script: <path_to>/envs/antismash/bin/.antismash-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout: Downloading PFAM version 27.0

stderr: <path_to>/envs/antismash/lib/python3.7/site-packages/sklearn/externals/joblib/__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)
<path_to>/envs/antismash/lib/python3.7/site-packages/scss/selector.py:54: FutureWarning: Possible nested set at position 329
  ''', re.VERBOSE | re.MULTILINE)
Traceback (most recent call last):
  File "<path_to>/envs/antismash/lib/python3.7/urllib/request.py", line 1535, in ftp_open
    fw = self.connect_ftp(user, passwd, host, port, dirs, req.timeout)
  File "<path_to>/envs/antismash/lib/python3.7/urllib/request.py", line 1557, in connect_ftp
    persistent=False)
  File "<path_to>/envs/antismash/lib/python3.7/urllib/request.py", line 2377, in __init__
    self.init()
  File "<path_to>/envs/antismash/lib/python3.7/urllib/request.py", line 2389, in init
    self.ftp.cwd(_target)
  File "<path_to>/envs/antismash/lib/python3.7/ftplib.py", line 631, in cwd
    return self.voidcmd(cmd)
  File "<path_to>/envs/antismash/lib/python3.7/ftplib.py", line 278, in voidcmd
    return self.voidresp()
  File "<path_to>/envs/antismash/lib/python3.7/ftplib.py", line 251, in voidresp
    resp = self.getresp()
  File "<path_to>/envs/antismash/lib/python3.7/ftplib.py", line 246, in getresp
    raise error_perm(resp)
ftplib.error_perm: 530 User access denied.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<path_to>/envs/antismash/lib/python3.7/site-packages/antismash/download_databases.py", line 82, in download_file
    req = request.urlopen(url)
  File "<path_to>/envs/antismash/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "<path_to>/envs/antismash/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "<path_to>/envs/antismash/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "<path_to>/envs/antismash/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "<path_to>/envs/antismash/lib/python3.7/urllib/request.py", line 1553, in ftp_open
    raise exc.with_traceback(sys.exc_info()[2])
  File "<path_to>/envs/antismash/lib/python3.7/urllib/request.py", line 1535, in ftp_open
    fw = self.connect_ftp(user, passwd, host, port, dirs, req.timeout)
  File "<path_to>/envs/antismash/lib/python3.7/urllib/request.py", line 1557, in connect_ftp
    persistent=False)
  File "<path_to>/envs/antismash/lib/python3.7/urllib/request.py", line 2377, in __init__
    self.init()
  File "<path_to>/envs/antismash/lib/python3.7/urllib/request.py", line 2389, in init
    self.ftp.cwd(_target)
  File "<path_to>/envs/antismash/lib/python3.7/ftplib.py", line 631, in cwd
    return self.voidcmd(cmd)
  File "<path_to>/envs/antismash/lib/python3.7/ftplib.py", line 278, in voidcmd
    return self.voidresp()
  File "<path_to>/envs/antismash/lib/python3.7/ftplib.py", line 251, in voidresp
    resp = self.getresp()
  File "<path_to>/envs/antismash/lib/python3.7/ftplib.py", line 246, in getresp
    raise error_perm(resp)
urllib.error.URLError: <urlopen error ftp error: error_perm('530 User access denied.')>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<path_to>/envs/antismash/bin/download-antismash-databases", line 10, in <module>
    sys.exit(_main())
  File "<path_to>/envs/antismash/lib/python3.7/site-packages/antismash/download_databases.py", line 352, in _main
    download(args)
  File "<path_to>/envs/antismash/lib/python3.7/site-packages/antismash/download_databases.py", line 317, in download
    download_pfam(args.database_dir, PFAM27_URL, "27.0", PFAM27_ARCHIVE_CHECKSUM, PFAM27_CHECKSUM)
  File "<path_to>/envs/antismash/lib/python3.7/site-packages/antismash/download_databases.py", line 228, in download_pfam
    download_if_not_present(url, archive_filename, archive_checksum)
  File "<path_to>/envs/antismash/lib/python3.7/site-packages/antismash/download_databases.py", line 207, in download_if_not_present
    download_file(url, filename)
  File "<path_to>/envs/antismash/lib/python3.7/site-packages/antismash/download_databases.py", line 84, in download_file
    raise DownloadError("ERROR: File not found on server.\nPlease check your internet connection.")
antismash.download_databases.DownloadError: ERROR: File not found on server.
Please check your internet connection.

return code: 1

()

```

**System (please complete the following information):**
 - OS: CentOS 7

**Comment by SJShaw** [comment]
The URL that you're getting that access denied error from is ftp://ftp.ebi.ac.uk/pub/databases/Pfam/releases/Pfam27.0/Pfam-A.hmm.gz

I can access it without issue both with the script and directly. If you are consistently getting that error, can you check that you can access that file via browser or some other tool (e.g. `wget`)?

**Comment by tamuanand** [comment]
Hi 

You are right - I can access it via wget.

Is there a way in which I can get this to work with a BioConda install of antiSMASH - probably, this might need updating some scripts on your end and then committing those changes to BioConda.

Thanks in advance.

**Comment by SJShaw** [comment]
Compared to FTP, HTTP takes about 10 times as long to download each Pfam release (11 seconds for FTP vs 126 for HTTP in my test just now), so I don't think it's a good idea to change from FTP in general.

Our scripts already check for existing files and skip downloads if present and allow for custom data directories, so you should be able to work around your FTP restriction.

- Create a directory somewhere for the antiSMASH data, I'll use `~/antismash_data` here as an example, change it to whatever you'd like instead.
- Create `.antismash5.cfg` file in your home directory with this line (ensure the path is absolute, if you're using something else)
```
databases ~/antismash_data
```
- Download and extract the Pfam databases (27.0 and 31.0) into your data directory so you have these two files in this layout (plus any other versions you wish to use):
```
~/antismash_data/pfam/27.0/Pfam-A.hmm
~/antismash_data/pfam/31.0/Pfam-A.hmm
```
- Run the conda install as previous

If you then want to use the default database location so it's removed automatically if you uninstall antiSMASH, just copy the `pfam` directory from that custom location to `wherever_conda_installed_antismash/data/pfam`, and you can then delete that custom location and the `.antismash5.cfg` file. Running antiSMASH with `--check-prereqs` will test that the databases are in the right place.

**Comment by tamuanand** [comment]
Thanks - I will give this a try.

A question: Why the need for 2 PFAM databases (the 27.0 and the 31.0) - wouldn't one suffice? Can I just download the version 31.0 of PFAM and use it OR do I absolutely need to have both the databases?

**Comment by SJShaw** [comment]
Version 27 is required for the clusterfinder module, as it was trained on that version and new versions will cause it to have issues. The later versions are just to keep to a newer dataset (arguably, we should update it to the latest which is 33).

If you don't intend to use clusterfinder, you can delete the v27 database afterwards and it shouldn't impact you at all.

At some stage we'd like to have a replacement for clusterfinder, but until then we're keeping it around for people who need something a little more exploratory.

**Comment by tamuanand** [comment]
Hi

Thanks for your replies - very very helpful.

Unfortunately, something is breaking - I was able to get thru the ftp install process by talking with the sysadmin and having temporary ftp access.

The conda install process now rolls back (or fails) with the `.antismash-post-link.sh` script as before but with different error message(s)

```
.............clipped for brevity.......................

Downloading and Extracting Packages
scikit-learn-0.22.2. | 7.1 MB    | ########### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

ERROR conda.core.link:_execute(700): An error occurred while installing package 'bioconda::antismash-5.1.1-py_0'.

Rolling back transaction: done

LinkError: post-link script failed for package bioconda::antismash-5.1.1-py_0
location of failed script: <path_to>/miniconda3/envs/antismash/bin/.antismash-post-link.sh

Traceback (most recent call last):
  File "<path_to>/miniconda3/envs/antismash/bin/download-antismash-databases", line 7, in <module>
    from antismash.download_databases import _main
  File "<path_to>/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/__init__.py", line 12, in <module>
    from antismash.main import run_antismash, get_detection_modules, \
  File "<path_to>/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/main.py", line 44, in <module>
    from antismash.modules import (active_site_finder,
  File "<path_to>/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/modules/lanthipeptides/__init__.py", line 13, in <module>
    from antismash.common.external.rodeo_svm.rebuild import pickle_classifier
  File "<path_to>/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/common/external/rodeo_svm/rebuild.py", line 9, in <module>
    from .svm_classify import save_classifier
  File "<path_to>/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/common/external/rodeo_svm/svm_classify.py", line 76, in <module>
    sklearn_int_versions = list(map(int, sklearn.__version__.split('.')))
ValueError: invalid literal for int() with base 10: 'post1'

return code: 1

()

```

**Comment by tamuanand** [comment]
Also, an observation -- ftp://ftp.ebi.ac.uk/pub/databases/Pfam/releases/Pfam33.0/ does not seem to have a PFAM-A.hmm file as one would normally see - say here - ftp://ftp.ebi.ac.uk/pub/databases/Pfam/releases/Pfam32.0/

> Version 27 is required for the clusterfinder module, as it was trained on that version and new versions will cause it to have issues. The later versions are just to keep to a newer dataset (arguably, we should update it to the latest which is 33).

**Comment by SJShaw** [comment]
Apparently `scikit-learn` [updated](https://github.com/scikit-learn/scikit-learn/releases) 5 hours ago and included the word 'post' to fix a packaging issue. If you install the prior version first (0.22.1) first with `pip install scikit-learn==0.22.1`, then hopefully that will work around it until we work out how to handle odd versions like this.

**Comment by tamuanand** [comment]
I installed `scikit-learn==0.22.1` separately and then went about the conda install

Looks like conda does not like me ;) 

Conda says it found incompatible packages, but does not list them -- the error message is strange, there is no output for the "Requested package --> Available versions line"

I am using conda 4.8.2 - Should I try something like this https://github.com/conda/conda/issues/9367#issuecomment-555156949

This is the error log on command line 

```
conda install antismash

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: /
Found conflicts! Looking for incompatible packages.                                                                                              failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions
```

**Comment by SJShaw** [comment]
I've not had good experiences with conda, myself, so I don't use it.

If you use a conda environment for only the binary dependencies you can't otherwise get via the default packaging repo of whatever your system is, then you can probably avoid most of the conda-specific issues. Create a new environment, download and extract the release tarball for antiSMASH (or clone the git repository), extract it somewhere, and `pip install .` in the resulting directory. That will give you a functional install without conda trying to get helpful and giving you that error with no information.

**Comment by tamuanand** [comment]
Just to confirm 

You are suggesting that I  `git clone from here - https://github.com/antismash/antismash`

And then if I do a `pip install . ` 

Will doing it this way take care of all databases downloads and dependencies?

**Comment by tamuanand** [comment]
I then did `conda install meme==4.1.12` and the `antismash --check-prereqs` now works ok.

However, upon job submission, I get the error as posted at https://github.com/antismash/antismash/issues/237

```
antismash -c 20 --cb-general --cb-knownclusters --cb-subclusters --asf --fullhmmer --pfam2go --smcog-trees --genefinding-tool prodigal  --skip-zip-
file --output-dir
```

**_This error message below gets repeated over many times_** depending on number of processes one has called on the command line:

Error

```
<path_to>/antismash/lib/python3.7/site-packages/scss/selector.py:54: FutureWarning: Possible nested set at position 329
  ''', re.VERBOSE | re.MULTILINE)
Process ForkPoolWorker-21:
Traceback (most recent call last):
  File "<path_to>/antismash/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "<path_to>/antismash/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "<path_to>/antismash/lib/python3.7/multiprocessing/pool.py", line 110, in worker
    task = get()
  File "<path_to>/antismash/lib/python3.7/multiprocessing/queues.py", line 354, in get
    return _ForkingPickler.loads(res)
  File "<path_to>/antismash/lib/python3.7/site-packages/antismash/common/secmet/qualifiers/nrps_pks.py", line 103, in extend
    raise NotImplementedError("Extending this list won't work")
NotImplementedError: Extending this list won't work
```

**Comment by SJShaw** [comment]
I'm going to close this issue since it's now diverging from the original and into other reported issues and the original issue is not something we can solve in general.

**Comment by surh** [comment]
I had the same problem as https://github.com/antismash/antismash/issues/245#issuecomment-594667890, the issue as noted has to to with scikit-learn but it cannot be solved by installing scikit-learn 0.22.1 as suggested at https://github.com/antismash/antismash/issues/245#issuecomment-594673396 because scikit-learn 0.20 was the last version to support python 2.7 (which is required by AntiSMASH 5). One has to force the installation of python 2.7 and let conda figure out the rest of the dependencies. Simply use:

```bash
conda create -n antismash5 python=2.7 scikit-learn antismash
```

**Comment by tamuanand** [comment]
> I had the same problem as [#245 (comment)](https://github.com/antismash/antismash/issues/245#issuecomment-594667890), the issue as noted has to to with scikit-learn but it cannot be solved by installing scikit-learn 0.22.1 as suggested at [#245 (comment)](https://github.com/antismash/antismash/issues/245#issuecomment-594673396) because scikit-learn 0.20 was the last version to support python 2.7 (which is required by AntiSMASH 5). One has to force the installation of python 2.7 and let conda figure out the rest of the dependencies. Simply use:
> 
> ```shell
> conda create -n antismash5 python=2.7 scikit-learn antismash
> ```

When you do it this way, only the old versions of many dependent software  get downloaded (for example `diamond 0.8.36, blast 2.2.31`)

**Comment by SJShaw** [comment]
> python 2.7 (which is required by AntiSMASH 5)

This is completely wrong. antiSMASH 5 requires >= python 3.5 (see: https://github.com/antismash/antismash/blob/master/setup.py#L97)

If you are running antiSMASH with python 2.7, you are running antiSMASH 4.

**Comment by surh** [comment]
you are right, I got confused because of an older antiSMASH 4 version I had installed, but then I was just simply able to install AntiSMASH 5 specifying an older scikit-learn

```bash
conda create --yes -n antismash5 scikit-learn=0.22.1 antismash=5
```
