### ISSUE TITLE
Help with full manual install of antiSMASH as non-root user

### ISSUE THREAD

**Issue by tamuanand** [antismash/antismash#247]
Hello antiSMASH developers.

Because of issues reported in https://github.com/antismash/antismash/issues/245#issuecomment-595424575 and https://github.com/antismash/antismash/issues/237, I am in the process of a full manual install of antiSMASH5.1.1

I would like your help and best practices in this effort. **Note:** I am doing this as a non-root user.

I ultimately want to run antiSMASH on a SGE/LSF cluster.

### What I have so far
Using https://docs.antismash.secondarymetabolites.org/install/#full-manual-install as guide:

1. Installed all the dependencies from their tarballs (diamond, FastTree, glimmerHMM, hmmer2, hmmer3, meme, muscle, NCBI BLAST+, Prodigal) - made sure hmmer2 and hmmer3 were in separate directories, changed hmmer2 executables as advised 

- Some links in the above documentation are broken. Correct links here:
```
hmmer3 and hmmer2 - http://hmmer.org/download.html
Prodigal - https://github.com/hyattpd/Prodigal/wiki/installation
```
2. After all the above installs as a non-root user, I have this directory `<path_to>/install_source_antismash/bin` which has all the executables from the above dependencies 

3. I then installed antiSMASH5.1.1 from the tarball and during install I mentioned this on command line
`pip install --install-option="--prefix=<path_to>/install_source_antismash" ./antismash-5.1.1`

- `Successfully installed antismash bcbio-gff helperlibs pyScss pysvg-py3`
- I can see the `antismash` executable and `download-antismash-databases` executable at `<path_to>/install_source_antismash/bin`

### Where I am stuck and I need help

1. When I try doing `<path_to>/install_source_antismash/bin/antismash --help`, I cannot get the help text one would get from doing a conda install

2. How do I get the `download-antismash-databases` script to work correctly and make sure the relevant databases are downloaded correctly such that I can use it with the antismash executable

3. Are there any changes need such that the `<path_to>/install_source_antismash/bin/antismash` executable knows where the other executables are (hmmer3, hmmer2, prodigal, etc)

Thanks in advance.

**Comment by kblin** [comment]
If you install the required binaries in a directory that's not in your shell's `$PATH` variable, you need to extend that variable so the shell can find your executables. Assuming you're on bash, `export PATH=$PATH:"<path_to>/install_source_antismash/bin"` should do the trick. Then e.g. `prodigal -v` should print the prodigal version, same for all the other executables you installed.

I think fixing the `$PATH` will fix all the parts you're stuck with, if not, we'll need to know more detailed errors than "doesn't work".

**Comment by SJShaw** [comment]
You can also use an antiSMASH argument to specify alternate binaries to use instead of the PATH defaults, e.g.:
`--executable-paths hmmpfam2=/some/other/binary/path,prodigal=~/my_prodigal/prodigal`

**Comment by tamuanand** [comment]
Thanks - adding the $PATH did the trick.

I have given details above on some broken links to some of the tools (hammer, prodigal) - I suggest updating the docs to reflect that as it will help others.

Thanks.
