### ISSUE TITLE
AntiSMASH 5.2.0 likely release

### ISSUE THREAD

**Issue by tamuanand** [antismash/antismash#257]
Hi

Just curious - when would antiSMASH 5.2.0 be available? I have seen some threads about a new PFAM2GO in 5.2.0 

Thanks

**Comment by kblin** [comment]
We have just pushed that pfam2go update to the git master branch. Once we are happy with how it runs on our test data sets we'll look into releasing 5.2.0
In the current situation it's a bit hard to commit to any specific dates.
