### ISSUE TITLE
The error is install antiSMASH by full manual install

### ISSUE THREAD

**Issue by YakunWang-0125** [antismash/antismash#258]
Hi, I'm so glad you checked this question！
  
  I‘m install antiSMASH on Ubuntu according one option full manual install. https://docs.antismash.secondarymetabolites.org/install/#installing-the-latest-antismash-release
The command is as follows: 

# Dependencies
sudo apt-get update
sudo apt-get install -y apt-transport-https
sudo wget http://dl.secondarymetabolites.org/antismash-stretch.list -O /etc/apt/sources.list.d/antismash.list
sudo wget -q -O- http://dl.secondarymetabolites.org/antismash.asc | sudo apt-key add -
sudo apt-get update
sudo apt-get install hmmer2 hmmer diamond-aligner fasttree prodigal ncbi-blast+ muscle glimmerhmm
# Create and activate a virtual environment
virtualenv -p $(which python3) ~/as5env
source ~/as5env/bin/activate
# Installing the latest antiSMASH release
wget https://dl.secondarymetabolites.org/releases/5.1.1/antismash-5.1.1.tar.gz
tar -zxf antismash-5.1.1.tar.gz
pip install ./antismash-5.1.1
download-antismash-databases

According to the command, I've successfully installed dependencies and activated the environment, Running the command pip install ./antismash-5.1.1, I got a result as fallows: 
Successfully built antismash bcbio-gff pyScss
Installing collected packages: bcbio-gff, biopython, helperlibs, MarkupSafe, jinja2, cycler, kiwisolver, pyparsing, matplotlib, pyScss, pysvg-py3, joblib, scikit-learn, antismash
  The scripts less2scss and pyscss are installed in '/home/wangyakun/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  The scripts antismash and download-antismash-databases are installed in '/home/wangyakun/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed MarkupSafe-1.1.1 antismash-5.1.1 bcbio-gff-0.6.6 biopython-1.76 cycler-0.10.0 helperlibs-0.1.11 jinja2-2.11.2 joblib-0.14.1 kiwisolver-1.2.0 matplotlib-3.2.1 pyScss-1.3.7 pyparsing-2.4.7 pysvg-py3-0.2.2.post3 scikit-learn-0.22.2.post1

Continue to run the command download-antismash-databases, I got an error: 
download-antismash-databases: command not found

I don't know where the problem occurred. Please! help me solve this problem, thank you very much!

**Comment by SJShaw** [comment]
> The scripts antismash and download-antismash-databases are installed in '/home/wangyakun/.local/bin' which is not on PATH.
Consider adding this directory to PATH

If you follow that advice, the problem should be solved for you. I haven't seen pip do that before, so I'm assuming it's something to do with a specific configuration or version.

**Comment by YakunWang-0125** [comment]
Really glad to receive your response!
Based on your suggestion, I tried adding the path and running the command：
download-antismash-databases
I got a new error:
/home/wangyakun/.local/lib/python3.7/site-packages/sklearn/externals/joblib/__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)
Traceback (most recent call last):
  File "/home/wangyakun/.local/bin/download-antismash-databases", line 6, in <module>
    from antismash.download_databases import _main
  File "/home/wangyakun/.local/lib/python3.7/site-packages/antismash/__init__.py", line 12, in <module>
    from antismash.main import run_antismash, get_detection_modules, \
  File "/home/wangyakun/.local/lib/python3.7/site-packages/antismash/main.py", line 44, in <module>
    from antismash.modules import (active_site_finder,
  File "/home/wangyakun/.local/lib/python3.7/site-packages/antismash/modules/lanthipeptides/__init__.py", line 13, in <module>
    from antismash.common.external.rodeo_svm.rebuild import pickle_classifier
  File "/home/wangyakun/.local/lib/python3.7/site-packages/antismash/common/external/rodeo_svm/rebuild.py", line 9, in <module>
    from .svm_classify import save_classifier
  File "/home/wangyakun/.local/lib/python3.7/site-packages/antismash/common/external/rodeo_svm/svm_classify.py", line 76, in <module>
    sklearn_int_versions = list(map(int, sklearn.__version__.split('.')))
ValueError: invalid literal for int() with base 10: 'post1'
I just started to study bioinformatics and lack of computer background, I can't understand these issues very well. Hope you can help me answer, thank you!

**Comment by YakunWang-0125** [comment]
> > The scripts antismash and download-antismash-databases are installed in '/home/wangyakun/.local/bin' which is not on PATH.
> > Consider adding this directory to PATH
> 
> If you follow that advice, the problem should be solved for you. I haven't seen pip do that before, so I'm assuming it's something to do with a specific configuration or version.

Really glad to receive your response!
Based on your suggestion, I tried adding the path and running the command：
download-antismash-databases
I got a new error:
/home/wangyakun/.local/lib/python3.7/site-packages/sklearn/externals/joblib/__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)
Traceback (most recent call last):
  File "/home/wangyakun/.local/bin/download-antismash-databases", line 6, in <module>
    from antismash.download_databases import _main
  File "/home/wangyakun/.local/lib/python3.7/site-packages/antismash/__init__.py", line 12, in <module>
    from antismash.main import run_antismash, get_detection_modules, \
  File "/home/wangyakun/.local/lib/python3.7/site-packages/antismash/main.py", line 44, in <module>
    from antismash.modules import (active_site_finder,
  File "/home/wangyakun/.local/lib/python3.7/site-packages/antismash/modules/lanthipeptides/__init__.py", line 13, in <module>
    from antismash.common.external.rodeo_svm.rebuild import pickle_classifier
  File "/home/wangyakun/.local/lib/python3.7/site-packages/antismash/common/external/rodeo_svm/rebuild.py", line 9, in <module>
    from .svm_classify import save_classifier
  File "/home/wangyakun/.local/lib/python3.7/site-packages/antismash/common/external/rodeo_svm/svm_classify.py", line 76, in <module>
    sklearn_int_versions = list(map(int, sklearn.__version__.split('.')))
ValueError: invalid literal for int() with base 10: 'post1'
I just started to study bioinformatics and lack of computer background, I can't understand these issues very well. Hope you can help me answer, thank you!

**Comment by SJShaw** [comment]
This issue was fixed in antiSMASH 5.1.2, you should update.
