### ISSUE TITLE
Feature request: text-based output for automated high-throughput screening

### ISSUE THREAD

**Issue by sjaenick** [antismash/antismash#261]
**Is your feature request related to a problem? Please describe.**
I'd like to perform screening of metagenomic assemblies for nrps/pks
gene clusters in an automated way. So far, antiSMASH generates reports
aimed at the end user, i.e. graphical web pages, and it's somewhat difficult
to automatically extract relevant predictions programatically.

**Describe the solution you'd like**
I'd be happy to see a text-based output format such as .tsv that is easy to parse and integrate
into existing analysis pipelines.

**Comment by SJShaw** [comment]
This has been covered [previously](https://github.com/antismash/antismash/issues/128#issuecomment-480355708), including reasoning and some script examples.

TSV/CSV files can't handle hierarchical data and every user will want slightly different information in single flat file like that. Most scripting languages can parse JSON without any issue, and if you've already got python installed for antiSMASH, then it's trivial to use antiSMASH itself to read in the genbank or JSON outputs.

If there's some data that's present in the HTML but not in the genbank or JSON outputs, that's something we can correct for those files, you'll just need to let us know what it is.

**Comment by sjaenick** [comment]
ok, thanks for the pointer.
