### ISSUE TITLE
diamond failed to run with no error details

### ISSUE THREAD

**Issue by ZepingQu** [antismash/antismash#262]
**Describe the bug**
Getting RuntimeError: diamond failed to run: blastp -> when running antiSMASH conda version with options "--cb-general" or "--cb-knownclusters" on gbk files.

**Expected behavior**
Expecting to see the antiSMASH finish its run as normal.

**To Reproduce**
the gbk file that I'm doing my test run is included in the attachment as a txt file.
[35302.assembled.gbk.txt](https://github.com/antismash/antismash/files/4533565/35302.assembled.gbk.txt)

here is the full error information:

antismash --cb-general --output-dir ./out 35302.assembled.gbk 
/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/scss/selector.py:54: FutureWarning: Possible nested set at position 329
  ''', re.VERBOSE | re.MULTILINE)
Traceback (most recent call last):
  File "/opt/anaconda3/envs/antismash/bin/antismash", line 10, in <module>
    sys.exit(entrypoint())
  File "/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/__main__.py", line 126, in entrypoint
    sys.exit(main(sys.argv[1:]))
  File "/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/__main__.py", line 115, in main
    antismash.run_antismash(sequence, options)
  File "/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/main.py", line 612, in run_antismash
    result = _run_antismash(sequence_file, options)
  File "/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/main.py", line 676, in _run_antismash
    analysis_timings = analyse_record(record, options, analysis_modules, module_results)
  File "/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/main.py", line 265, in analyse_record
    run_module(record, module, options, previous_result, timings)
  File "/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/main.py", line 237, in run_module
    results = module.run_on_record(record, results, options)
  File "/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/modules/clusterblast/__init__.py", line 146, in run_on_record
    results.general = perform_clusterblast(options, record, clusters, proteins)
  File "/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/modules/clusterblast/clusterblast.py", line 42, in perform_clusterblast
    blastoutput = run_diamond_on_all_regions(regions, database)
  File "/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/modules/clusterblast/core.py", line 82, in run_diamond_on_all_regions
    stdout = subprocessing.run_diamond_search(temp_file.name, database, mode="blastp", opts=extra_args)
  File "/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/common/subprocessing/diamond.py", line 68, in run_diamond_search
    return run_diamond(mode, args).stdout
  File "/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/common/subprocessing/diamond.py", line 42, in run_diamond
    raise RuntimeError("diamond failed to run: %s -> %s" % (subcommand, result.stderr[-100:]))
RuntimeError: diamond failed to run: blastp -> 

**System (please complete the following information):**
 - OS: macOS 10.15.3
 - antiSMASH: conda version 5.1.2

**Additional context**
this error doesn't seem to be caused by my gbk file, as all things seem okay when running my gbk file on the website version of antiSMASH, and I have tried this on multiple gbk files, and the error seems to persist.

**Comment by SJShaw** [comment]
The `diamond` dependency has an issue and doesn't have any stderr to display, which is very unusual.

Is it actually `diamond`, the alignment tool, and not something else? If it is, what version is it?

**Comment by ZepingQu** [comment]
I'm sorry but how do I check this?

**Comment by ZepingQu** [comment]
Actually, do I need to install the "Dependencies via Bioconda" part under the "Manual install" part? Is it caused by me not doing that?

**Comment by SJShaw** [comment]
If you installed antiSMASH via bioconda, then you don't need to do that part.

In your conda environment you use for antiSMASH, run the command `diamond version`.

**Comment by ZepingQu** [comment]
> If you installed antiSMASH via bioconda, then you don't need to do that part.
> 
> In your conda environment you use for antiSMASH, run the command `diamond version`.

Thanks, the diamond version is 0.9.32

**Comment by SJShaw** [comment]
Try running with `--check-prereqs` to ensure the relevant databases are properly set up for that version of diamond.
Then run on the [nisin](https://github.com/antismash/antismash/blob/master/antismash/test/integration/data/nisin.gbk) genbank that is used in some of our tests.

If the same issue happens, then it's something to do with your specific environment.

**Comment by ZepingQu** [comment]
> Try running with `--check-prereqs` to ensure the relevant databases are properly set up for that version of diamond.
> Then run on the [nisin](https://github.com/antismash/antismash/blob/master/antismash/test/integration/data/nisin.gbk) genbank that is used in some of our tests.
> 
> If the same issue happens, then it's something to do with your specific environment.

It says "All prerequisites satisfied", but the same issue persists. Do you have any suggestions on how to deal with this? Thanks

**Comment by SJShaw** [comment]
There shouldn't be anything else you need if you've installed via conda, as that's what conda is intended to solve for you. That said, if it's an issue with conda not installing it correctly, then it's an issue for conda instead of us.

Here's another thing to try to get more information on what might be happening:

Create a file named `prot_query.fa` with contents:
```
>A
AAAAA
```

Find your antiSMASH install directory, and replace `ANTISMASH_INSTALL_DIR` in the following command with it, then run it.

`diamond blastp --threads 2 --db ANTISMASH_INSTALL_DIR/antismash/modules/clusterblast/data/known/proteins --query prot_query.fa --compress 0 --max-target-seqs 10000 --evalue 1e-05 --outfmt 6`

If that completes successfully, then I've got no idea why the errors would be occcuring.

If it doesn't complete successfully, then we could use whatever error message it tells you to try and work out what's going wrong.

**Comment by ZepingQu** [comment]
> There shouldn't be anything else you need if you've installed via conda, as that's what conda is intended to solve for you. That said, if it's an issue with conda not installing it correctly, then it's an issue for conda instead of us.
> 
> Here's another thing to try to get more information on what might be happening:
> 
> Create a file named `prot_query.fa` with contents:
> 
> ```
> >A
> AAAAA
> ```
> 
> Find your antiSMASH install directory, and replace `ANTISMASH_INSTALL_DIR` in the following command with it, then run it.
> 
> `diamond blastp --threads 2 --db ANTISMASH_INSTALL_DIR/antismash/modules/clusterblast/data/known/proteins --query prot_query.fa --compress 0 --max-target-seqs 10000 --evalue 1e-05 --outfmt 6`
> 
> If that completes successfully, then I've got no idea why the errors would be occcuring.
> 
> If it doesn't complete successfully, then we could use whatever error message it tells you to try and work out what's going wrong.

So I would get the following message if I follow your instruction:

No such file or directory
Error: Error opening file /opt/anaconda3/pkgs/antismash-5.1.2-py_0/site-packages/antismash/modules/clusterblast/data/known/proteins

However, If I run on "/opt/anaconda3/pkgs/antismash-5.1.2-py_0/site-packages/antismash/modules/clusterblast/data/known/proteins.fasta", I would get no error message.

**Comment by SJShaw** [comment]
Specifying `proteins.fasta` should be incorrect, as diamond automatically appends `.dmnd` to the given filename. We've run it with 0.9.32 on a linux system and it's as expected, so possibly that's an issue with diamond on mac. Even in that case, that error message should come through in your trace and it isn't.

The other thing that it could be is that you just don't have enough memory for diamond to run on the full clusterblast database. If you run without the `--cb-g` option but still with `--cb-k`, does it still cause errors?

**Comment by ZepingQu** [comment]
Yes, it still causes the error, though the error message is slightly different here:

antismash --cb-knownclusters --output-dir ./out nisin.gbk 
/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/scss/selector.py:54: FutureWarning: Possible nested set at position 329
  ''', re.VERBOSE | re.MULTILINE)
Traceback (most recent call last):
  File "/opt/anaconda3/envs/antismash/bin/antismash", line 10, in <module>
    sys.exit(entrypoint())
  File "/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/__main__.py", line 126, in entrypoint
    sys.exit(main(sys.argv[1:]))
  File "/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/__main__.py", line 115, in main
    antismash.run_antismash(sequence, options)
  File "/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/main.py", line 612, in run_antismash
    result = _run_antismash(sequence_file, options)
  File "/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/main.py", line 676, in _run_antismash
    analysis_timings = analyse_record(record, options, analysis_modules, module_results)
  File "/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/main.py", line 265, in analyse_record
    run_module(record, module, options, previous_result, timings)
  File "/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/main.py", line 237, in run_module
    results = module.run_on_record(record, results, options)
  File "/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/modules/clusterblast/__init__.py", line 150, in run_on_record
    results.knowncluster = run_knownclusterblast_on_record(record, options)
  File "/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/modules/clusterblast/known.py", line 90, in run_knownclusterblast_on_record
    return perform_knownclusterblast(options, record, clusters, proteins)
  File "/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/modules/clusterblast/known.py", line 114, in perform_knownclusterblast
    blastoutput = run_diamond_on_all_regions(record.get_regions(), _get_datafile_path('proteins'))
  File "/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/modules/clusterblast/core.py", line 82, in run_diamond_on_all_regions
    stdout = subprocessing.run_diamond_search(temp_file.name, database, mode="blastp", opts=extra_args)
  File "/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/common/subprocessing/diamond.py", line 68, in run_diamond_search
    return run_diamond(mode, args).stdout
  File "/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/common/subprocessing/diamond.py", line 42, in run_diamond
    raise RuntimeError("diamond failed to run: %s -> %s" % (subcommand, result.stderr[-100:]))
RuntimeError: diamond failed to run: blastp ->

**Comment by SJShaw** [comment]
The stack trace changing is unsurprising, since it's not running general clusterblast this time. It's possibly still a memory issue if you've got less than 16GB of RAM.

In `/opt/anaconda3/pkgs/antismash-5.1.2-py_0/site-packages/antismash/modules/clusterblast/data/known/` is there any file with the extension `.dmnd`?

**Comment by ZepingQu** [comment]
No, there is only a fasta and a txt file

**Comment by SJShaw** [comment]
That you're missing a `.dmnd` file is a big issue.

Can you provide the output of running with `--check-prereqs --debug`?

**Comment by ZepingQu** [comment]
yes, here it is:

antismash --check-prereqs --debug
/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/scss/selector.py:54: FutureWarning: Possible nested set at position 329
  ''', re.VERBOSE | re.MULTILINE)
INFO     30/04 07:23:30   antiSMASH version: 5.1.2
INFO     30/04 07:23:30   diamond using executable: /opt/anaconda3/envs/antismash/bin/diamond (0.9.32)
INFO     30/04 07:23:30   hmmpfam2 using executable: /opt/anaconda3/envs/antismash/bin/hmmpfam2 (2.3.2)
INFO     30/04 07:23:30   fasttree using executable: /opt/anaconda3/envs/antismash/bin/fasttree
INFO     30/04 07:23:30   hmmsearch using executable: /opt/anaconda3/envs/antismash/bin/hmmsearch (3.1b2)
INFO     30/04 07:23:30   hmmpress using executable: /opt/anaconda3/envs/antismash/bin/hmmpress (3.1b2)
INFO     30/04 07:23:30   hmmscan using executable: /opt/anaconda3/envs/antismash/bin/hmmscan (3.1b2)
INFO     30/04 07:23:30   meme using executable: /opt/anaconda3/envs/antismash/bin/meme (4.11.2)
INFO     30/04 07:23:30   fimo using executable: /opt/anaconda3/envs/antismash/bin/fimo (4.11.2)
INFO     30/04 07:23:30   glimmerhmm using executable: /opt/anaconda3/envs/antismash/bin/glimmerhmm
INFO     30/04 07:23:30   prodigal using executable: /opt/anaconda3/envs/antismash/bin/prodigal (V2.6.3)
INFO     30/04 07:23:30   muscle using executable: /opt/anaconda3/envs/antismash/bin/muscle (v3.8.1551)
INFO     30/04 07:23:31   java using executable: /usr/bin/java (1.8.0_172)
INFO     30/04 07:23:31   blastp using executable: /opt/anaconda3/envs/antismash/bin/blastp (2.2.31+)
INFO     30/04 07:23:31   makeblastdb using executable: /opt/anaconda3/envs/antismash/bin/makeblastdb (2.2.31+)
DEBUG    30/04 07:23:31   Checking prerequisites for antismash.detection.genefinding
DEBUG    30/04 07:23:31   Checking prerequisites for antismash.detection.hmm_detection
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/detection/hmm_detection/data/bgc_seeds.hmm'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/detection/hmm_detection/data/bgc_seeds.hmm.h3f'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/detection/hmm_detection/data/bgc_seeds.hmm.h3i'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/detection/hmm_detection/data/bgc_seeds.hmm.h3m'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/detection/hmm_detection/data/bgc_seeds.hmm.h3p'
DEBUG    30/04 07:23:31   Checking prerequisites for antismash.detection.nrps_pks_domains
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/detection/nrps_pks_domains/data/abmotifs.hmm.h3f'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/detection/nrps_pks_domains/data/abmotifs.hmm.h3i'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/detection/nrps_pks_domains/data/abmotifs.hmm.h3m'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/detection/nrps_pks_domains/data/abmotifs.hmm.h3p'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/detection/nrps_pks_domains/data/dockingdomains.hmm.h3f'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/detection/nrps_pks_domains/data/dockingdomains.hmm.h3i'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/detection/nrps_pks_domains/data/dockingdomains.hmm.h3m'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/detection/nrps_pks_domains/data/dockingdomains.hmm.h3p'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/detection/nrps_pks_domains/data/ksdomains.hmm.h3f'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/detection/nrps_pks_domains/data/ksdomains.hmm.h3i'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/detection/nrps_pks_domains/data/ksdomains.hmm.h3m'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/detection/nrps_pks_domains/data/ksdomains.hmm.h3p'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/detection/nrps_pks_domains/data/nrpspksdomains.hmm.h3f'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/detection/nrps_pks_domains/data/nrpspksdomains.hmm.h3i'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/detection/nrps_pks_domains/data/nrpspksdomains.hmm.h3m'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/detection/nrps_pks_domains/data/nrpspksdomains.hmm.h3p'
DEBUG    30/04 07:23:31   Checking prerequisites for antismash.detection.full_hmmer
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/databases/pfam/31.0/Pfam-A.hmm'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/databases/pfam/31.0/Pfam-A.hmm.h3f'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/databases/pfam/31.0/Pfam-A.hmm.h3i'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/databases/pfam/31.0/Pfam-A.hmm.h3m'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/databases/pfam/31.0/Pfam-A.hmm.h3p'
DEBUG    30/04 07:23:31   Checking prerequisites for antismash.detection.cassis
DEBUG    30/04 07:23:31   Checking prerequisites for antismash.detection.clusterfinder_probabilistic
DEBUG    30/04 07:23:31   Checking prerequisites for antismash.detection.cluster_hmmer
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/databases/pfam/31.0/Pfam-A.hmm'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/databases/pfam/31.0/Pfam-A.hmm.h3f'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/databases/pfam/31.0/Pfam-A.hmm.h3i'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/databases/pfam/31.0/Pfam-A.hmm.h3m'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/databases/pfam/31.0/Pfam-A.hmm.h3p'
DEBUG    30/04 07:23:31   Checking prerequisites for antismash.detection.genefunctions
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/databases/resfam/Resfams.hmm'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/detection/genefunctions/data/smcogs.hmm.h3f'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/detection/genefunctions/data/smcogs.hmm.h3i'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/detection/genefunctions/data/smcogs.hmm.h3m'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/detection/genefunctions/data/smcogs.hmm.h3p'
DEBUG    30/04 07:23:31   Checking prerequisites for antismash.modules.smcog_trees
DEBUG    30/04 07:23:31   Checking prerequisites for antismash.modules.tta
DEBUG    30/04 07:23:31   Checking prerequisites for antismash.modules.lanthipeptides
DEBUG    30/04 07:23:31   missing cached SVM classifiers, rebuilding
DEBUG    30/04 07:23:31   Checking prerequisites for antismash.modules.thiopeptides
DEBUG    30/04 07:23:31   Checking prerequisites for antismash.modules.nrps_pks
DEBUG    30/04 07:23:31   Checking prerequisites for antismash.modules.clusterblast
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/modules/clusterblast/data/known/clusters.txt'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/modules/clusterblast/data/known/proteins.fasta'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/modules/clusterblast/data/known/proteins.dmnd'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/modules/clusterblast/data/known/proteins.dmnd'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/databases/clusterblast/clusters.txt'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/databases/clusterblast/proteins.fasta'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/databases/clusterblast/proteins.dmnd'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/databases/clusterblast/proteins.dmnd'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/modules/clusterblast/data/sub/proteins.fasta'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/modules/clusterblast/data/sub/proteins.fasta.phr'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/modules/clusterblast/data/sub/proteins.fasta.pin'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/modules/clusterblast/data/sub/proteins.fasta.psq'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/modules/clusterblast/data/sub/clusters.txt'
DEBUG    30/04 07:23:31   Checking prerequisites for antismash.modules.sactipeptides
DEBUG    30/04 07:23:31   Checking prerequisites for antismash.modules.lassopeptides
DEBUG    30/04 07:23:31   Checking prerequisites for antismash.modules.active_site_finder
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/modules/active_site_finder/data/PKSI-KR.hmm2'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/modules/active_site_finder/data/PKSI-KS_N.hmm2'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/modules/active_site_finder/data/PKSI-KS_C.hmm2'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/modules/active_site_finder/data/PKSI-AT.hmm2'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/modules/active_site_finder/data/PKSI-ACP.hmm2'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/modules/active_site_finder/data/PKSI-DH.hmm2'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/modules/active_site_finder/data/Thioesterase.hmm2'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/modules/active_site_finder/data/PKSI-ER.hmm2'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/modules/active_site_finder/data/p450.hmm2'
DEBUG    30/04 07:23:31   Checking prerequisites for antismash.modules.pfam2go
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/modules/pfam2go/data/pfam2go-march-2018.txt'
DEBUG    30/04 07:23:31   Checking prerequisites for antismash.modules.t2pks
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/modules/t2pks/data/KSIII.fasta'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/modules/t2pks/data/KSIII.phr'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/modules/t2pks/data/KSIII.pin'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/modules/t2pks/data/KSIII.psq'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/modules/t2pks/data/AT.fasta'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/modules/t2pks/data/AT.phr'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/modules/t2pks/data/AT.pin'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/modules/t2pks/data/AT.psq'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/modules/t2pks/data/LIG.fasta'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/modules/t2pks/data/LIG.phr'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/modules/t2pks/data/LIG.pin'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/modules/t2pks/data/LIG.psq'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/modules/t2pks/data/t2pks.hmm.h3f'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/modules/t2pks/data/t2pks.hmm.h3i'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/modules/t2pks/data/t2pks.hmm.h3m'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/modules/t2pks/data/t2pks.hmm.h3p'
DEBUG    30/04 07:23:31   Checking prerequisites for antismash.outputs.html
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/outputs/html/css/bacteria.css'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/outputs/html/css/fungi.css'
DEBUG    30/04 07:23:31   Found file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/outputs/html/css/plants.css'
All prerequisites satisfied

**Comment by SJShaw** [comment]
That says you have the file in the right place 

> Found` file '/opt/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/modules/clusterblast/data/known/proteins.dmnd

The path you used previously was:
> /opt/anaconda3/pkgs/antismash-5.1.2-py_0/site-packages/antismash/modules/clusterblast/data/known

These are very different locations.

**Comment by ZepingQu** [comment]
Oh sorry about that. So I went back and tried the previous test on prot_query.fa, and got no error message.

**Comment by ZepingQu** [comment]
Does this means that this is an issue caused by not having a large enough RAM?

**Comment by SJShaw** [comment]
Looks like it. To confirm it, you'll need to dig around in your system logs for the relevant errors (and I'm not quite sure how macOS handles this, but as a starter, you can try `dmesg | grep 'killed process'` or similar).

**Comment by ZepingQu** [comment]
is there any other keyword you would suggest looking for? I tried quite a few keywords and nothing came up, then I tried running sudo dmesg straight after running --cb-g, but I cannot find any useful information. Was running dmesg straight after running antismash correct? Thanks

**Comment by SJShaw** [comment]
It should cover quite a long time prior to running it, as it's just pulling from one of the system log files. I've never used a mac, so I can't help with this, sorry. Maybe someone else reading this knows.

**Comment by ZepingQu** [comment]
Okay, thank you so much for your help, I guess I'll just try to find a linux machine with enough RAM to continue my work.

Thank you again for creating this wonderful tool, and please take care during this difficult period.

**Comment by ZepingQu** [comment]
Issue solved, error no longer exists after switching to ubuntu with 16gb of RAM.

Thanks for helping!

**Comment by ZepingQu** [comment]
Issue solved, error no longer exists after switching to ubuntu with 16gb of RAM.

Thanks for helping!

**Comment by SJShaw** [comment]
I've just come across someone else who had a similar error message and it was because the homebrew diamond installs on macOS was compiled for a different CPU architecture and was dying halfway through with an 'illegal instruction' error. It's possible that it was the cause of this issue too, if anyone comes across this.

**Comment by ZepingQu** [comment]
> I've just come across someone else who had a similar error message and it was because the homebrew diamond installs on macOS was compiled for a different CPU architecture and was dying halfway through with an 'illegal instruction' error. It's possible that it was the cause of this issue too, if anyone comes across this.

So does this mean it will be solved if I install a ubuntu system on MacBook or is it a problem with the specific type of CPU macs use? From the information I have, it seems like all Macbooks are using intel chips?

**Comment by SJShaw** [comment]
Not all intel chips have the same instruction set, but that said it looks to possibly be a compiler error, going by the [commit ](https://github.com/bbuchfink/diamond/commit/232967c0e127035eaab0c679b79b15d0a0dccce9) to fix one such case in the diamond source.

Using ubuntu instead will solve the issue, I imagine, but since it's specific to diamond, it should be solvable with changes to diamond (and/or recompiling on your machine, if it's an instruction set issue).
