### ISSUE TITLE
Questions on quality of genome data

### ISSUE THREAD

**Issue by ZepingQu** [antismash/antismash#265]
Hi,

I occasionally would get "BiopythonParserWarning: Truncated LOCUS line found" when running on some gbk files, and further investigation suggests that such gbk files have quite a few "LOCUS" line, likely meaning that there is more than one contig in the genome file. Is this a sign of low-quality testing on the genome sequence? If so, do you have any suggestions on how many contigs can exist in a gbk file to make the antismash results meaningful?

Thanks

**Comment by SJShaw** [comment]
In general, the fewer the better. Plasmids being their own contig is not a problem, so just having a single contig isn't necessarily better than having multiple. Having hundreds or thousands of contigs is usually a bad sign.

However, the important part for antiSMASH analysis is where the contig breaks are.
If a sequence is fragmented and the cut(s) happen to be where a gene cluster would have been found, then it will cause the cluster to be missed completely, missing a section, or be reported as multiple independent regions. This can also apply to circular genomes where the origin is not dnaA and is located in what should be a cluster, so just making it a a single contig can still negatively impact your results.

**Comment by ZepingQu** [comment]
Got it, thank you.
A side question though, is it possible to compare the result BGCs from antismash with each other instead of comparing to the default database?
Thanks

**Comment by SJShaw** [comment]
That's essentially #201 and #203. I've got most of a clusterblast update done that will cover those, I just need to finish the current work of mine which is more time sensitive, then I'll be back on the "customblast".

**Comment by ZepingQu** [comment]
> That's essentially #201 and #203. I've got most of a clusterblast update done that will cover those, I just need to finish the current work of mine which is more time sensitive, then I'll be back on the "customblast".

Thanks, but maybe I missed something, is there a flag we can find for "region on contig edge" in the output gbk files?

**Comment by SJShaw** [comment]
You'll see `/contig_edge="True"` as a qualifier if it was on the contig edge.
