### ISSUE TITLE
no module named cStringIO

### ISSUE THREAD

**Issue by anotherXinzhu** [antismash/antismash#267]
Hi !

I managed to install all the dependencies via conda, download and pip install antismash-5.1.1 following the guidance. However, when I tried to run "download-antismash-databases" and "antismash -check-prereqs", same errors occured :

`(antismash5) Xinzhus-MacBook-Air:~ xinzhuyi$ antismash -check-prereqs
Traceback (most recent call last):
  File "/anaconda3/envs/antismash5/lib/python3.7/site-packages/helperlibs/bio/seqio.py", line 21, in <module>
    from cStringIO import StringIO
ModuleNotFoundError: No module named 'cStringIO'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/envs/antismash5/bin/antismash", line 5, in <module>
    from antismash.__main__ import entrypoint
  File "/anaconda3/envs/antismash5/lib/python3.7/site-packages/antismash/__init__.py", line 12, in <module>
    from antismash.main import run_antismash, get_detection_modules, \
  File "/anaconda3/envs/antismash5/lib/python3.7/site-packages/antismash/main.py", line 31, in <module>
    from antismash.common import logs, record_processing, serialiser
  File "/anaconda3/envs/antismash5/lib/python3.7/site-packages/antismash/common/record_processing.py", line 16, in <module>
    from helperlibs.bio import seqio
  File "/anaconda3/envs/antismash5/lib/python3.7/site-packages/helperlibs/bio/seqio.py", line 23, in <module>
    from Bio._py3k import StringIO
ModuleNotFoundError: No module named 'Bio._py3k'`

I then tried to install cStringIO, neither pip install nor conda install  could find this module. 
Any suggestion on this issue?

**Comment by kblin** [comment]
Hi, what version of Biopython do you have installed?

**Comment by kblin** [comment]
Ok, I could reproduce this outside of conda. Turns out that Biopython 1.77 dropped some features another library we use relied on. If you downgrade Biopython to 1.76, things should work again.

**Comment by kblin** [comment]
Alternatively, you could `pip install -U helperlibs` to get version 0.2.0 of the helperlibs library, which works correctly with Biopython 1.77.
Let us know if there still is a problem with antiSMASH after upgrading helperlibs or downgrading Biopython.

**Comment by anotherXinzhu** [comment]
Thanks for the reply! I didn’t continue on manual installation because there seems to always have some issues pumping up. I find the antismash 5.1.2 is available on Bioconda and one step installation is straightforwad and successful.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Kai Blin<mailto:notifications@github.com>
发送时间: 2020年5月29日 23:50
收件人: antismash/antismash<mailto:antismash@noreply.github.com>
抄送: anotherXinzhu<mailto:labxz@hotmail.com>; Author<mailto:author@noreply.github.com>
主题: Re: [antismash/antismash] no module named cStringIO (#267)


Alternatively, you could pip install -U helperlibs to get version 0.2.0 of the helperlibs library, which works correctly with Biopython 1.77.
Let us know if there still is a problem with antiSMASH after upgrading helperlibs or downgrading Biopython.

―

**Comment by anotherXinzhu** [comment]
There is another question that I would like to consult you on. I used to run antismash 4.2.0 but the -c (cpu) option seems to be not working, and some times the program exists with “ERROR   29/05 11:00:21   run_parallel_fastree: child 34810 exited with code 1”at SANDPUMA stage.That’s why I gave up version 4.2.0 and switch to version 5.



My issue is when I use version 4.2.0 with the -inclusive option, I get quite a number of predicted BGCs named “cf_****”.  However, with version 5.1.2, --cf-create-clusters (with default settings) barely detects any extra cluster. My question is what is the difference between these two algorithms (I thought they are the same)? Is the inconsistent results due to the threshold settings or what?


发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Kai Blin<mailto:notifications@github.com>
发送时间: 2020年5月29日 23:50
收件人: antismash/antismash<mailto:antismash@noreply.github.com>
抄送: anotherXinzhu<mailto:labxz@hotmail.com>; Author<mailto:author@noreply.github.com>
主题: Re: [antismash/antismash] no module named cStringIO (#267)


Alternatively, you could pip install -U helperlibs to get version 0.2.0 of the helperlibs library, which works correctly with Biopython 1.77.
Let us know if there still is a problem with antiSMASH after upgrading helperlibs or downgrading Biopython.

―

**Comment by grst** [comment]
Has this been fixed? 

I still encounter this issue when installing from Bioconda
```conda install -n antismash antismash```

I can confirm that downgrading Biopython to 1.76 works: 

```conda install -n antismash antismash Biopython=1.76```

Maybe you could update the conda recipe to pin the Biopython version? 

Cheers, 
Gregor
