### ISSUE TITLE
VS compilation problems

### ISSUE THREAD

**Issue by ws234** [antismash/antismash#275]
**Describe the bug**
The system stops at the debugging stage because the compiler does not create .exe solution. The issue was submitted mo VS MS team and the problem was diagnosed as related to the antismash source code.
**Expected behavior**
Creation of an .exe file

**To Reproduce**
Try VS 2019 Community Edition. It will come up by itself.
For interaction issues, also include steps to reproduce the behavior:

**Screenshots**

**System (please complete the following information):**
 - OS: [e.g. iOS, Ubuntu]
 - Browser [e.g. chrome, safari] (if relevant)
MS Win 10 latest Edition 64-bit
**Additional context**

**Comment by SJShaw** [comment]
We apparently never mentioned that we don't support windows, so I'm fixing that now.

If you'd like to get it running on windows, I'd suggest starting by making sure it runs correctly as a normal python script first. Compiling python can lead to extra issues that don't appear when running as a script or at compile time.

You can also try using Docker to run antiSMASH on Windows instead.

**Comment by ws234** [comment]
I have a Linux server running MD simulations and HTS docking. Therefore, a Win2012 server or similar would be preferred.
The last resort would be running it on my laptop (32GB RAM, 4GB VRAM, NVIDIA card, 3D-capable) but I use it for regular work.
When would you have a Windows-ready version?

**Comment by SJShaw** [comment]
As I said, we don't support windows and we have no plans to do so.

If you or someone else would like to contribute some patches with minimal side effects, we'll definitely consider them.

**Comment by ws234** [comment]
I will try Docker. It would have to be done by IT guys as a common server.
