### ISSUE TITLE
FutureWarning: Possible nested set at position 329   ''', re.VERBOSE | re.MULTILINE)

### ISSUE THREAD

**Issue by LuDeChen** [antismash/antismash#285]
Thank you very much for this cool tools. when I finish install this tools use conda. I tried to run. This commond as :antismash --check-prereqs, but responds error. I don't know why. could you help me?

try$ antismash --check-prereqs

/home/dlu/miniconda3/envs/antismash/lib/python3.7/site-packages/scss/selector.py:54: FutureWarning: Possible nested set at position 329 ''', re.VERBOSE | re.MULTILINE)

debian systerm

Thank you very much!

**Comment by SJShaw** [comment]
This is a warning from one of our dependencies about a change in a future version of python that might cause an issue with that dependency. While it says `FutureWarning` in the message, it's safe to ignore as a user.

`pyScss` and its use of regex that causes the `FutureWarning` seems to still be completely functional, so we're not too worried. 

There's been an [issue](https://github.com/Kronuz/pyScss/issues/376) for the pySCSS library for some time now, hopefully they will update it and the warning will no longer appear for us.

**Comment by SJShaw** [comment]
This has been fixed in the pySCSS dependency, so I'll close this now.
