### ISSUE TITLE
How to extract antimash gbk that is only similar to known (MIBIG regerence) compounds?

### ISSUE THREAD

**Issue by mza0150** [antismash/antismash#287]
Hi,
I have been struggling to extract the gbk files that are only similar to known compounds for antismash 5, it was easy for antismash 4. Is there a way to run antismash that allow to get the only gbk that are most similar to known SMs or how do I extract the gbk that are similar to known compounds? Thanks in advance for your help.

**Comment by SJShaw** [comment]
There is no automatic system to restrict outputs like this. There also wasn't anything like this in antiSMASH 4 that I remember.

Each region already has a genbank file extracted for it, you can just take the ones that you're interested in either by checking the overview page of the HTML output and seeing which regions have matches above your threshold similarity or parse the JSON and programmatically find matching regions above your threshold.
