### ISSUE TITLE
Problem installing antiSMASH 5.1.2

### ISSUE THREAD

**Issue by aescasinas** [antismash/antismash#297]
The command I ran to install antiSMASH was:

`conda create -n antismash antismash biopython=1.76 python=3.7`

I'm stuck at Executing transaction: / for about 2 hours now. Any ideas?

**Comment by aescasinas** [comment]
3 hour is the charm. Closed

**Comment by kblin** [comment]
Yeah, conda can be really, really slow sometimes. Nothing we can do about this on our end, I'm afraid.
