### ISSUE TITLE
Any chances to obtain MSA files that used to build HMM profiles?

### ISSUE THREAD

**Issue by TaehyungKwon** [antismash/antismash#299]
Dear authors,

In the data folders, I could find HMM profiles for nrps_pks domains or core biosynthesis genes.
Is there any way to get MSA files to generate these profiles?

Thanks,

**Comment by SJShaw** [comment]
For the NRPS/PKS domains, many are sourced externally, you see the sources at https://docs.antismash.secondarymetabolites.org/modules/nrps_pks_domains/

**Comment by TaehyungKwon** [comment]
Thank you.

**Comment by taylorreiter** [comment]
I looked through the documentation to see if there were other such documents for the rest of the HMM profiles in https://github.com/antismash/antismash/tree/master/antismash/detection/hmm_detection/data. Is there documentation for those sources as well? Sorry if I missed it!

**Comment by taylorreiter** [comment]
thank you!!
