### ISSUE TITLE
"list index out of range" error with prodigal + metagenomic data

### ISSUE THREAD

**Issue by drelo** [antismash/antismash#309]
**Describe the bug**

I can't run antismash with my metagenomic dataset. I got this error "list index out of range". I could test my installation running a short example with a .gbk file from GenBank.

**Expected behavior**

I am trying to use antiSMASH in a metagenomic data set using as input metagenomes assembled by SPAdes. 

When I tried using genefindig-tool prodigal I got the error copied below.  
I tried a dummy set (only 7 sequences from one metagenome) with both the .fna and .gff files obtained with Prokka and I  also got an error.

**To Reproduce**

I tried this with the output of Prokka (skipping the tbl2asn stage)

`nohup antismash ./PROKKA/P1-18/PROKKA_10222020.fna  --cb-knownclusters --genefinding-tool prodigal  -c 10  --output-dir  /mnt/ubi/andres/PLAYAS/TRANSFER/Reads/antiSMASH/SMASH --output-basename XXXX > NOHUP &
`
Here is the output 
```
/mnt/ubi/andres/miniconda3/envs/smash/lib/python3.7/site-packages/scss/selector.py:54: FutureWarning: Possible nested set at position 329
  ''', re.VERBOSE | re.MULTILINE)
WARNING  23/10 12:30:30   Fasta header too long: renamed "gnl|G|P1-18_10000" to "c10000_gnl|G|P.."
```

[long series of lines like this WARNING...]

```
WARNING  23/10 12:30:40   Fasta header too long: renamed "gnl|G|P1-18_36859" to "c36859_gnl|G|P.."
Traceback (most recent call last):
  File "/mnt/ubi/andres/miniconda3/envs/smash/bin/antismash", line 8, in <module>
    sys.exit(entrypoint())
  File "/mnt/ubi/andres/miniconda3/envs/smash/lib/python3.7/site-packages/antismash/__main__.py", line 129, in entrypoint
    sys.exit(main(sys.argv[1:]))
  File "/mnt/ubi/andres/miniconda3/envs/smash/lib/python3.7/site-packages/antismash/__main__.py", line 118, in main
    antismash.run_antismash(sequence, options)
  File "/mnt/ubi/andres/miniconda3/envs/smash/lib/python3.7/site-packages/antismash/main.py", line 625, in run_antismash
    result = _run_antismash(sequence_file, options)
  File "/mnt/ubi/andres/miniconda3/envs/smash/lib/python3.7/site-packages/antismash/main.py", line 685, in _run_antismash
    timings = run_detection(record, options, module_results)
  File "/mnt/ubi/andres/miniconda3/envs/smash/lib/python3.7/site-packages/antismash/main.py", line 191, in run_detection
    run_module(record, cast(AntismashModule, module), options, module_results, timings)
  File "/mnt/ubi/andres/miniconda3/envs/smash/lib/python3.7/site-packages/antismash/main.py", line 237, in run_module
    results = module.run_on_record(record, results, options)
  File "/mnt/ubi/andres/miniconda3/envs/smash/lib/python3.7/site-packages/antismash/detection/genefunctions/__init__.py", line 131, in run_on_record
    for result in run_tools(record, options):
  File "/mnt/ubi/andres/miniconda3/envs/smash/lib/python3.7/site-packages/antismash/detection/genefunctions/tools.py", line 33, in run_tools
    return [func(record.id, cds_features, options) for func in functions]
  File "/mnt/ubi/andres/miniconda3/envs/smash/lib/python3.7/site-packages/antismash/detection/genefunctions/tools.py", line 33, in <listcomp>
    return [func(record.id, cds_features, options) for func in functions]
  File "/mnt/ubi/andres/miniconda3/envs/smash/lib/python3.7/site-packages/antismash/detection/genefunctions/tools.py", line 57, in find_resistance
    hits = scan_for_functions(cds_features, hmm_file, hmmscan_opts=["--cut_ga"])
  File "/mnt/ubi/andres/miniconda3/envs/smash/lib/python3.7/site-packages/antismash/detection/genefunctions/core.py", line 83, in scan_for_functions
    hmm_lengths = utils.get_hmm_lengths(database)
  File "/mnt/ubi/andres/miniconda3/envs/smash/lib/python3.7/site-packages/antismash/common/utils.py", line 131, in get_hmm_lengths
    namepart = hmm.split("NAME  ")[1]
IndexError: list index out of range
```

I also tried using the .gff from Prokka. Using `--genefinding-tool none ` also throws the same error.
A dummy example with a .gbk works and saves everything into the folder 'SMASH'
 

**System (please complete the following information):**
 - OS: CentOS
 - Browser [e.g. chrome, safari] (if relevant)

**Additional context**

Please find attached a shortened version of the file I am trying to use. 

[short.fna.txt](https://github.com/antismash/antismash/files/5430744/short.fna.txt)

**Comment by SJShaw** [comment]
The issue is the ResFam database, it looks like the profiles aren't complete or are otherwise corrupted for some reason. The only thing that's changed in the last 5 years is that they've used HMMer 3.2.1 instead of 3.1b2 to package the profiles. The `NAME` fields are unchanged. That means the version you fetched and the version everyone else has should be the same unless something's gone wrong with the file itself.

The md5 hash of the version I just fetched is `a838bea272e71adbfb2843b8054fcc74`, if yours is different, then delete the `data/resfam` directory and rerun the download script.

**Comment by drelo** [comment]
Just a comment, I solved this issue reported above just downloading again de databases without pointing to a custom local directory, otherwise it seems I got errors. I waited to gain access to more processors in the cluster so I can diagnose this in a better way but now it is fully occupied. But the good news is antiSMASH seems to be working fine after this workaround. Thanks. 

Below is the 'error' while trying to download to a local path. 

"It seems I got this error seems related to this former issue https://github.com/antismash/antismash/issues/308

I installed antiSMASH as detailed before, I created a new environment following those instructions, for some reason diamond doesn't work so I downgraded to 0.9.14, only after doing that I could run download databases."

```
(SMASH) [andrespara@nagual Metabolites]$  download-antismash-daatabases --database-dir ./data
/mnt/ubi/andres/miniconda3/envs/SMASH/lib/python3.7/site-packages/scss/selector.py:54: FutureWarning: Possible nested set at position 329
  ''', re.VERBOSE | re.MULTILINE)
Creating checksum of Pfam-A.hmm
PFAM file present and ok for version 27.0
Creating checksum of Pfam-A.hmm
PFAM file present and ok for version 32.0
Downloading Resfam database
Downloading Resfams.hmm.gz: 100.00% downloaded.
Creating checksum of Resfams.hmm.gz
Extraction of Resfams.hmm.gz finished successfully.
Ensuring all cutoffs are present
Creating checksum of proteins.fasta
ClusterBlast fasta file present and checked
Pre-building all databases...
Error encountered while preparing module data: [Errno 2] No such file or directory: '/mnt/ubi/andres/miniconda3/envs/SMASH/lib/python3.7/site-packages/antismash/databases/clusterblast/proteins.fasta'

```
