### ISSUE TITLE
# How to cancel automatic database download

### ISSUE THREAD

**Issue by yexianingyue** [antismash/antismash#322]
**Is your feature request related to a problem? Please describe.**
It is slow use conda install antismash, because it will download database automatically.

**Describe the solution you'd like**
I hope you can write a script to parse the database downloaded.

**Describe alternatives you've considered**
I modify the script  `download_databases.py` .
**PFAM.._URL**
__PFAM..ARCHIVE_CHECKSUM__
__PFAM..CHECKSUM__

But it is graceless

**Comment by kblin** [comment]
Running the database download automatically on install is a decision the bioconda packagers made when building the bioconda package. From an antiSMASH perspective, as long as the databases are present before running, everything will work, no matter where they came from.

If you want to propose a change to the bioconda package behaviour, please raise that in the bioconda repository.
