### ISSUE TITLE
About clusterblast_20190415

### ISSUE THREAD

**Issue by yexianingyue** [antismash/antismash#323]
**Describe the bug**
I download the database __[clusterblast_20201113.tar.xz](https://dl.secondarymetabolites.org/releases/clusterblast/clusterblast_20201113.tar.xz)__, but it is not work.

**Find**
I download the [clusterblast_20190415.tar.xz](https://dl.secondarymetabolites.org/releases/clusterblast/clusterblast_20190415.tar.xz)  it's work.
 Their third column are different see below:

**Format of clusterblast_20190415**
```
NC_000914	Sinorhizobium...	c6	terpene	NGR_a00360;NGR76.1;...
NC_000914	Sinorhizobium...	c7	siderophore	NGR_a0071008904...
NC_000914	Sinorhizobium...	c9	hserlactone	NGR_a04100C_000...
NC_000918	Aquifex aeolicus...	c2	bacteriocin	aq_1752...
NC_001263	Deinococcus...	c1	terpene	DR_0791...
NC_001263	Deinococcus...	c2	terpene	DR_0853...
NC_001263	Deinococcus...	c3	t3pks	DR_2070...
```

**Format of   clusterblast_20201113**
```
CM000576        Fusarium...   c6019166-6099885        NRPS    FGSG_10997;FGSG_10996;...
CM000576        Fusarium...   c7255232-7302481        NRPS    FGSG_11403;FGSG_13969;...
CM000576        Fusarium...   c7456514-7478171        terpene FGSG_11330;FGSG_11329;...
CM000576        Fusarium...   c7682802-7694587        siderophore     FGSG_14005...
CM000577        Fusarium...   c49741-70044    terpene FGSG_06441;FGSG_06442;FGSG_064...
CM000577        Fusarium...   c86520-130134   NRPS-like       FGSG_06456;FGSG_06457;...
CM000577        Fusarium...   c260243-300046  NRPS-like       FGSG_06501;FGSG_06502;...
```

**Comment by kblin** [comment]
As an explanation, this is because the database format changed for antiSMASH 5.2 to accomodate the new, more robust cluster linking scheme that was added in the antiSMASH database v3 release.
You can't easily use the antiSMASH 5.2 format for older antiSMASH versions.
