### ISSUE TITLE
antismash-db: many strain names are incorrect

### ISSUE THREAD

**Issue by zreitz** [antismash/antismash#342]
**Describe the bug**
Many strains are incorrectly labeled in the Species column.

_(I wasn't sure where to put this among the antismash-db repositories.)_

**Expected behavior**
Correct strain names. My (strongly disfavored) alternative solution is to remove strain names from the Species column if the link behavior is intended:

The Species column is technically acting true to its name, linking to the _species_-wide genome database page in NCBI. However, since the column lists specific strains, I expect clicking the link to take me to an NCBI page that is strain-specific, i.e. the assembly database.  Linking to the species-wide genome database is not particularly helpful, especially when the species has many strains. (It also doesn't always work, see example below.)

**To Reproduce**
From https://antismash-db.secondarymetabolites.org/:
1. Click "Query"
2. Simple search for "coli thiopeptide": [link](https://antismash-db.secondarymetabolites.org/query.html?q=coli%20thiopeptide)
3. Note the many rows with Species "Escherichia coli ECCWS199"
4. Click the Species column in row 5 to be taken to NCBI, i.e. [here](https://www.ncbi.nlm.nih.gov/genome/?term=NZ_RDDR01000006).
5. The link fails to direct to a genome page.
6. In the top search bar dropdown menu, select "nucleotide" and search
7. Row 5 belongs to strain CMSX59a, not ECCWS199.
6. Problem also occurs in "Download results" csv.

**System (please complete the following information):**
 - OS: Chrome OS
 - Browser: Chrome

**Comment by zdk123** [comment]
I'm not sure how antismashDB maps accessions to taxonomies internally, but that accession is a nucleotide not a genome. i.e.g https://www.ncbi.nlm.nih.gov/nucleotide/?term=NZ_RDDR01000006 gets you to the right place. The strain ID is correct in the assembly stats page (CMSX59a as you say) although the taxid just links to 'E. coli' (taxid 562).

**Comment by SJShaw** [comment]
Much delayed, but version 4 of the database is now live and fixes the NCBI links to point directly at nucleotide entries instead of genomes.

The taxonomy has also been updated, however handling future taxonomy changes within the same release of the database presents some issues with versioning that we haven't worked around yet.
