### ISSUE TITLE
Mibig-mode doesn't run for "unclassified sequences"

### ISSUE THREAD

**Issue by zdk123** [antismash/antismash#347]
**Describe the bug**
the generated output for various mibig clusters is missing. I know this is the expected behavior for plants but unclassified sequences (presumably bacterial metagenomes) are missing as well. These get 404 errors on the mibig db page:
* [BGC0000053](https://mibig.secondarymetabolites.org/repository/BGC0000053/generated/index.html#r1c1)
* [BGC0001068](https://mibig.secondarymetabolites.org/repository/BGC0001068/generated/index.html#r1c1)
* [BGC0001109](https://mibig.secondarymetabolites.org/repository/BGC0001109/generated/index.html#r1c1)
* [BGC0001931](https://mibig.secondarymetabolites.org/repository/BGC0001931/generated/index.html#r1c1)

**Expected behavior**
I presume this is not the expected behavior since the 'unclassified' case is not explicitly handled when checking the taxonomy string:
https://github.com/mibig-secmet/antismash-mibig/blob/mibig/run_mibig.py#L50-L51

In fact line 50:
```py
        elif "Viridiplantae":
            taxon = "plants"
```
will always evaluate to `True`, so 'Unrecognizable taxons'/exit will actually never get logged.

I would issue a PR that explicitly handles the "unclassified sequences" case.  However, I'm not sure if you would rather treat unclassifieds the same as plants (i.e. generate the mibig page but not the antismash output) or as bacteria[which they presumably are]/fungi.

**To Reproduce**
See above links.

**Comment by jorgecnavarrom** [comment]
FWIW, I had written some small script some time ago that tried to separate the gbks per taxon and ended up hard-coding some of these. I think I looked at the GenBank/literature at the time

```python
hardcoded_taxa["BGC0001325"] = "Viridiplantae" # noscapine from opium poppy
hardcoded_taxa["BGC0001109"] = "Bacteria" # 'bacterial symbiont of Paederus fuscipes'
hardcoded_taxa["BGC0001315"] = "Viridiplantae" # cucurbitacin from Cucumis sativus
hardcoded_taxa["BGC0000053"] = "Bacteria" # elaiophylin from streptomycete
hardcoded_taxa["BGC0001931"] = "Bacteria" # carrimycin from Streptomyces spiramyceticus
hardcoded_taxa["BGC0000350"] = "Bacteria" # ET-743 from "marine bacterial symbiont"
hardcoded_taxa["BGC0001974"] = "Algae"
hardcoded_taxa["BGC0000504"] = "Bacteria" # cytolysin from E. faecalis
hardcoded_taxa["BGC0001816"] = "Fungi"
hardcoded_taxa["BGC0001316"] = "Viridiplantae" # linamarin from Lotus japanicus
hardcoded_taxa["BGC0001068"] = "Fungi" # pyripyropene A from Penicillium coprobium
```

**Comment by zdk123** [comment]
Thanks @jorgecnavarrom, I may crib those for a local patch.

**Comment by jorgecnavarrom** [comment]
No prob!
Also, I had a larger list, but I didn't post them because their MIBiG "generated" link works. Here's the rest of them in case they're useful:
```python
hardcoded_taxa["BGC0001109"] = "Bacteria" # 'bacterial symbiont of Paederus fuscipes'
hardcoded_taxa["BGC0000598"] = "Bacteria" # polyehwonamide from Streptomyces sp.
hardcoded_taxa["BGC0001317"] = "Viridiplantae" # lupeol from Lotus japanicus
hardcoded_taxa["BGC0001105"] = "Bacteria" # onnamide A from uncultured bacteria
hardcoded_taxa["BGC0000299"] = "Bacteria" # alterochromide etc. from pseudoalteromonas
hardcoded_taxa["BGC0001108"] = "Bacteria" # pederin from uncultured bacteria
hardcoded_taxa["BGC0000255"] = "Bacteria" # pederin from uncultured bacteria
```

**Comment by kblin** [comment]
I guess the long-term solution is to grab the species from the MIBiG json file, and then do a lookup to NCBI or some other taxonomy source.
The antiSMASH mibig fork is due for a rework anyway, I'll try to keep this on the radar.

**Comment by SJShaw** [comment]
https://github.com/mibig-secmet/mibig-html is the replacement for the MIBiG HTML generation. The unclassified issue was fixed there.
