### ISSUE TITLE
How to load the Predicted BGCs by deepBGC to local antiSMASH 6.0.0.alpha1

### ISSUE THREAD

**Issue by yangziyi1990** [antismash/antismash#349]
Hi，now, we can upload the json file that generated by deepBGC to the website of antiSMASH with version 6.0.0.alpha1. But when I install the local program of antiSMASH 6.0.0.alpha1 on my computer, and how to load the Predicted BGCs by deepBGC to antiSMASH？

Looking forward to your reply. 
Many thanks!

**Comment by SJShaw** [comment]
The latest from the DeepBGC team was [this comment](https://github.com/antismash/antismash/issues/122#issuecomment-501708399). It looks like they may not have merged their changes to update this yet, but they'd be best to ask, either on their repository or as a follow-up comment in #122.

**Comment by yangziyi1990** [comment]
Thanks SJShaw, DeepBGC team has updated the new version of DeepBGC to generate json file which can be uploaded to the antismash website. However, the local program for antismash 6.0.0 does not have an interface for entering JSON files. So,  how do I load the json file generated by deepBGC into the local version of antiSMASH？

**Comment by SJShaw** [comment]
Use `--sideload` and the path to the JSON you're trying to sideload.

**Comment by yangziyi1990** [comment]
Thank you, @SJShaw. It works! Maybe you can add this additional options "--sideload" to the README.md file~

**Comment by SJShaw** [comment]
There are many command line options, the most common are included when using `--help` as is standard for command line tools. Advanced options such as sideload are shown when using `--help-showall` (this is mentioned in the output of `--help`).
