### ISSUE TITLE
only one sequence file should be provided

### ISSUE THREAD

**Issue by cmcflrc** [antismash/antismash#352]
Hi,

My sequence file is not being recognized by antismash 5.1.0. I initially input a genome containing 2 contigs, then input a fasta file containing 1 contig. Same problem is being reported. I followed the format:

antismash --taxon bacteria <input.fasta>

**Comment by SJShaw** [comment]
Does your input filename contain spaces and are you escaping them correctly when providing it as a command line argument?

**Comment by cmcflrc** [comment]
Hi SJShaw! Thanks for your response. I was using a wrapping tool for the dockerfile and I made a mistake on the command line arguments. :)
