### ISSUE TITLE
antiSMASH 6 beta features - release info missing???

### ISSUE THREAD

**Issue by vcastroagudin** [antismash/antismash#353]
Hello,

I am having some problems in the compatibility between AntiSMASH output and downstream annotation software.
What is the difference between AntiSMASH v 5.0.0 and the new one, v 6.0.0? What are the features/advantages/new info when selecting "antiSMASH 6 beta features" in the website UI to be included in the analyses?

What are the features in "antiSMASH 6 beta features"?

Thanks in advance.

Vanina

**Comment by kblin** [comment]
Hi there,

antiSMASH 6 features are described in [our recent paper on antiSMASH 6](https://doi.org/10.1093/nar/gkab335). Hope this helps.
