### ISSUE TITLE
No results found on input.

### ISSUE THREAD

**Issue by Leejquan** [antismash/antismash#356]
Hello,
  I ran the command as follow:
> antismash  --taxon bacteria  --genefinding-tool prodigal-m \
> --cb-knownclusters  --cb-general --cb-knownclusters --asf --pfam2go \
> --cpus 16   5801.2.fa
  It finished at two minutes later without any errors. But There were not any results such as  knownclusterblastoutput.txt, subclusterblastoutput.txt etc.  And I open the index.html, finding that there were no results found on input.

  The 5801.2.fa genome was annotated as Mycoplasma hyopneumoniae. So I downloaded the represent genome of Mycoplasma hyopneumoniae called GCF_000400855.1 in NCBI RefSeq database. Then I uploaded  GCF_000400855.1 genome  in antismash annotation online: https://antismash.secondarymetabolites.org/#!/start .
I sellected all the fetures by choosed the "all on". However,   web page displayed that  
no results found on input.

I have no idea about that why doesn't antiSMASH detect my gene cluster.

Thanks

**Comment by SJShaw** [comment]
If there's no results, it means nothing was detected according to the existing cluster definition rules.

What cluster type were you expecting to find in this input and does it normally get detected by antiSMASH?

**Comment by Leejquan** [comment]
Thanks for  your timely reply!
I expected to find any gene clusters possibly annotated in BGCs type. And  it nomally get detected by antiSAMSH.  However, when I ran the same command locally in other genome, there were results detected such as  knownclusterblastoutput.txt, subclusterblastoutput.txt etc. But I didnot find any description detail of it in antiSMASH Documentation or antiSMASH 5 USER MANUAL. I  am looking for your help!

**Comment by SJShaw** [comment]
`knownclusterblast.txt` and `subclusterblast.txt` are legacy outputs from older versions of antiSMASH. They will not exist if there are no clusters detected, as they are analysis modules that run on regions, not the full genome. If you'd like to run them on an arbitrary section of the genome, you'll need to specify the region via one of the sideloading options (`--sideload` or `--sideload-simple`).

The genome you've used is only 900kb, so it's likely that the majority of it is primary metabolism and not secondary, which is what antiSMASH is intended to find. If you'd had a specific cluster type you were expecting, we could look at why that cluster type wasn't being detected and, if necessary, correct it

Unless antiSMASH is missing a reasonably well described secondary metabolite within the genome., I'd trust that the rules are functioning as desired for known secondary metabolites and that this is not an err.
