### ISSUE TITLE
Add "--allow-long-headers" to web version of antismash 

### ISSUE THREAD

**Issue by kcamnairb** [antismash/antismash#359]
Would it be possible to add the "--allow-long-headers" to the web version of antismash as an additional option? This would be very useful.

Thanks,
Brian

**Comment by kblin** [comment]
I'll look into this for our next dispatcher update. :+1:

**Comment by kblin** [comment]
Allowing long headers is now the default for the upcoming antiSMASH 7, added with 34dd634. The new 18 character NCBI IDs are also supported in the submission form now.

**Comment by SJShaw** [comment]
This is now available via the website, so I'll close this.
