### ISSUE TITLE
Clusterblast between two sets of BGCs

### ISSUE THREAD

**Issue by snayfach** [antismash/antismash#362]
I'd like to be able to run the clusterblast feature independently from the rest of antiSMASH to compare two sets of BGCs (or one BGC vs a BGC database). For example, I have a directory of 100 antiSMASH5 genbank files that I want to compare to another directory of antiSMASH5 files. Is there an easy way to do this? Many thanks and apologies if I overlooked this information in your documentation.

**Comment by snayfach** [comment]
From looking closer at the repo I see that there is a feature like this in antiSMASH v6 (issue #325). I've already identified my BGCs of interest. Is there a way to compute the similarity for them to a database (e.g. to MIBIG) without re-runing the BGC identification steps implemented when calling antiSMASH? I'm interested in a standalone tool for cluster comparison that skips de novo prediction of BGCs.

**Comment by SJShaw** [comment]
The new clustercompare module that's been added ready for antiSMASH 6 is set up to make it very easy to add custom databases, so it would be my first suggestion. For best results, use the same version of antiSMASH for the detection steps in both the genomes to build a database from and the genomes you're searching with.

Once you've added your database, you can skip having to redo everything but the new comparison by use `--reuse` on the JSON output for an existing result. Adding the `--cc-custom` argument with your custom database (or any other extra analysis) will run only analysis modules that haven't been run previously for that result. You cannot change detection results this way.

If you specifically want clusterblast, the scripts for generating the clusterblast databases are at https://github.com/antismash/generate-databases. You can probably adjust them to your inputs without much trouble, then replace the clusterblast database in your install with the newly generated ones. This will generate broken links and such, so it's not great.

**Comment by snayfach** [comment]
I don't see the --cc-custom or --reuse option with antiSMASH 6.0.0alpha1 (cloned a few days ago). Am I using the right version? Is there documentation for how to build the custom database?

All my BGCs were identified using antiSMASH5 and I want to compare vs MIBIG. I only have .gbk files for both. Will these be issues?

**Comment by snayfach** [comment]
Update: using the full help text option, I now see the --reuse-results and --cc-custom-dbs options. 

For the  --cc-custom-dbs options it says "A comma separated list of database config files to run with".  How do I generate a database config file for a directory of BGCs?

Also for the --cc-mibig option, which version of MIBiG is being used?

Sorry for all the questions and thanks for your responses!

**Comment by snayfach** [comment]
Update:  --reuse-results does not work for a JSON from antiSMASH v5.1.2, which produces the error:

> raise ValueError("Detection results have changed. No results can be reused")

**Comment by SJShaw** [comment]
That's expected. When detection modules change (either their predictions or whole new modules), the analysis modules may not have all the information they expected, which can lead to results being misleading. To avoid that, we blocked results reuse in this situation.

You can do a full rerun with 6, or if you really like, you could copy the clustercompare code from 6 to 5.1 and make some small code changes to get it running. However, it's probably faster to just rerun with 6.

For the custom database config file, reading through the [scheme](https://github.com/antismash/antismash/blob/master/antismash/modules/cluster_compare/data/schema.json) should show you all the options and the [MIBiG config file](https://github.com/antismash/antismash/blob/master/antismash/modules/cluster_compare/data/mibig.json) should give you an idea of a real one.

`--cc-mibig` is currently based on the MIBiG 2.0 release.

**Comment by snayfach** [comment]
Thanks for all the answers!
