### ISSUE TITLE
[Question]: antiSMASH 6 via Bioconda

### ISSUE THREAD

**Issue by tamuanand** [antismash/antismash#368]
Hi antiSMASH team,

Congrats on the latest release and the publication.

A question: Would you know when antiSMASH 6 would be available via Bioconda.

Thanks

**Comment by kblin** [comment]
We're working on building and testing bioconda packages, it'll just take a while. Follow https://github.com/bioconda/bioconda-recipes/pull/28846 for the progress of that.

**Comment by kblin** [comment]
As far as I understand the BioContainers paper, they integrate with BioConda and the antiSMASH 6 container will show up there via BioConda once that part is done.

**Comment by kblin** [comment]
bioconda packages are now available for 6.0.0, I'm expecting the BioContainers page to update soon as well.
