### ISSUE TITLE
MIBIG entry not found

### ISSUE THREAD

**Issue by snayfach** [antismash/antismash#369]
I've run antismash 6 using the --cc-mibig flag. In the MIBiG comparison table it list BGC0002076.1 as the top hit. However when I went to the MIBiG website and entered the id 'BGC0002076.1' in the search bar no entries were returned. Any ideas why that might be the case?

**Comment by jorgecnavarrom** [comment]
I think the Repository section is not up-to-date, but the entry does exist if you type in directly: https://mibig.secondarymetabolites.org/repository/BGC0002076/index.html#r1c1

**Comment by kblin** [comment]
Yes, the Repository page lists the entries that were in the 2.0 release of the MIBiG database. We're planning for a 2.1 release this summer that will include new entries like this one. As Jorge said, the entries themselves are available already, and the direct links from the MIBiG clustercompare output also are pointing to those entries.

**Comment by snayfach** [comment]
Thank you for your responses. This makes sense.

**Comment by tamuanand** [comment]
hi @kblin @jorgecnavarrom @SJShaw 

Would you know when mibig 2.1 would likely be available.

Thanks
