### ISSUE TITLE
'Namespace' object has no attribute 'diamond'

### ISSUE THREAD

**Issue by mmp3** [antismash/antismash#371]
**Describe the bug**

For `antismash-6.0.0`, installed via "full manual install", the `download-antismash-databases` command fails during the  `Pre-building all databases...` step because it cannot find the `diamond` module for Python.

Specifically, the command:

```
$ sudo download-antismash-databases  --database-dir /data1/antismash_db
```

Gives output:

```
Creating checksum of Pfam-A.hmm
PFAM file present and ok for version 32.0
Downloading Resfam database
Downloading Resfams.hmm.gz: 100.00% downloaded.
Creating checksum of Resfams.hmm.gz
Extraction of Resfams.hmm.gz finished successfully.
Ensuring all cutoffs are present
Creating checksum of TIGRFam.hmm
TIGRFam database present and checked
Creating checksum of proteins.fasta
ClusterBlast fasta file present and checked
Creating checksum of proteins.fasta
ClusterCompare mibig FASTA file present and checked
Pre-building all databases...
Error encountered while preparing module data: 'Namespace' object has no attribute 'diamond'
```

The `diamond` executable is readily verified to be installed:

```
$ which diamond
/home/ubuntu/packages/diamond_v2.0.5/diamond
```

and it works:

```
$ diamond --version
diamond version 2.0.5
```

**Expected behavior**
It should not crash.

**To Reproduce**

```
$ sudo download-antismash-databases  --database-dir /data1/antismash_db
```

**System:**
```
$ lsb_release  -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal
```

**Comment by SJShaw** [comment]
There is no diamond module for python. The error you're seeing is a `Namespace` object holding the paths to the binaries as detected on your PATH, and going by the result of your `which diamond`, I suspect that the root user doesn't have that directory in its PATH and there is no diamond available. You can confirm this either way by doing `sudo which diamond` (or `diamond-aligner` for the standard Ubuntu install name from packages).

Running antiSMASH with `--check-prereqs` (with sudo) will provide more information about missing or misconfigured depedencies while running as root, as well as building any relevant files that still need building (assuming the binary dependencies are found).

**Comment by mmp3** [comment]
I see. Thank you for the explanation. I will activate the virtual environment first and try again, so I don't need `sudo`.

**Comment by 897891211** [comment]
Hi, May I ask if your problem has been resolved?  I also encountered the same problem, but my antiSMASH version is 7.0.0,diamond_v2.0.15

How did it end up being resolved?   Thank you .
