### ISSUE TITLE
How to resolve "ValueError: Protein end coordinate must be contained by the feature"

### ISSUE THREAD

**Issue by tamuanand** [antismash/antismash#377]
Hi

I am trying to run antiSmash 6.0.1 obtained via conda install 

```
antismash -c 20 \
    --genefinding-tool none  \
    --cb-general --cb-knownclusters \
     --cb-subclusters --asf --fullhmmer --pfam2go \
     --smcog-trees \
     --rre --cc-mibig --tigrfam \
     --skip-zip-file  -v -d \
     --logfile genome_abc/logs/genome_abc.log \
     --html-description "genome_abc antiSmash results" \
     --html-start-compact  \
     --allow-long-headers \
     --output-dir genome_abc/results \
     genome_abc.gbk
```

and I end up getting this error in some of my runs  - `ValueError: Protein end coordinate must be contained by the feature`

In the command line above, I am using `--genefinding-tool none`  as I have the gene calls annotated within my input file.

Given below is the traceback info when it errs:
```
Traceback (most recent call last):
  File "<path_to>/antismash_6.0.1/bin/antismash", line 10, in <module>
    sys.exit(entrypoint())
  File "<path_to>/antismash_6.0.1/lib/python3.8/site-packages/antismash/__main__.py", line 129, in entrypoint
    sys.exit(main(sys.argv[1:]))
  File "<path_to>/antismash_6.0.1/lib/python3.8/site-packages/antismash/__main__.py", line 118, in main
    antismash.run_antismash(sequence, options)
  File "<path_to>/antismash_6.0.1/lib/python3.8/site-packages/antismash/main.py", line 630, in run_antismash
    result = _run_antismash(sequence_file, options)
  File "<path_to>/antismash_6.0.1/lib/python3.8/site-packages/antismash/main.py", line 690, in _run_antismash
    timings = run_detection(record, options, module_results)
  File "<path_to>/antismash_6.0.1/lib/python3.8/site-packages/antismash/main.py", line 161, in run_detection
    run_module(record, cast(AntismashModule, module), options, module_results, timings)
  File "<path_to>/antismash_6.0.1/lib/python3.8/site-packages/antismash/main.py", line 241, in run_module
    results = module.run_on_record(record, results, options)
  File "<path_to>/antismash_6.0.1/lib/python3.8/site-packages/antismash/detection/full_hmmer/__init__.py", line 105, in run_on_record
    return hmmer.run_hmmer(record, record.get_cds_features(), MAX_EVALUE, MIN_SCORE, database, "fullhmmer")
  File "<path_to>/antismash_6.0.1/lib/python3.8/site-packages/antismash/common/hmmer.py", line 270,
 in run_hmmer
    hits = build_hits(record, hmmscan_results, min_score, max_evalue, database)
  File "<path_to>/antismash_6.0.1/lib/python3.8/site-packages/antismash/common/hmmer.py", line 157,
 in build_hits 
    location = feature.get_sub_location_from_protein_coordinates(hsp.query_start, hsp.query_end)
  File "<path_to>/antismash_6.0.1/lib/python3.8/site-packages/antismash/common/secmet/features/feature.py", line 123, in get_sub_location_from_protein_coordinates
    raise ValueError("Protein end coordinate must be contained by the feature")
ValueError: Protein end coordinate must be contained by the feature
```

How do I figure out where things could be going wrong?

Interestingly enough, when I use `--genefinding-tool prodigal` on the same genome, the program runs fine - In this case, I am giving the assembly fasta file and therefore asking antiSMASH to make the gene calls.

Thanks in advance.

**Comment by SJShaw** [comment]
Is this an input you're able (and willing) to share? If so, that might help us work out the exact cause.

If not, you can go to `<path_to>/antismash_6.0.1/lib/python3.8/site-packages/antismash/common/hmmer.py` and add in a line immediately above line 157:
```python
print(feature, hsp.query_start, hsp.query_end)
```
That will tell you the feature that's causing the issue and where hmmscan is reporting a hit within the feature's translation (though there will be many lines in the output from this, only the last one will be the important one).

While the full input would be most useful to us in finding out what's going wrong, that more limited information could still help us work out what might be happening and how to avoid it.

**Comment by tamuanand** [comment]
Hi @SJShaw 

I have made the change to `Line 157 of hmmer.py` as suggested and ran the job - please find attached the partial logfile where this errs out

[as6.0.1_debug_feature_within_coordinate.log.txt](https://github.com/antismash/antismash/files/6919808/as6.0.1_debug_feature_within_coordinate.log.txt)

**Comment by SJShaw** [comment]
The shifting I'm not too worried about. The locations in the Genbank input are 1-indexed and python (and biopython's locations, specifically) are 0-indexed for the start, so it's quite normal that the start coordinate is shifted by 1. To account for the `codon_start` qualifier and the negative strand, the end coordinate (normally 1-indexed, consistent with intervals in python to be `inclusive:exclusive`) is also shifted by 1.

The end of the hit should also be 1 indexed, so with a length of 90 aminos, 91 should be right up to the last one. It might be as simple as an off-by-one error that only shows up as an error when the hit is perfectly at the end of the query sequence. It feels a bit strange that this is the first time we've hit it in the year or more that the relevant code has existed, so I'll do some experimenting just to be sure.

**Comment by tamuanand** [comment]
Hi @SJShaw 

I was wondering if you have had a chance to look at this

Thanks

**Comment by SJShaw** [comment]
I've found a bug where `antismash.common.hmmer` was interpreting the hits given by biopython's `SearchIO` as using 1-index end coordinates, but apparently they're 0-indexed. This was truncating the translations of the domains by 1 amino and causing the DNA positions to be off by 3.

This is the opposite of the problem I wanted to solve with your input, which had the translation being 1 too long for the feature ranslation and now it will be longer still. I'm still digging into it, since this is definitely an issue, but I want to be very certain of what's going on because there could be quite a few follow-on issues if I make a mistake (or another one, I suppose) somewhere with these.

**Comment by SJShaw** [comment]
The issue looks to be features without translations that also have frameshifts via `codon_start` qualifiers. If you tweak that feature by subtracting 1 from the end location and changing `codon_start` to 1 instead of 2, that should prove whether it's the right cause of the problem. E.g.
```
     CDS             complement(7206646..7206917)
                     /codon_start=1
                     ...
```
I have a fix ready for issues like this, but before I prematurely celebrate, it would be nice to double check that it solves your problem in particular.

**Comment by tamuanand** [comment]
Hi @SJShaw 

By following what you suggested and hand-editing the genbank file, the program ran fine and did not have any issues.

I would look forward to the patch from your end and install the same via bioconda whenever it is available. 

I am also assuming that you would have taken care of this below in the process
>I've found a bug where antismash.common.hmmer was interpreting the hits given by biopython's SearchIO as using 1-index end coordinates

Thanks a lot

**Comment by SJShaw** [comment]
I was fooled by HMMer for that 1-index issue, so that didn't end up being a bug after all. My test case just happened to shrink after rescanning.

Once the pull request above is merged, you can copy those files into your existing install or wait for the next release (I don't have a timeframe on that).

**Comment by tamuanand** [comment]
Thanks @SJShaw 

Which specific files do I need to my install after the PR is merged?

**Comment by SJShaw** [comment]
The files are listed in the pull request: https://github.com/antismash/antismash/pull/380/files

`antismash/common/secmet/locations.py`
`antismash/common/secmet/features/feature.py`
`antismash/common/secmet/features/cds_feature.py`
