### ISSUE TITLE
BGC functional annotation

### ISSUE THREAD

**Issue by snayfach** [antismash/antismash#378]
I've run antiSMASH v6 on a large number of human gut metagenomic assemblies. Based on the cluster comparison tool, only a very small % of BGCs show any similarity to an entry from the MiBIG v2.0 database. Do you have any suggestions for how I might be able to get a more specific functional annotation for my BGCs, outside of the product type reported by antiSMASH? Thank you.

**Comment by SJShaw** [comment]
Metagenomic assemblies will typically result in many contigs per genome, which tend to make comparisons much less useful, as the clusters will fragment. If you can get good quality assemblies of each included genome that might help.

It's also quite possible that typical gut bacteria won't have any (or very many) good matches to clusters within the MIBiG database.

**Comment by snayfach** [comment]
Do you know of any other databases of functionally characterized BGCs? Or any other tools for functional prediction of BGCs?
