### ISSUE TITLE
download_databases.py

### ISSUE THREAD

**Issue by zhangchenchen870529** [antismash/antismash#379]
when I run "download_databases.py",  the error is :

Creating checksum of Pfam-A.hmm
PFAM file present and ok for version 32.0
Resfams database present and checked
Creating checksum of TIGRFam.hmm
TIGRFam database present and checked
Creating checksum of proteins.fasta
ClusterBlast fasta file present and checked
Creating checksum of proteins.fasta
ClusterCompare mibig FASTA file present and checked
Pre-building all databases...
Error encountered while preparing module data: Syntax error: Found '#810e15' but expected one of ADD, ALPHA_FUNCTION, BANG_IMPORTANT, BAREWORD, COLOR, DOUBLE_QUOTE, FNCT, IF_FUNCTION, INTERP_START, LITERAL_FUNCTION, LPAR, NOT, NUM, SIGN, SINGLE_QUOTE, URL_FUNCTION, VAR

I don't know what's wrong ? what should I do ?

**Comment by SJShaw** [comment]
That's an error message from `pyScss` trying to prepare the CSS for antiSMASH's HTML output module.

At least one of `antismash/outputs/html/css/bacteria.scss`, `antismash/outputs/html/css/plants.scss`, and/or `antismash/outputs/html/css/style.scss` is corrupted in your install.
