### ISSUE TITLE
Inconsistent exon ordering for features - pgap genbank file

### ISSUE THREAD

**Issue by d-yarmosh** [antismash/antismash#384]
I've run PGAP locally on a genome and am trying to use Antismash5.1.1 to add further details. The command is 
`antismash --taxon bacteria --output-dir . -v -d  annot.gbk`

And I am getting "25dc5d5b8a5d4a29_3: inconsistent exon ordering for features" back immediately.

I have attached annot.txt (annot.gbk) for your review. It notably has a section for genes and CDS, which might be the issue?
[annot.txt](https://github.com/antismash/antismash/files/7156656/annot.txt)

**Comment by SJShaw** [comment]
Your contig named `25dc5d5b8a5d4a29_3` has two CDS overlapping features crossing the origin. Circular genomes aren't' truly supported in antiSMASH at the moment, but it allows for a single cross-origin CDS that it then splits it into two features. More than one CDS feature and it assumes that the input is wrong, as we've seen in some annotation pipelines that are very inconsistent about coordinate ordering in their Genbank files.

Until antiSMASH fully supports circular genomes (which I've no timeline on at all, as it gets quite complicated in the implementation details), you're probably best served by rotating your genome so you don't have multiple CDS features overlapping the origin (preferably to dnaA, even for the first two contigs, as that is less likely to split a cluster into parts and lose the detection).

**Comment by d-yarmosh** [comment]
Thanks. I'm resetting the start position and attempting to rerun, but meeting the same error. Used circlator fixstart to adjust the positioning and reannotated with PGAP. I'll let you know if I can find any more detail

**Comment by d-yarmosh** [comment]
Multiple runs of circlator prior to PGAP resolved this.
