### ISSUE TITLE
Fungal BGC detection based on Prodigal meta mode

### ISSUE THREAD

**Issue by mhyleung** [antismash/antismash#408]
Dear all

I ran fungiSMASH with the option `--taxon fungi` enabled, however, the run indicated the following:

```
Fungi taxon must use glimmerhmm for genefinding if using genefinding
```

Why is it that fungiSMASH cannot use prodigal (meta) mode for gene-finding?  Thank you!

Marc

**Comment by SJShaw** [comment]
That's been the case for quite a long time, it's my understanding that `glimmerhmm` outperforms `prodigal` for fungal inputs in general. If that's changed and there's some statistics published somewhere about this, I think we'd consider changing it.

Either way, you can run your genefinding of choice and then supply it to antSMASH.
