### ISSUE TITLE
Error while donwloading antismash database for antismash 6.0.0

### ISSUE THREAD

**Issue by mars188** [antismash/antismash#409]
Hello, 

I installed the latest antismash version 6.0.0 successfully. But when I tried to install its databases as below:

`pip install ./antismash-6.0.0 download-antismash-databases`

I get the following error:

`ERROR: Could not find a version that satisfies the requirement download-antismash-databases (from versions: none)`
`ERROR: No matching distribution found for download-antismash-databases`

Any help will be appreciated.

**Comment by SJShaw** [comment]
`download-antismash-databases` is not a pip package, it's a script that comes with the `antismash` package.
You just need to run it after you've installed antiSMASH.
