### ISSUE TITLE
Air-gapped conda installation failing on DB install

### ISSUE THREAD

**Issue by standage** [antismash/antismash#425]
I'm attempting to install antismash 6.0.1 on an airgapped HPC system that has a local mirror of conda/conda-forge/bioconda. The software installation seems to complete without any complications, but the post-link hook is failing due to network connectivity errors. It looks like the `download-antismash-databases` command is intended to recognize local copies of the database files, so I downloaded the files and copied them to my current directory. But the `download-antismash-databases` command doesn't seem to recognize the local copies. Do I need to place the files in a particular location?

Related to but distinct from #416.

**Comment by SJShaw** [comment]
The default directory is inside the antiSMASH install directory, named `databases`. If you want to point at a different path, use `--database-dir` (this will also be required with `antismash` if you want to keep that separate location).

**Comment by standage** [comment]
Thanks for your response. Since the antismash install directory doesn't exist prior to conda installation, it looks like there's no other way to take advantage of the "don't attempt to download the file if it already exists" feature except to use the `--database-dir` flag?

**Comment by kblin** [comment]
There should now be a bioconda package called `antismash-light` that doesn't attempt to grab the antiSMASH databases during the installation, as per a discussion in #418, thanks to @jasmezz. This will give you more control over the database files during installation.

**Comment by jasmezz** [comment]
Yes, the bioconda package is called `antismash-lite` and does not download the databases upon installation. Thus, running either `download-antismash-databases` afterwards or providing your custom database directory with the `--database-dir` flag as mentioned above is required.

**Comment by standage** [comment]
This is fantastic! I won't be able to test until tomorrow, but I will report on my progress then. Thanks!

**Comment by standage** [comment]
Took a bit of trial and error to unpack the compressed databases and put them in the expected paths, but I was able to get `download-antismash-databases` to work on local database files with a reasonable amount of effort. Thanks!
