### ISSUE TITLE
Output a machine readable output table

### ISSUE THREAD

**Issue by jolespin** [antismash/antismash#443]
**Is your feature request related to a problem? Please describe.**
I ran antiSMASH on my dataset for the first time and noticed there weren't any tables generated just gbk and html files. 

**Describe the solution you'd like**
A tab-separated values file that has a summary of the run with all of the relevant information and outputs. 

**Describe alternatives you've considered**
Writing a script myself. 

**Additional context**
Are there any accessory scripts that summarize the data or should I do this post hoc after running the analysis?

**Comment by SJShaw** [comment]
TSV/CSV files can't handle hierarchical data, which is why the machine readable output we went with was a JSON file. Since everyone also has different needs, it's best that users create their own.

This has been covered [previously](https://github.com/antismash/antismash/issues/128#issuecomment-480355708), including reasoning and some script examples for reading genbank files. Reading the JSON files is even easier and doesn't need antiSMASH source around.

**Comment by jolespin** [comment]
This makes sense, I will parse the Json file and create a table to index easier. 

Does all of the info in the gen bank files exist in the json?

**Comment by SJShaw** [comment]
> If I'm going the way of the antismash parsers, is there any way to get the original gene id from `record`? I'm using a pretty standard workflow of metaSPAdes + Prodigal and it relabels the gene identifiers. I see `record` has a `.original_id` attribute but it's `NoneType`

For the genbank output, the original record ID is kept in a comment with the antiSMASH version and run date. It should come back in on parse, but perhaps it's missed. Record order isn't changed from your original input, and you can always keep those very long names with `--allow-long-headers` for future runs.

> If I go the JSON file route,  how should I filter?

However you like. It depends on what information you want to get out of the results for the particular summary you're after.

> Am I looking for the records with non-empty lists for `areas`?

It depends on what you want. If a record doesn't have any regions, that could be interesting to you. If you aren't interested in them, then yes, skip them.
 
> Is this the typical output for looking at hits vs. contig?

You can compare the results you're seeing there with the HTML output fairly easily.

You've got a lot of regions at the edge of contigs, but that's normal for very fragmented inputs. Generally you'd want a better assembly. You'll have each region with 1 or more candidate clusters, mostly overlapping, and each of those will have 1 or more protoclusters, again with overlaps. This is why a two dimensional table doesn't really work.

**Comment by jolespin** [comment]
Thank you, all of this is extremely informative.  In the future, I'll make sure to go ahead with the `--allow-long-headers`.  

>You've got a lot of regions at the edge of contigs, but that's normal for very fragmented inputs. 

I see what you mean, a lot of them are either at start=0 or end=length of contig.  Is the concern that these BGCs are truncated? If so, is there any type of score I can use to filter out "low quality" or "low confidence" BGCs? 

Forgive me if some of these questions are obvious or don't have intended meaning.  I'm quite new to BGC analysis/interpretation.

**Comment by SJShaw** [comment]
Yes, if it's on a contig edge, then it's likely that it's missing something. High levels of fragmentation can also cause some protoclusters to be missed entirely.

For good results, antiSMASH needs a good assembly.
