### ISSUE TITLE
Most similar known cluster and top MiBIG comparison hit don't match

### ISSUE THREAD

**Issue by promicrobial** [antismash/antismash#452]
Hi, I'm new to bioinformatics and antiSMASH so I'm sorry if this is glaringly obvious and a bit of a stupid question but what I'm seeing doesn't make any sense to me. I'm using the online antiSMASH 6.1.1 server and the top hit for the most similar known cluster in the overview tab doesn't match the top hit in the MiBIG comparison. 

I had expected these to be the same as the KnownClusterBlast analysis function is supposed to identify the closest match from the MiBIG database.

In the case of Escherichia coli str. K-12 substr. MG1655 (NCBI accession NC_000913.3) the most similar known cluster for region 1.1 is the NRP turnerbactin with 30% similarity. However, in the MiBIG comparision tab in the more detailed overview, the top hit is bacillibactin with 0.34 similarity score (procluster to region) and 0.67 (region to region). Turnerbactin doesn't even appear in the MiBIG analysis. Why are these not the same? If KnownClusterBlast analysis and MiBIG compariosn are using the same database should they not report the same top hit?

I tried having a look at the antiSMASH documentation for a posible explaination but it is based on antiSMASH 5.0 and doesn't go into detail about the MiBIG comparison function. Are there differences in the database versions used, search algoritms and/or reporting methods that result in this differenc, or is it something else?

Thanks in advance for any help!

**Comment by SJShaw** [comment]
These are two different analyses. KnownClusterBlast uses the ClusterBlast analysis module with the MIBiG data. The "MIBiG comparsion" tab is the result of the ClusterCompare analysis module, also using the MIBiG data.

The "Most similar known cluster" is pulled from KnownClusterBlast alone. If/when at some point ClusterCompare fully replaces it, then it will swap over on the main overview as well.

The two analyses do use the same base data set of MIBiG entries, but they use very different parts of the information and calculate results in very different ways. ClusterBlast uses percentage identity with scores modified by synteny and core gene hits. ClusterCompare uses identity, synteny, gene functions, PKS/NRPS modules, and so on.
