### ISSUE TITLE
UnsatisfiableError when installing via conda

### ISSUE THREAD

**Issue by panchyni** [antismash/antismash#456]
**Describe the bug**
I am helping users install AntiSMASH on our university computing cluster, but both 'conda create -n antismash antismash' and 'conda install antismash' within an active environment result in the following error:

```
UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.17=0
  - feature:|@/linux-64::__glibc==2.17=0

Your installed version is: 2.17
```

I though this may be a channel conflict within conda, but I got the same error with  the '-c bioconda' option. 

For the moment, I was able to get AntiSMASH installed by first installing the dependencies ('conda install hmmer2 hmmer diamond fasttree prodigal blast muscle glimmerhmm') then running 'conda install antismash'. However, if possible I would like to resolve the above error so that I can point users to the AntiSMASH documentation for installation via conda and to ensure that AntiSMASH is install correctly.

Any advice you could give would be much appreciated.

**System (please complete the following information):**
Linux dev-intel14 3.10.0-1160.36.2.el7.x86_64 #1 SMP Wed Jul 21 11:57:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by SJShaw** [comment]
There's nothing in antiSMASH that needs a specific version of `glibc` installed. As long as you can install the relevant third party  binaries, that's all antiSMASH needs (and all it checks).

This is an issue for the [bioconda recipe repository](https://github.com/bioconda/bioconda-recipes).
