### ISSUE TITLE
json file "region" features doesn't correspond to the actual regions

### ISSUE THREAD

**Issue by pavlohrab** [antismash/antismash#465]
**Describe the bug**
While parsing json file from antismash results, I found that one of the regions have different location, that the one viewed in the browser and the one that is written to gbk file.
Antismash feature from json file:
![image](https://user-images.githubusercontent.com/38843017/181186160-aafc0ea5-f702-4298-b05c-f325d4752e04.png)
Region from gbk file:
![image](https://user-images.githubusercontent.com/38843017/181186311-7731c74d-6b1e-44e1-a137-3206554cd709.png)
And from web version:
![image](https://user-images.githubusercontent.com/38843017/181186488-6396f306-ce4b-49ff-8a64-dbe2ccb8c09f.png)

**Expected behavior**
Region annotations match each other in different result formats

**To Reproduce**
The bug is cached on  accession # NZ_CM002285.1 , region 6

1.  Annotate NZ_CM002285.1. (I have checked every extra feature, but minimal run should be fine too)
2. Download results as a zip archive
3. Inspect json and gbk files. At least region 6 location and annotation is not the same

**Comment by Marios-Nikolaidis** [comment]
Greetings,
I run the NZ_CM002285.fa file with genefinding-tool prodigal and inspected the regions.js file.
Region 6 has the same start and end with the gbk file. 

Hope the attaching image helps. Also if you want i can email you the results i got to compare

![Screenshot 2022-07-27 18:01:15](https://user-images.githubusercontent.com/85386661/181281619-ecfb03ff-4c9e-4e8e-ae2d-5d0f3ffcad4f.png)

**Comment by SJShaw** [comment]
I can't replicate this using the genbank from NCBI.

The HTML shows `Location: 896,711 - 922,771`, which matches `regions.js`:
```
$ grep -A 3 '"r1c6":' regions.js
 "r1c6": {
  "start": 896711,
  "end": 922771,
  "idx": 6,
```
It matches the genbank output:
```
$ grep -A 3 '  region  ' NZ_CM002285.1.gbk
     region          896711..922771
                     /candidate_cluster_numbers="9"
                     /candidate_cluster_numbers="10"
                     /candidate_cluster_numbers="11"
```

It matches the output JSON object (note: the index and start position here are 0-indexed, which varies from the human readable outputs which are 1-indexed), in both the simple version:
```
$ jq .records[0].areas[5] NZ_CM002285.1.json
{
  "start": 896710,
  "end": 922771,
  "products": [
    "lanthipeptide-class-iii",
    "RiPP-like"
  ],
 ...
```
and the full record feature dump:
```
$ jq .records[0].features[1904] NZ_CM002285.1.json
{
  "location": "[896710:922771]",
  "type": "region",
  ...
```

For all of these options, the candidate cluster numbers and products also match for me. Your JSON object appears to be missing the lanthipeptide protocluster, while the GBK and HTML have the lanthipeptide protocluster. 

I suspect this might be a mix of results from multiple runs. It'll be easy to see if you do something like `ls -l` to see the timestamps of the files in question, they should all be within the same minute or so, generally.
If you're sure it's not a mix of results, we'll need the details of the input (genbank/fasta+gff/fasta+genefinding, etc), and the mismatching outputs themselves to see what's going on (preferably the zip file that antiSMASH generates).

**Comment by SJShaw** [comment]
Closing due to lack of information to work with.
