### ISSUE TITLE
Which gene prediction tool is used for fungal genomes?

### ISSUE THREAD

**Issue by Juliana-Soto24** [antismash/antismash#475]
I am planing to use antismash in fungal genomes and I can see that the options for gene predictions are:
 --genefinding-tool {glimmerhmm,prodigal,prodigal-m,none,error}

which tool is used for fungal genomes?

Thanks, 
Juliana

**Comment by SJShaw** [comment]
`glimmerhmm` is the appropriate gene finder for fungal inputs, just make sure to also use `--taxon fungi`.
