### ISSUE TITLE
ImportError: cannot import name 'Markup' from 'jinja2'

### ISSUE THREAD

**Issue by ShakunthalaNatarajan** [antismash/antismash#476]
I have been trying to download the antismash databases after following initial installation steps. I used the followng command to download the databases:

python3 download_databases.py

But I faced OSE error: Errno 28: No space on disk
To avoid this I created a config folder in my home directory called .antismash6.cfg and wrote in it the path where my databases should exist as follows to avoid space issues:

data /path/to/folder/for databases

Now when I run python3 download_databases.py, the error reads as,

ImportError: cannot import name 'Markup' from 'jinja2'

I tried out the following fixes:

pip install --upgrade jinja2

Then I tried,

pip install flask==2.0.3

I also tried installing a lower version of jnja2 with

pip install jinja2==3.1.1

Then I started python3 and did

from jinja2.utils import markupsafe 
markupsafe.Markup()

Also, I tried
from markupsafe import Markup

But still the import error persists. Can someone please help!

**Comment by SJShaw** [comment]
Can you copy/paste the full stack trace of the error?
Also, which version of antiSMASH are you trying to work with?

**Comment by ShakunthalaNatarajan** [comment]
`(my_antismash) ubuntu@genecracker-36114:/vol/bigdata/miniconda3/envs/my_antismash/antismash-6.0.0/antismash$ python3 download_databases.py
Traceback (most recent call last):
  File "/vol/bigdata/miniconda3/envs/my_antismash/antismash-6.0.0/antismash/download_databases.py", line 17, in <module>
    import antismash
  File "/vol/bigdata/miniconda3/envs/my_antismash/antismash/__init__.py", line 12, in <module>
    from antismash.main import run_antismash, get_detection_modules, \
  File "/vol/bigdata/miniconda3/envs/my_antismash/antismash/main.py", line 35, in <module>
    from antismash.detection import (cassis,
  File "/vol/bigdata/miniconda3/envs/my_antismash/antismash/detection/nrps_pks_domains/__init__.py", line 15, in <module>
    from .domain_drawing import generate_html, generate_js_domains, will_handle
  File "/vol/bigdata/miniconda3/envs/my_antismash/antismash/detection/nrps_pks_domains/domain_drawing.py", line 16, in <module>
    from antismash.common.html_renderer import FileTemplate, HTMLSections
  File "/vol/bigdata/miniconda3/envs/my_antismash/antismash/common/html_renderer.py", line 12, in <module>
    from jinja2 import Markup
**ImportError: cannot import name 'Markup' from 'jinja2' (/vol/bigdata/miniconda3/envs/my_antismash/jinja2/__init__.py)**
`

**Comment by ShakunthalaNatarajan** [comment]
I am trying to use antiSMASH version-6.0.0

**Comment by SJShaw** [comment]
You'll need to install a version of jinja2 older than 3.0.
Alternatively, use antiSMASH 6.0.2 or later, which handles newer version of jinja having removed `Markup`.
