### ISSUE TITLE
download-antismash-databases still tries to modify installation directory when specifying a different database-dir

### ISSUE THREAD

**Issue by 0xaf1f** [antismash/antismash#496]
**Describe the bug**
Installations on NIH's Biowulf cluster are read-only-- in particular, I'm trying to build a singularity container for antismash (with a native interface--to appear as a bare metal installation) and downloading the databases onto a separate filesystem afterwards. Given that `download-antismash-databases` is to be run separately and after installation, it should not try to modify things in the installation folder when specifically requesting the database to be built elsewhere:

```
$ download-antismash-databases --database-dir /fdb/antismash
Downloading PFAM version 34.0
Downloading Pfam-A.hmm.gz: 100.00% downloaded.
Creating checksum of Pfam-A.hmm.gz
Extraction of Pfam-A.hmm.gz finished successfully.
Downloading Resfam database
Downloading Resfams.hmm.gz: 100.00% downloaded.
Creating checksum of Resfams.hmm.gz
Extraction of Resfams.hmm.gz finished successfully.
Ensuring all cutoffs are present
Downloading TIGRFam database
Downloading TIGRFam.hmm.gz: 100.00% downloaded.
Creating checksum of TIGRFam.hmm.gz
Extraction of TIGRFam.hmm.gz finished successfully.
Downloading ClusterBlast database.
Downloading clusterblast_20201113.tar.xz: 100.00% downloaded.
Creating checksum of clusterblast_20201113.tar.xz
Extraction of clusterblast_20201113.tar.xz finished successfully.
Extraction of clusterblast_20201113.tar finished successfully.
Downloading ClusterCompare mibig database.
Downloading cc_mibig_20211216.tar.xz: 100.00% downloaded.
Creating checksum of cc_mibig_20211216.tar.xz
Extraction of cc_mibig_20211216.tar.xz finished successfully.
Extraction of cc_mibig_20211216.tar finished successfully.
Pre-building all databases...
Error encountered while preparing module data: [Errno 30] Read-only file system: '/opt/conda/envs/app/lib/python3.8/site-packages/antismash/detection/hmm_detection/data/bgc_seeds.hmm'
```

**Expected behavior**

I'd expect that `download-antismash-databases` not to write/modify anything in the installation tree if I've specified an independent `--database-dir`.

Many thanks

**Comment by kblin** [comment]
You can do that, provided you make sure to handle all the other data preparation tasks during the installation. `download-antismash-database` runs the data preparation logic mainly to handle building the diamond databases and calling `hmmpress` on the downloaded PFAM, TIGR, and Resfams databases. However, if you didn't run the prepare data step during installation, the same call by `download-antismash-database` will try to also prepare the data that is shipped with the antiSMASH install (hmmer profiles, `scikit.learn` data, etc.), which is exactly what is failing for you.

Having said that, our docker builds have the exact thing you need to be running during the install to be able to prepare all the shipped data, see https://github.com/antismash/antismash/blob/master/Dockerfile#L17

So if you run your install like that, the subsequent `download-antismash-databases` call should no longer try to change anything. Let us know if that doesn't work, because then that would be a bug indeed.

**Comment by 0xaf1f** [comment]
Oh ok, I'll have to give that a shot. I was using `antismash-lite` conda package, but I guess it still does some database setup.

**Comment by 0xaf1f** [comment]
I copied that setup line (`python -c "import antismash; antismash.config.build_config(['--databases', 'mounted_at_runtime'], modules=antismash.get_all_modules()); antismash.main.prepare_module_data()"`) into my definition file and rebuilt the container and tried `download-antismash-databases` again in my external directory, but I still got an error, this time with it trying to modify the lanthipeptides installation subdirectory:


```
Creating checksum of cc_mibig_20211216.tar.xz
Extraction of cc_mibig_20211216.tar.xz finished successfully.
Extraction of cc_mibig_20211216.tar finished successfully.
Pre-building all databases...
Error encountered while preparing module data: [Errno 30] Read-only file system: '/opt/conda/envs/app/lib/python3.8/site-packages/antismash/modules/lanthipeptides/data/lanthipeptide.scaler.pkl'
```

The container is also a bit large (1.5G). I was hoping that the lite installation would allow me to manage all the databases in a separate directory outside of the container.

**Comment by kblin** [comment]
I'm not sure where you're running this line. It needs to be run whenever you're doing the initial antismash install step (`pip install ....` or however you're running it) while the install directories are still writable.

Having said that, I'm really not sure where the actual issue is, because I know this works for our containers, but your setup is a couple of layers removed from what I know. For example, are you trying to convert the biocontainers version of the bioconda antismash-lite package, or are you installing from bioconda within your container? 

What are the exact steps to get to the issue, so I can convince myself this is a bug with antiSMASH and not with e.g. the bioconda reciepe?

**Comment by 0xaf1f** [comment]
> I'm not sure where you're running this line. It needs to be run whenever you're doing the initial antismash install step (pip install .... or however you're running it) while the install directories are still writable.

yes, I ran it as part of the container build process while the installation was still writable. The error is different than what I was getting before.

> are you trying to convert the biocontainers version of the bioconda antismash-lite package, or are you installing from bioconda within your container?

The latter (biocontainers aren't even available for antismash's bioconda packages). I installed the `antismash-lite` conda package since it doesn't run `download-antismash-databases` post-install.

> Having said that, I'm really not sure where the actual issue is, because I know this works for our containers,
The container builds just fine. This just comes up when trying to do the database setup afterwards, which is probably too heavy for you to have automated testing for. I don't have a good docker setup to check whether your containers have the same issue.

> What are the exact steps to get to the issue, so I can convince myself this is a bug with antiSMASH and not with e.g. the bioconda reciepe

My definition file is very simple-- I don't have access to it at the moment, but it's basically:

```
Bootstrap: <a micromamba base image>

%post
micromamba create -y -n app antismash-lite
export PATH=/opt/conda/envs/app/bin:$PATH
python -c "import antismash; antismash.config.build_config(['--databases', 'mounted_at_runtime'], modules=antismash.get_all_modules()); antismash.main.prepare_module_data()"

%environment
export PATH=/opt/conda/envs/app/bin:$PATH
```
Built the container, so say I have `container.sif`. This part works just fine.
Then, to bind mount my writable  `/my-db-dir` into the container at the same path and try to setup the databases, I do something like

```
singularity exec -B /my-db-dir container.sif download-antismash-databases --database-dir /my-db-dir
```

The error is pretty clear that it's still trying to modify the installation directory.

The [bioconda recipe](https://github.com/bioconda/bioconda-recipes/tree/master/recipes/antismash-lite) is very simple and is in fact just running `pip` to do the installation. It also adds something else to`MANIFEST.in` (see https://github.com/bioconda/bioconda-recipes/blob/master/recipes/antismash-lite/build.sh ). Not sure that that matters.


Anyway, the only reason I can see this not being an antismash bug is if the python one-liner quietly errored/failed due to some incompatible dependency and that data preparation step was incomplete. But even so, it shouldn't quietly fail and that itself would be a bug.

**Comment by SJShaw** [comment]
That one-liner doesn't fail silently, here's an example of it in a virtual environment raising the same error you had (though since I'm testing with a file system that's not entirely read-only, only the directory, it's a _slightly_ different message).
```
$ antismash --version
antiSMASH 6.1.1
$ rm -f temp/lib/python3.9/site-packages/antismash/modules/lanthipeptides/data/lanthipeptide.scaler.pkl
$ chmod -R -w temp/lib/python3.9/site-packages/antismash/modules/lanthipeptides/
$ python -c "import antismash; from antismash import main; antismash.config.build_config(['--databases', 'mounted_at_runtime'], modules=antismash.get_all_modules()); main.prepare_module_data()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "temp/lib/python3.9/site-packages/antismash/main.py", line 579, in prepare_module_data
    module.prepare_data()
  File "temp/lib/python3.9/site-packages/antismash/modules/lanthipeptides/__init__.py", line 69, in prepare_data
    pickle_classifier(training_set, prefix="lanthipeptide", kernel='rbf', C=9.77e6, gamma=1.78e-9,
  File "temp/lib/python3.9/site-packages/antismash/common/external/rodeo_svm/rebuild.py", line 36, in pickle_classifier
    save_classifier(training_set, prefix, kernel=kernel, C=C, gamma=gamma)
  File "temp/lib/python3.9/site-packages/antismash/common/external/rodeo_svm/svm_classify.py", line 144, in save_classifier
    joblib.dump(scaler, "%s.scaler.pkl" % save_prefix)
  File "temp/lib/python3.9/site-packages/joblib/numpy_pickle.py", line 481, in dump
    with open(filename, 'wb') as f:
PermissionError: [Errno 13] Permission denied: 'temp/lib/python3.9/site-packages/antismash/modules/lanthipeptides/data/lanthipeptide.scaler.pkl'
```

That one-liner is effectively the exact same line as used in the [download script](https://github.com/antismash/antismash/blob/master/antismash/download_databases.py#L444), the only change being that the config building is necessarily more complex:
```
    try:
        print("Pre-building all databases...")
        antismash.main.prepare_module_data()
        print("done.")
    except Exception as err:  # pylint: disable=broad-except
        print("Error encountered while preparing module data:", str(err), file=sys.stderr)
        sys.exit(1)
```

**Comment by kblin** [comment]
This is an issue with they way you install antiSMASH, not with antiSMASH itself. I see no way in which that python command can fail silently, unless there's something in Singularity that makes it fail that way. Outside of singularity, it'll fail with an error message similar to what Simon posted.

Feel free to re-open this issue if you can provide us with a way to reproduce this issue outside of Singularity. I understand that Singularity is a popular option for people running software in a cluster environent, but we don't have the capacity to support all possible setups.
Having said that, isn't there a way to create a Singularity container from a Dockerfile? I'd feel more comfortable supporting this install path than going via a conda option that we didn't build or support.

**Comment by 0xaf1f** [comment]
I am not saying it failed silently-- you said you weren't convinced that there was a bug and I said either way you look at it there is a bug. Either the config build is not doing everything it's expected to, or it failed silently. Because the result that I am observing is that, after the config build one-liner completes successfully and the container build completes, the later step of download-antismash-databases still tries to write to the now read-only installation tree. And I showed you which part of the installation it's trying to write to, which shows it had progressed more than when I had tried it previously without having running the one-liner at all.

If I'm right, you should be able to observe the same issue with Docker. And I think it's plausible to have been overlooked because the issue only becomes apparent after the build when running `download-antismash-databases`.

> Having said that, isn't there a way to create a Singularity container from a Dockerfile?
There is a way to do it from a Docker image, but we try to avoid using things from DockerHub on our cluster. I'll have to do a scan on it to validate it.

**Comment by kblin** [comment]
Oh, and my bad, I didn't notice that things were now failing elsewhere. Can you try with the current master tree now that f7b1b69 has come in?

**Comment by 0xaf1f** [comment]
I just got around to testing the master branch past https://github.com/antismash/antismash/commit/f7b1b692a39929e661a5f26c1b440b9d98ab50a9 and I see that the problem is resolved and looking forward to the next release.
