### ISSUE TITLE
MIBiG v3.1 ClusterCompare databaes

### ISSUE THREAD

**Issue by snayfach** [antismash/antismash#500]
Could you please update the clustercompare database to MIBiG v3.1? In the current version downloaded by antismash, there are 1952 entries which were updated in 2020 (MIBiG v2 I think). This is compared to the 2502 entries in MIBiG v3. Many thanks.

**Comment by kblin** [comment]
Thanks for the feedback. That's on our todo list for the antiSMASH 7 release that'll come out in beta in a few weeks.

**Comment by kblin** [comment]
Fixed in d29af3ffb, you can already give this a spin at https://dev.antismash.secondarymetabolites.org/
