### ISSUE TITLE
Conda installation without database download

### ISSUE THREAD

**Issue by jolespin** [antismash/antismash#528]
**Is your feature request related to a problem? Please describe.**

I keep running out of memory because I want to install antismash in an environment but it is download/configuring the database which I already have downloaded.  I'm trying to incorporate it in the my https://github.com/jolespin/veba suite but am having issues getting the environment set up. 

**Describe the solution you'd like**

For anaconda to install antismash and then run a separate command if we need a new database such as CheckM or GTDB-Tk. 

**Describe alternatives you've considered**

Allocating a lot of memory and compute time for installation.

**Comment by SJShaw** [comment]
That functionality is already provided by antiSMASH with `download-antismash-databases` and the `--database-dir` option/antiSMASH config file.

The bioconda equivalent also already exists: https://github.com/bioconda/bioconda-recipes/blob/master/recipes/antismash-lite/meta.yaml
If that doesn't behave the way you want, then you'll need to open an issue on that repository.

**Comment by jolespin** [comment]
For reference, here is the error I get when installing: 

```
ERROR conda.core.link:_execute(733): An error occurred while installing package 'bioconda::antismash-6.1.1-pyhdfd78af_0'.
Rolling back transaction: done

LinkError: post-link script failed for package bioconda::antismash-6.1.1-pyhdfd78af_0
location of failed script: /expanse/projects/jcl110/anaconda3/envs/test-VEBA-biosynthetic_env/bin/.antismash-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout:
stderr: /expanse/projects/jcl110/anaconda3/envs/test-VEBA-biosynthetic_env/bin/.antismash-post-link.sh: line 4: 2293712 Killed                  download-antismash-databases

return code: 137

()

```
