### ISSUE TITLE
Sideloaded annotations lost if record names changed/truncated

### ISSUE THREAD

**Issue by Stephen-Harding** [antismash/antismash#559]
Hello,

I am very new to posting issues here, so I apologize for any mistakes. For antiSMASH v6 and v7 beta, I have tested the sideload feature using a JSON file output by DeepBGC (DBGC). I have not been successful at obtaining sideloaded results from an analysis conducted using antiSMASH v6 executed with a command line or web version. However, using the same input GBK and DBGC JSON, I was able to get the additional annotations with v7.

Here is a a snippet of the JSON I am using as input:
![image](https://user-images.githubusercontent.com/121183636/222263946-a7c84442-5a57-4e6f-a7ad-2b5fcb83c0e2.png)

**antiSMASH v6 installed on HPC:**
Here is a template of the code I used to conduct the analysis: 
antismash --taxon fungi --output-dir /PATH/TO/DIR --sideload /PATH/TO/DBGC.json --[Added Arguments] /PATH/TO/INPUT.gbk

**antiSMASH v6.1.1 web version:**
Here is a screenshot of my options from my attempt at using the web based version:
![image](https://user-images.githubusercontent.com/121183636/222267599-d4e85d09-843a-4b5c-be1d-ab8ab6681682.png)

These analyses will run with no apparent errors, but the DBGC results are not incorporated. Here is an example of the output (JOB ID: available by request):
![image](https://user-images.githubusercontent.com/121183636/222264493-dae97b7d-ea44-447d-b9e4-445373ce6d40.png)

**antiSMASH v7.0 beta web:**
Here are screenshots of the results from the sideloaded analysis conducted with v7.0 (JOB ID: available by request):
![image](https://user-images.githubusercontent.com/121183636/222265579-2cf2c598-de94-4c0b-8604-faee167d0c95.png)
![image](https://user-images.githubusercontent.com/121183636/222265727-b21cb42a-a5c2-4a18-88c2-b454877b3158.png)

In attempt to figure out my problem, I have inspected the DBGC JSON file and it appears to be formatted correctly. So, any help would be greatly appreciated. I can provide additional files upon request.

-Stephen

**Comment by SJShaw** [comment]
For antiSMASH 7.0, the default behaviour of handling long record names changed to _not_ renaming long names instead of truncating them. This is the `--allow-long-headers`/`--no-allow-long-headers` argument.

The reason the 6.1 run didn't work is that the record names, having been truncated, no longer matched the identifier in your sideloaded JSON.

We can fix that bug, but in the meantime you can work around it by adding the `--allow-long-headers` argument to your command line.
