### ISSUE TITLE
Which version of MIBiG is used in antiSMASH 6.1.1 ?

### ISSUE THREAD

**Issue by duboism** [antismash/antismash#567]
Hello,

We would like to know what is the version of MIBiG used in antiSMASH 6.1.1 ? Is it possible to retrieve this programmatically ?

**Comment by duboism** [comment]
We took a look at the code in `download_databases.py`. AFAIU, the code downloads the data `https://dl.secondarymetabolites.org/releases/clustercompare/cc_mibig_3.1.tar.xz` but I can't relate that to any "official" [MIBiG releases](https://mibig.secondarymetabolites.org/download).

**Comment by SJShaw** [comment]
`cc_mibig_3.1.tar.xz` is the matching 3.1 release on the website you linked to.
> Version 3.1 (October 7th, 2022)

However 6.1.1 is using a version of MIBiG 2, fetched and built on 2021.12.16 (likely with some minor corrections to get it to build).

**Comment by duboism** [comment]
Sorry I got confused and opened the lasest revision of the file. In version 6.1.1, the URL used to download MIBiG is `https://dl.secondarymetabolites.org/releases/clustercompare/cc_mibig_20211216.tar.x` as you mentionned (it's this one I could not relate to "official" versions). So if I understand what you say, this is a modified version 2.

**Comment by duboism** [comment]
Thanks for you answer.
