### ISSUE TITLE
less restrictive hmmer requirement in bioconda

### ISSUE THREAD

**Issue by alexweisberg** [antismash/antismash#569]
I am trying to incorporate antismash into a conda environment along with several other programs that use Hmmer3.

Currently, the environment wont solve due to a conflict between antismash, which explicitly requires 'hmmer ==3.1b2', and bakta, which requires hmmer >3.2.2. 

Would it be possible to relax the restrictions on hmmer to just a version >3? Thanks!

**Comment by kblin** [comment]
We don't maintain the bioconda recipe of antiSMASH, the bioconda project does. Please file a bug about bioconda packages [there](https://github.com/bioconda/bioconda-recipes/issues).
Having said that, I personally use  hmmer in version 3.3.2 with antiSMASH at the moment with no issues. I'm not sure why there was a hard version pin in the first place.

**Comment by alexweisberg** [comment]
Thank you! I will contact them instead and see if they can loosen the requirement.
