### ISSUE TITLE
Did not recognise the LOCUS line layout

### ISSUE THREAD

**Issue by liaohu1231** [antismash/antismash#575]
**Describe the bug**

**Expected behavior**

**To Reproduce**
For analysis issues, provide an accession number or a record fragment that can reproduce the problem.

For interaction issues, also include steps to reproduce the behavior:

**Screenshots**

**System (please complete the following information):**
 - OS: [e.g. iOS, Ubuntu]
 - Browser [e.g. chrome, safari] (if relevant)

**Additional context**

**Comment by liaohu1231** [comment]
1-1_bin.10/1-1_bin.10.gbk
ERROR    24/03 10:14:32   Parsing '1-1_bin.10/1-1_bin.10.gbk' failed: Did not recognise the LOCUS line layout:
LOCUS       1-1_NODE_212_length_2995329953 bp   DNA    linear       23-MAR-2023

**Comment by liaohu1231** [comment]
Can you tell me how to resolve this bug?

**Comment by SJShaw** [comment]
Separate the name and the length in the locus line with a space, it's confusing biopython, which is what we use to parse genbank files.
