### ISSUE TITLE
Error building diamond database

### ISSUE THREAD

**Issue by saurav1983** [antismash/antismash#587]
Hi, 
I am encountering problem while installing antismash database, 
i used download -antismash -databases

Got the following error at last....
Pre-building all databases...
Error encountered while preparing module data: diamond failed to run: makedb ->

**Comment by matinnuhamunada** [comment]
Seems like its a diamond issue: https://github.com/bbuchfink/diamond/issues/698
While waiting for the fix, maybe pinning diamond to previous version (2.0.0) might works?

**Comment by SJShaw** [comment]
What version of diamond were you running in order to get this error?

**Comment by SJShaw** [comment]
As mentioned above, diamond 2.1.0 and later have problems in diamond itself, and we'd rather not try to work around bugs in specific versions of external dependencies. We've tested with 0.8.36, 0.9.17, 0.9.24, 2.0.7, 2.0.9, and 2.0, so if you can install one of those versions, then we can rule out diamond bugs and can try to see what other issues your particular setup might have.

**Comment by saurav1983** [comment]
Hi, 
i pinned down the diamond to 2.0.15, but still the same error came

(antismash) kumars@kumars-VirtualBox:~$ download-antismash-databases
Downloading PFAM version 34.0
Downloading Pfam-A.hmm.gz: 100.00% downloaded.
Creating checksum of Pfam-A.hmm.gz
Extraction of Pfam-A.hmm.gz finished successfully.
Downloading Resfam database
Downloading Resfams.hmm.gz: 100.00% downloaded.
Creating checksum of Resfams.hmm.gz
Extraction of Resfams.hmm.gz finished successfully.
Ensuring all cutoffs are present
Downloading TIGRFam database
Downloading TIGRFam.hmm.gz: 100.00% downloaded.
Creating checksum of TIGRFam.hmm.gz
Extraction of TIGRFam.hmm.gz finished successfully.
Downloading ClusterBlast database.
Downloading clusterblast_20201113.tar.xz: 100.00% downloaded.
Creating checksum of clusterblast_20201113.tar.xz
Extraction of clusterblast_20201113.tar.xz finished successfully.
Extraction of clusterblast_20201113.tar finished successfully.
Downloading ClusterCompare mibig database.
Downloading cc_mibig_20211216.tar.xz: 100.00% downloaded.
Creating checksum of cc_mibig_20211216.tar.xz
Extraction of cc_mibig_20211216.tar.xz finished successfully.
Extraction of cc_mibig_20211216.tar finished successfully.
Pre-building all databases...
Error encountered while preparing module data: diamond failed to run: makedb -> 
(antismash) kumars@kumars-VirtualBox:~$ diamond version
diamond version 2.0.15

Thank You,

**Comment by SJShaw** [comment]
If you run `antismash -d --check-prereqs` and post the output, we might be able to see which particular database it's objecting to.

**Comment by SJShaw** [comment]
There's something very wrong in your environment. The above is showing that even `diamond version` isn't working as expected.

If `diamond version` on the command line still gives you a result as per your earlier comment, then try forcing that particular path to skip whatever might be going on with conda:
```
antismash --check -d --executable-paths diamond=$(which diamond)
```

If that still fails, you should probably try without conda. If your virtual machine is using either Ubuntu or Debian, then it's fairly easy to skip conda altogether.

**Comment by saurav1983** [comment]
installed without conda...

Thank You,
