### ISSUE TITLE
Wrong docker script on secondarymetabolites.org

### ISSUE THREAD

**Issue by JWDebler** [antismash/antismash#597]
Hi, 
I'm not sure if this is the correct place to report this, but the docker scripts for 'full' and 'lite' on [https://docs.antismash.secondarymetabolites.org/install/](https://docs.antismash.secondarymetabolites.org/install/) are currently the same (both install the lite version).

The problem is in this script: [docker-run_antismash-full](https://dl.secondarymetabolites.org/releases/latest/docker-run_antismash-full)

Line 34 needs to be changed from:

`antismash/standalone-lite:7.0.0`

to

`antismash/standalone:7.0.0`

Cheers

**Comment by kblin** [comment]
I'm also not sure if this is the right place to report it, but it certainly works. Thanks for the heads up.

I must have copied the standalone-lite script twice, I've now put the right script in. There's some other changes on the `-full` script on top of the different docker image, so if you're planning on using that I'd suggest you fetch it from the server again.

**Comment by kblin** [comment]
Oh, and of course the issue is fixed. That's what I get for handling github issues pre-coffee.
