### ISSUE TITLE
Security Issue Report

### ISSUE THREAD

**Issue by AdnaneKhan** [antismash/antismash#613]
I've found a _likely_ security issue that would allow unauthorized parties to modify this repository's code - is there a way I can privately report this?

**Comment by SJShaw** [comment]
The most reliable way that we have right now for a private report would be to open a ticket via https://antismash.secondarymetabolites.org/#!/contact

**Comment by SJShaw** [comment]
I'm closing this as it has now been handled.

Private security issue reporting has also been enabled for the repository for future issues.
