### ISSUE TITLE
Will the meme module fail to install and affect the subsequent use?

### ISSUE THREAD

**Issue by zhaohanshuang** [antismash/antismash#618]
Here is the error message I reported using the command: antismash --prepare-data.
(antismash-7)[mcs@mcs1 antismash-7]$ antismash --prepare-data
ERROR    22/06 10:03:53   antismash.detection.cassis: preqrequisite failure: Failed to locate executable for 'meme'
ERROR    22/06 10:03:53   antismash.detection.cassis: preqrequisite failure: Failed to locate executable for 'fimo'
Some module prerequisites not satisfied

The dependencies you provided in the software installation steps include: meme (version 4.11.2 required for meme specifically, which is only used in the cassis module, fimo tested with 5.5.2), but it doesn't install, how do I fix this? How do I fix this? Thank you for your help!

**Comment by SJShaw** [comment]
Follow the link to meme given in the text you quoted from our installation instructions. It takes you to the available releases and install instructions for the meme software.

For the rest of your question, if meme is not installed you cannot use the cassis module as the instructions also mentioned. Not having fimo (also part of the meme suite) available will degrade RiPP precursor predictions as RODEO cannot be used, but it will not prevent predictions completely.
