### ISSUE TITLE
Exec format error: '/opt/conda/bin/hmmpress' when running download-antismash-databases

### ISSUE THREAD

**Issue by bennend** [antismash/antismash#621]
Hi,

I was trying to download the databases with download-antismash-databases (antismash 6.1.0, command line version). But I got the following error:
` > [18/28] RUN download-antismash-databases:

3.175 Downloading PFAM version 34.0

Downloading Pfam-A.hmm.gz: 97.66% downloaded.Traceback (most recent call last):

33.54   File "/opt/conda/bin/download-antismash-databases", line 8, in <module>

Downloading Pfam-A.hmm.gz: 100.00% downloaded.

33.54 Creating checksum of Pfam-A.hmm.gz

33.54 Extraction of Pfam-A.hmm.gz finished successfully.

33.54     sys.exit(_main())

33.54   File "/opt/conda/lib/python3.10/site-packages/antismash/download_databases.py", line 397, in _main

33.54     download(args)

33.54   File "/opt/conda/lib/python3.10/site-packages/antismash/download_databases.py", line 360, in download

33.54     download_pfam(

33.54   File "/opt/conda/lib/python3.10/site-packages/antismash/download_databases.py", line 237, in download_pfam

33.54     ensure_database_pressed(filename)

33.54   File "/opt/conda/lib/python3.10/site-packages/antismash/common/hmmer.py", line 303, in ensure_database_pressed

33.54     result = subprocessing.run_hmmpress(filepath)

33.54   File "/opt/conda/lib/python3.10/site-packages/antismash/common/subprocessing/hmmpress.py", line 20, in run_hmmpress

33.54     return execute([get_config().executables.hmmpress, "-f", hmmfile])

33.54   File "/opt/conda/lib/python3.10/site-packages/antismash/common/subprocessing/base.py", line 85, in execute

33.54     with Popen(commands, stdin=stdin_redir, stdout=stdout, stderr=stderr) as proc:

33.54   File "/opt/conda/lib/python3.10/subprocess.py", line 971, in __init__

33.54     self._execute_child(args, executable, preexec_fn, close_fds,

33.54   File "/opt/conda/lib/python3.10/subprocess.py", line 1847, in _execute_child

33.54     raise child_exception_type(errno_num, err_msg, err_filename)

33.54 OSError: [Errno 8] Exec format error: '/opt/conda/bin/hmmpress'`

I encountered this when I try to build a docker image with Antismash. My PC is Apple M1, not sure if it is related to this.
I've tried changing the python version but no good. Any idea how to fix this? Thanks in advance.

Best,

Ben

**Comment by kblin** [comment]
I'm not sure if there's a hmmer build for M1 macs on bioconda yet, can you double-check you got the right binary?
