### ISSUE TITLE
ValueError: Equivalence group contains unknown identifiers

### ISSUE THREAD

**Issue by bennend** [antismash/antismash#622]
Hi, I am running Antismash 6.0.1 on linux with following command:
`antismash --hmmdetection-strictness strict -c 1 --taxon bacteria input --output-dir output `

But I got following error:

`Traceback (most recent call last):
  File "/opt/conda/bin/antismash", line 8, in <module>
    sys.exit(entrypoint())
  File "/opt/conda/lib/python3.10/site-packages/antismash/__main__.py", line 129, in entrypoint
    sys.exit(main(sys.argv[1:]))
  File "/opt/conda/lib/python3.10/site-packages/antismash/__main__.py", line 118, in main
    antismash.run_antismash(sequence, options)
  File "/opt/conda/lib/python3.10/site-packages/antismash/main.py", line 630, in run_antismash
    result = _run_antismash(sequence_file, options)
  File "/opt/conda/lib/python3.10/site-packages/antismash/main.py", line 690, in _run_antismash
    timings = run_detection(record, options, module_results)
  File "/opt/conda/lib/python3.10/site-packages/antismash/main.py", line 171, in run_detection
    run_module(record, cast(AntismashModule, module), options, module_results, timings)
  File "/opt/conda/lib/python3.10/site-packages/antismash/main.py", line 241, in run_module
    results = module.run_on_record(record, results, options)
  File "/opt/conda/lib/python3.10/site-packages/antismash/detection/hmm_detection/__init__.py", line 153, in run_on_record
    results = detect_protoclusters_and_signatures(record, signatures, seeds, rules, valid_categories,
  File "/opt/conda/lib/python3.10/site-packages/antismash/common/hmm_rule_parser/cluster_prediction.py", line 434, in detect_protoclusters_and_signatures
    results, results_by_id = filter_results(results, results_by_id, filter_file, set(sig_by_name))
  File "/opt/conda/lib/python3.10/site-packages/antismash/common/hmm_rule_parser/cluster_prediction.py", line 240, in filter_results
    raise ValueError("Equivalence group contains unknown identifiers: %s" % (unknown))
ValueError: Equivalence group contains unknown identifiers: {'Chal_sti_synt_N', 'hglE', 't2fas', 't2ks', 'APE_KS1', 'ft1fas', 't2pks2', 'fabH', 'DarB', 't2clf', 'FabF', 'Chal_sti_synt_C', 'bt1fas', 'PUFA_KS', 'ksIII', 'ladderane', 'hglD', 'PKS_KS', 'APE_KS2'}`

What could possibly cause this error? Thanks in advanced.

Best

**Comment by kblin** [comment]
I'm assuming you installed this one using conda? It looks like there's profiles missing from the detection profile setup. This shouldn't be happening at all in a functional install.
Could you run `grep Chal_sti_synt_N /opt/conda/lib/python3.10/site-packages/antismash/common/hmm_rule_parser/data/hmmdetails.txt` and tell me the result?

**Comment by bennend** [comment]
Thank you for your prompt reply!!

Actually I installed it with pip:

`RUN wget https://dl.secondarymetabolites.org/releases/latest/antismash-6.0.1.tar.gz`
`RUN tar -zxvf antismash-6.0.1.tar.gz  `
`RUN pip3 install ./antismash-6.0.1  `
`RUN conda install -c bioconda hmmer2=2.3.2 diamond=0.9.14 fasttree=2.1.10 prodigal=2.6.3 muscle=3.8.1551  glimmerhmm=3.0.4 -y   `
`RUN download-antismash-databases  `

And there is no **data** folder in `/opt/conda/lib/python3.10/site-packages/antismash/common/hmm_rule_parser/`, instead I could get `Chal_sti_synt_N	Type III PKS N-terminal	21	Chal_sti_synt_N.hmm` using grep command from `/opt/conda/lib/python3.10/site-packages/antismash/detection/hmm_detection/data/hmmdetails.txt`.

Thanks again

**Comment by bennend** [comment]
For unknown reason, it is working normally again😂, but thanks anyways.

**Comment by kblin** [comment]
Just out of curiosity, why are you building a docker container yourself? Is there an issue with the docker containers we provide?

**Comment by bennend** [comment]
I am just not aware of that, since when did you have the docker container? I would definetly pull yours if I was aware of it 2 yrs ago.

**Comment by SJShaw** [comment]
> I am just not aware of that, since when did you have the docker container? I would definetly pull yours if I was aware of it 2 yrs ago.

I'm a little late, but the docker containers go back to antiSMASH 3 around 8 years ago: https://hub.docker.com/r/antismash/standalone/tags
