### ISSUE TITLE
How can results for NRPS/PKS products be obtained in the command-line version?

### ISSUE THREAD

**Issue by senlinZ** [antismash/antismash#630]
I am able to obtain NRPS/PKS products in the web version, but not in the command-line version. I have set all the parameters in the command-line version, yet I am still unable to obtain results for NRPS/PKS products, which are crucial for my analysis. I analyzed the example data using both the web version and the command-line version simultaneously, but the command-line version still could not generate results for NRPS/PKS products. Therefore, I would like to inquire if it is possible to achieve results for NRPS/PKS products in the command-line version by adjusting the parameter settings or adding databases.

**Comment by SJShaw** [comment]
The web version is just the command line version with a shiny UI and some queuing. By default, the web version turns on some extra analyses (equivalent to `--asf --cb-subclusters --cb-kknownclusters --rre --tfbs`, unless you've unchecked those boxes on the web UI).

NRPS and PKS protoclusters will be detected regardless of settings. The only way to disable those is to edit the detection rules themselves. Similarly, NRPS/PKS domains will be detected unless you've made some edits to code.

As for the compounds and predictions for those protoclusters, those are enabled by default and will only be disabled when `--minimal` is present in the arguments.

If you can provide the command you're using and which version of antiSMASH you're using, we might be able to help more.

**Comment by senlinZ** [comment]
Thanks! I disabled --minimal and got the compounds and predictions I was looking for. Turns out I missed the complete help documentation. By the way, I have a quick question to ask: Is it advisable to merge multiple bacterial genome (more than 1000 genomes) FASTA files together for Antismash analysis? I noticed that some tutorials suggest analyzing them individually.

**Comment by zreitz** [comment]
I'm not on the antiSMASH team, but as a power user I'd recommend analyzing them individually. It would be quite painful to have to start from scratch if antiSMASH encounter an error after 800 genomes, and the HTML output is not designed for so many BGCs.

There are a few third-party workflows for putting large numbers of genomes through antiSMASH. [BGCflow](https://github.com/NBChub/bgcflow) is probably the most comprehensive. I've also written a much simpler (and less documented) [pipeline](https://github.com/zreitz/multismash).

**Comment by SJShaw** [comment]
Any automated system worthy of the description can process 1000 output files just as easily as a single file, and for 1000 genomes you should definitely be doing some kind of automated processing of results.

There's no real advantage to combining genomes into a single file, but there are many disadvantages:
- more fragile runs
- more resource demanding runs (more memory, much larger files)
- more resource intensive results processing, whether human or machine (opening one file that's 1000 times as large needs 1000 times as much memory, and visually processing an HTML page that's 1000 times larger is not a good idea)

and so on.

Anyway, since the initial issue is resolved, I'll close this.

**Comment by senlinZ** [comment]
Thank you for your invaluable help!

2023-08-04 00:21:42SJShaw ***@***.***>写道：

Any automated system worthy of the description can process 1000 output files just as easily as a single file, and for 1000 genomes you should definitely be doing some kind of automated processing of results.

There's no real advantage to combining genomes into a single file, but there are many disadvantages:

more fragile runs
more resource demanding runs (more memory, much larger files)
more resource intensive results processing, whether human or machine (opening one file that's 1000 times as large needs 1000 times as much memory, and visually processing an HTML page that's 1000 times larger is not a good idea)

and so on.

Anyway, since the initial issue is resolved, I'll close this.
