### ISSUE TITLE
Installled v7.0.1 but "antismash --version" outputs 6.0.0

### ISSUE THREAD

**Issue by jmpolinski** [antismash/antismash#641]
I've just downloaded the tar.gz source code for v7.0.1 and installed it following the full manual install instructions. Everything looks good when the installation ends, with the message ```Successfully installed antismash-7.0.1```. 

However, when I then run ```antismash --version``` the output is ```antiSMASH 6.0.0``` and running the program leads to an error related to not having the older muscle version installed, which I believe indicates it is version 6 being installed, not 7. 

Why is it installing version 6, not 7? How do I get the newest version if I have to do a manual install on my system?

I am working on a RHEL7 system.

**Comment by zreitz** [comment]
Does `which antismash` return the expected path or a previous installation? You'll need to set a new alias. 

`python path/to/antismash7/run_antismash.py --version` should output `7.0.1`.

**Comment by jmpolinski** [comment]
The previous installation was uninstalled and all associated files removed prior to attempting the new installation (location is ```/usr/local/bin/antismash```). I go to uninstall it again, I get the following message suggesting this is the newly installed copy:
```
Found existing installation: antismash 7.0.1
Uninstalling antismash-7.0.1:
  Would remove:
    /usr/local/bin/antismash
    /usr/local/bin/download-antismash-databases
    /usr/local/lib/python3.8/site-packages/antismash-7.0.1.dist-info/*
    /usr/local/lib/python3.8/site-packages/antismash/*
Proceed (Y/n)?
```

If I go into the directory I used for the python installation and run ```python3 ./run_antismash.py --version``` I get the following error message:
```
Traceback (most recent call last):
  File "./run_antismash.py", line 6, in <module>
    from antismash.__main__ import entrypoint
  File "/data/app/antismash-7-0-1/antismash/__init__.py", line 12, in <module>
    from antismash.main import run_antismash, get_detection_modules, \
  File "/data/app/antismash-7-0-1/antismash/main.py", line 33, in <module>
    from antismash.common import logs, record_processing, serialiser
  File "/data/app/antismash-7-0-1/antismash/common/record_processing.py", line 24, in <module>
    from .subprocessing import parallel_function
  File "/data/app/antismash-7-0-1/antismash/common/subprocessing/__init__.py", line 38, in <module>
    from .hmmscan import (
  File "/data/app/antismash-7-0-1/antismash/common/subprocessing/hmmscan.py", line 13, in <module>
    def _find_error(output: list[str]) -> str:
TypeError: 'type' object is not subscriptable
```

**Comment by SJShaw** [comment]
> The previous installation was uninstalled and all associated files removed prior to attempting the new installation. Now "which antismash" outputs `/usr/local/bin/antismash`. If go to uninstall it, I get the following message suggesting this is the newly installed copy:
> 
> ```
> Found existing installation: antismash 7.0.1
> Uninstalling antismash-7.0.1:
>   Would remove:
>     /usr/local/bin/antismash
>     /usr/local/bin/download-antismash-databases
>     /usr/local/lib/python3.8/site-packages/antismash-7.0.1.dist-info/*
> ```
Python 3.8 isn't new enough for the python features antiSMASH 7 is using. Somehow we missed updating the minimum version in `setup.py` to 3.9. I'm certain I made a change to that at some point, but I must never have ended up with it coming into the main repository. I'll put in a fix for that right after this.

In any case, that is the cause of this error:
> ```
>     def _find_error(output: list[str]) -> str:
> TypeError: 'type' object is not subscriptable
> ```

This might also explain why your version is reporting 6 still, because running 7 would never have worked with that python version.
