### ISSUE TITLE
Error 'could not parse records from GFF3 file' from web-based antismash fungal version

### ISSUE THREAD

**Issue by Teeratask** [antismash/antismash#647]
I recently submitted a web-based antismash job for a fungal version. Once I loaded my assembly and gff3 files and ran it, I got an error message saying "failed: Job returned errors: ERROR 03/09 18:16:55 invalid literal for int() with base 10: 'start' ERROR 03/09 18:16:55 could not parse records from GFF3 file". See an attached screenshot for more details. 

I am not sure how to fix the issue to make the antismash run smoothly. I used the web-based antismash in Google Chrome browser. The gff3 file is derived from MAKER. The assembly and gff3 files are provided in a Google drive link below in order to reproduce the issue:
https://drive.google.com/drive/folders/1VIeCBpBCKyZDC21RKNJBHB8yfsmIPQIv?usp=sharing

**Screenshots**
![image](https://github.com/antismash/antismash/assets/22451281/e80f4325-10bd-4ea1-af47-9c60e63e1298)

**Comment by SJShaw** [comment]
That heading line is missing a leading `#`, you'll need to the character or remove that line .

**Comment by Teeratask** [comment]
I could get it run now. Thank you very much.
