### ISSUE TITLE
Genbank corrupts contig ID in antiSMASH v6.1.1

### ISSUE THREAD

**Issue by jolespin** [antismash/antismash#651]
**Describe the bug**
`ID` field in genbank gets corrupted.  Name is correct for contig ID. 

**Expected behavior**

```
ID: S1__NODE_447_length_17931_cov_7.22600
Name: S1__NODE_447_length_17931_cov_7.022600
Description: S1__NODE_447_length_17931_cov_7.022600
Number of features: 18
/topology=linear
/data_file_division=UNK
/date=01-JAN-1980
/accessions=['S1__NODE_447_length_17931_cov_7']
/sequence_version=22600
/keywords=['']
/source=
/organism=
/taxonomy=[]
/structured_comment=defaultdict(<class 'dict'>, {'antiSMASH-Data': {'Version': '6.1.1', 'Run date': '2023-07-11 16:25:33 NOTE: This is a single cluster extracted from a larger record!', 'Orig. start': '8266', 'Orig. end': '17931'}})
/molecule_type=DNA
Seq('ATTTTCGTCCGCCATGGCCAGCATCGATCGCGCGTGCCGCGCGGCGACTTCGCC...TTC')
```
**To Reproduce**

        antismash --allow-long-headers --verbose --skip-zip-file -c 16 --output-dir ${INTERMEDIATE_DIRECTORY}/${ID} --html-title ${ID} --taxon bacteria --minlength 1000 --databases %s --hmmdetection-strictness strict --logfile ${INTERMEDIATE_DIRECTORY}/${ID}/log.txt --genefinding-gff3 ${GENE_MODELS} ${GENOME}

Version: 

```
seq_record.annotations

{'topology': 'linear',
 'data_file_division': 'UNK',
 'date': '01-JAN-1980',
 'accessions': ['S1__NODE_447_length_17931_cov_7'],
 'sequence_version': 22600,
 'keywords': [''],
 'source': '',
 'organism': '',
 'taxonomy': [],
 'structured_comment': defaultdict(dict,
             {'antiSMASH-Data': {'Version': '6.1.1',
               'Run date': '2023-07-11 16:25:33 NOTE: This is a single cluster extracted from a larger record!',
               'Orig. start': '8266',
               'Orig. end': '17931'}}),
[S1__METABAT2__P.1__bin.2.zip](https://github.com/antismash/antismash/files/12601782/S1__METABAT2__P.1__bin.2.zip)

 'molecule_type': 'DNA'}
```

**Comment by SJShaw** [comment]
Could you provide an example input and output where both are in Genbank format? I can't replicate this and I can't rebuild a real genbank file from your example input and partial output.

**Comment by SJShaw** [comment]
Additionally, now that version 7 has been out for a while, we won't be doing patches of version 6, so try using the latest and see if it's still an issue.

**Comment by jolespin** [comment]
I'll try to get some files together to reproduce. 

Do you know when antiSMASH might be available on anaconda.org via bioconda?

**Comment by zreitz** [comment]
antiSMASH 7 is installable in a conda environment, you just have to jump through a few hoops. Here's a protocol I've put together: [https://github.com/zreitz/multismash/#antismash-7-installation-protocol](https://github.com/zreitz/multismash/#antismash-7-installation-protocol)

**Comment by jolespin** [comment]
Are there any plans to put it on PyPI without the dependencies? The reason why I'm asking is because I'm including it in https://github.com/jolespin/veba and currently only using packages that are installable via conda/pip since the installations are already quite complex for each module. 

Also, is meme essential for the core functionality of antiSMASH7?

**Comment by jolespin** [comment]
I just updated the first comment and attaching the relevant files here:

[S1__METABAT2__P.1__bin.2.zip](https://github.com/antismash/antismash/files/12601788/S1__METABAT2__P.1__bin.2.zip)

**Comment by SJShaw** [comment]
> I just updated the first comment and attaching the relevant files here:
> 
> ```
> (base) jespinozlt2-osx:S1__METABAT2__P.1__bin.2 jespinoz$ ls -lhS
> total 3.4M
> -rw-r--r-- 1 jespinoz staff 2.4M Jul  8 01:06 S1__METABAT2__P.1__bin.2.fa
> -rw-r--r-- 1 jespinoz staff 1.1M Jul  8 01:20 S1__METABAT2__P.1__bin.2.gff
> -rw-r--r-- 1 jespinoz staff  34K Jul 11 16:25 S1__NODE_447_length_17931_cov_7.022600.region001.gbk
> ```
> 
> The contig ID in the actual genbank filename is correct:
> 
> ```
> (base) jespinozlt2-osx:S1__METABAT2__P.1__bin.2 jespinoz$ grep "S1__NODE_447_length_17931_cov_7.022600" S1__METABAT2__P.1__bin.2.fa
> >S1__NODE_447_length_17931_cov_7.022600
> ```
> 
> However, the ID and accessions are corrupted:
> 
> ```
> ID: S1__NODE_447_length_17931_cov_7.22600 # Missing the 0 after the period/fullstop
> Name: S1__NODE_447_length_17931_cov_7.022600 # <--- CORRECT
> Description: S1__NODE_447_length_17931_cov_7.022600 # <--- CORRECT
> /accessions=['S1__NODE_447_length_17931_cov_7'] # Missing everything after the period/fullstop
> ```
That `accessions` field is not present in the genbank file, it's generated by whatever tool you're using to load the genbank file.

Similarly, the output region's genbank has the correct output:
```
LOCUS       S1__NODE_447_length_17931_cov_7.022600 9665 bp    DNA     linear   UNK 01-JAN-1980
DEFINITION  S1__NODE_447_length_17931_cov_7.022600.
ACCESSION   S1__NODE_447_length_17931_cov_7
VERSION     S1__NODE_447_length_17931_cov_7.22600
```

For context, all input parsing and genbank output writing is handled by the biopython library.

The `VERSION` line removes the leading zero, because anything after a `.` is considered the version by biopython and thus goes through a conversion to an integer. As for the `ACCESSION` field, in the Genbank format that field is without the version number, which is why it's removed when written out by biopython.

If you want that information in your post processing, you'll need to either change which tool is reading the input or change your naming scheme to avoid confusion with version numbers. 

In any case, this isn't something we have control over since it's within biopython, and while we could modify records afterward, they would then not match up to the genbank file format expectations, which causes problems of its own.

**Comment by jolespin** [comment]
Got it!  That makes a lot of sense about the version info.  Similar to on PyPI if you do v.2023.09.14 it would turn out to be v2023.9.14.  That's weird Biopython uses this behavior on ID and ACCESSIONS as well.  No problem, I'll just use the NAME field.

**Comment by jolespin** [comment]
Out of scope, but is there any documentation or explanation about when CDS features are added that are not in the GFF file and include labels like `allorf_1307903_1308019`?
