### ISSUE TITLE
run_antismash script points to non-existant docker image

### ISSUE THREAD

**Issue by kaw97** [antismash/antismash#658]
The version of run_antismash pointed to on readthedocs currently tries to pull `docker.io/antismash/standalone:7.0.1`

This fails to run because there is no docker image with that tag. The latest image and 7.0.0 were both uploaded 5 months ago.
https://hub.docker.com/r/antismash/standalone/tags

Not sure 7.0.1 just hasn't been put on docker yet, but I changed my run_antismash script to pull `docker.io/antismash/standalone:latest`

**Comment by kblin** [comment]
This is fixed now, on our initial deploy it seems like the docker hub uploading failed. Having said that, the `standalone-lite` packages basically always work because those are the ones we run ourselves for the public web service.
