### ISSUE TITLE
too many problem of python package "biopython"

### ISSUE THREAD

**Issue by joybio** [antismash/antismash#670]
in setup.py, it required biopython>=1.78.
I installed biopython=1.81, however, it failed to start
```
ImportError: cannot import name 'UnknownSeq' from 'Bio.Seq'
```
or
```
Traceback (most recent call last):
  File "/data6/yangjunbo/miniconda3/envs/antismash/bin/antismash", line 5, in <module>
    from antismash.__main__ import entrypoint
  File "/data6/yangjunbo/miniconda3/envs/antismash/lib/python3.10/site-packages/antismash/__init__.py", line 12, in <module>
    from antismash.main import run_antismash, get_detection_modules, \
  File "/data6/yangjunbo/miniconda3/envs/antismash/lib/python3.10/site-packages/antismash/main.py", line 23, in <module>
    from Bio import SeqIO
  File "/data6/yangjunbo/miniconda3/envs/antismash/lib/python3.10/site-packages/Bio/SeqIO/__init__.py", line 379, in <module>
    from Bio.SeqIO import GckIO
  File "/data6/yangjunbo/miniconda3/envs/antismash/lib/python3.10/site-packages/Bio/SeqIO/GckIO.py", line 15, in <module>
    from Bio.SeqFeature import SimpleLocation
ImportError: cannot import name 'SimpleLocation' from 'Bio.SeqFeature' (/data6/yangjunbo/miniconda3/envs/antismash/lib/python3.10/site-packages/Bio/SeqFeature.py)
```
I also replaced biopython=1.78
```
File "/data6/yangjunbo/miniconda3/envs/antismash/lib/python3.10/site-packages/antismash/common/secmet/features/__init__.py", line 6, in <module>
    from .antismash_domain import AntismashDomain
  File "/data6/yangjunbo/miniconda3/envs/antismash/lib/python3.10/site-packages/antismash/common/secmet/features/antismash_domain.py", line 10, in <module>
    from .domain import Domain, generate_protein_location_from_qualifiers
  File "/data6/yangjunbo/miniconda3/envs/antismash/lib/python3.10/site-packages/antismash/common/secmet/features/domain.py", line 13, in <module>
    from .feature import Feature, FeatureLocation, Location
  File "/data6/yangjunbo/miniconda3/envs/antismash/lib/python3.10/site-packages/antismash/common/secmet/features/feature.py", line 13, in <module>
    from antismash.common.secmet.locations import (
  File "/data6/yangjunbo/miniconda3/envs/antismash/lib/python3.10/site-packages/antismash/common/secmet/locations.py", line 9, in <module>
    from Bio.SeqFeature import (
ImportError: cannot import name 'AbstractPosition' from 'Bio.SeqFeature' (/data6/yangjunbo/miniconda3/envs/antismash/lib/python3.10/site-packages/Bio/SeqFeature.py)
```
I tried to switch my biopython version, but met a lot of improt errors, such as "ImportError: cannot import name 'UnknownSeq' from 'Bio.Seq'. I'm confused which version should i use.

**Comment by SJShaw** [comment]
The removal of `UnknownSeq` in biopython 1.79 is what caused us to pin the version of biopython to 1.78 in 0d6a343 more than two years ago as part of antiSMASH 6.1. Which version of antiSMASH are you trying to use?

For your first error, that is biopython internal code referring to something else in biopython that is missing. This means something is wrong with your biopython install.

When you replaced it with 1.78, there's still something wrong with your biopython install, since 1.78 does have the `AbstractPosition` class, i.e.
```
$ pip freeze | grep biopython
biopython==1.78

$ python -c "from Bio.SeqFeature import AbstractPosition; print(AbstractPosition)"
<class 'Bio.SeqFeature.AbstractPosition'>
```

You will need to check your environment and fix whatever has gone wrong.

**Comment by joybio** [comment]
```
pip freeze | grep biopython
biopython==1.81
```
```
python -c "from Bio.SeqFeature import AbstractPosition; print(AbstractPosition)"
<class 'Bio.SeqFeature.AbstractPosition'>

python -c "from Bio.SeqFeature import AbstractPosition; print(SimpleLocation)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'SimpleLocation' is not defined
```

Initially, I attempted to install Antismash using the following command, but it encountered environment-related issues. 
```
conda install -n antismash antismash
Solving environment: | 
```
Consequently, I decided to install Antismash version 6.0.0 from the official website at https://docs.antismash.secondarymetabolites.org/install/.
```
wget https://dl.secondarymetabolites.org/releases/6.0.0/antismash-6.0.0.tar.gz
tar -zxf antismash-6.0.0.tar.gz
pip install ./antismash-6.0.0
```

**Comment by SJShaw** [comment]
> ```
> pip freeze | grep biopython
> biopython==1.81
> ```

This is the problem, you will need to install 1.78. Versions 1.79 and above cause problems, which is why we pinned the version to 1.78 years ago.

> Consequently, I decided to install Antismash version 6.0.0 from the official website at https://docs.antismash.secondarymetabolites.org/install/.

Is there a reason you want to use 6.0 specifically? It's now 3 years old and is missing many of the fixes and improvements that have happened between now and then (e.g. the biopython version pin in 6.1.0).

**Comment by joybio** [comment]
I want to install the latest version, but when I try to install it using conda, it consistently gets stuck in the environment resolution process. As a workaround, I had to refer to the installation page, which recommended an alternative installation method.  I followed the instructions specified at this link: https://docs.antismash.secondarymetabolites.org/install/.

**Comment by SJShaw** [comment]
> I want to install the latest version, but when I try to install it using conda, it consistently gets stuck in the environment resolution process. As a workaround, I had to refer to the installation page, which recommended an alternative installation method. I followed the instructions specified at this link: https://docs.antismash.secondarymetabolites.org/install/.

As the page says, 6.0 is used as an example, follow the link in the bolded section to find the latest releases:

![image](https://github.com/antismash/antismash/assets/1700735/9891242f-611f-4f1d-a510-9b7e39808fbd)

Also, conda is bad at resolving environments, that's not an antiSMASH-specific thing. The problems with conda are a major the reason there is no recent version of antiSMASH on conda.

**Comment by joybio** [comment]
I successfully installed AntiSMASH 7.0.1, thanks for your assistance!
