### ISSUE TITLE
Error：pip install antismash-7.1.0

### ISSUE THREAD

**Issue by qkqk-hub** [antismash/antismash#682]
Hello, I had an error while installing antismash.

When I execute `pip install antismash 7.1.0`.

The error is as follows:
`ERROR: Could not find a version that satisfies the requirement antismash-7.1.0 (from versions: none)`
`ERROR: No matching distribution found for antismash-7.1.0`

My version of python is : 3.9.18
My version of pip is : 23.3.1

Should I change the pip version?

Or what should I do?

Thank you for your reply

**Comment by qkqk-hub** [comment]
Thank you for your prompt reply

I refer to this [https://docs.antismash.secondarymetabolites.org/install/#installing-the-latest-antismash-release](https://docs.antismash.secondarymetabolites.org/install/#installing-the-latest-antismash-release)
It's mentioned here:`pip install ./antismash-6.0.0`,But I got an error when using `pip install./antismash-7.1.0`.

Is it because my pip version is wrong?

I have used `pip install ./antismash-7.1.0` successfully, but I forget the pip version at the time

**Comment by SJShaw** [comment]
The version of your pip is irrelevant.

The `./` at the beginning is important, it means that it's looking for a directory named `antismash-7.1.0` in the current directory.

If you leave the `./` (or rest of the local path, if applicable) out, then it looks on https://pypi.org/, where there isn't a package.

**Comment by qkqk-hub** [comment]
Thank you very much, I have successfully downloaded and used antismash.

Thank you again for your patient guidance!

**Comment by SJShaw** [comment]
The HTML is the visual output.
The JSON is the machine readable output.
The GBK(s) are the default genome viewer style outputs, but do not contain all the information in the other two options.

**Comment by qkqk-hub** [comment]
Ok, thank you very much. I'll interrupt again if there are any other questions. Thank you！
