### ISSUE TITLE
Some protoclusters in a "neighbouring candidate cluster" don't belong to anyone of the other kinds of candidate clusters

### ISSUE THREAD

**Issue by RuolinHe** [antismash/antismash#687]
**Describe the bug**
I found some protoclusters in a "neighbouring candidate cluster" don't belong to anyone of the other kinds of candidate clusters.

**Expected behavior**
As mentioned in [antismash documentation](https://docs.antismash.secondarymetabolites.org/understanding_output/regions/#neighbouring), "Every protocluster in a "neighbouring candidate cluster" will also belong to one of the other kinds of candidate clusters".

**To Reproduce**
My inputs are two annotated fungal genomes in the genbank format, [GCA_010093885.1](https://www.ncbi.nlm.nih.gov/datasets/genome/GCA_010093885.1/) and [GCA_016861735.1](https://www.ncbi.nlm.nih.gov/datasets/genome/GCA_016861735.1/).

For interaction issues, also include steps to reproduce the behavior:
1. run antismash. My command is 
```
antismash /storage/disk1/HRL/Project/SM_in_genome/Fungi/ncbi_dataset/data/GCA_010093885.1/GCA_010093885.1.gbff --asf --clusterhmmer --cc-mibig --tfbs --cb-knownclusters --output-dir /storage/disk1/HRL/Project/SM_in_genome/Fungi_antismash_result/GCA_010093885.1--skip-zip-file --taxon fungi --genefinding-tool none
antismash /storage/disk1/HRL/Project/SM_in_genome/Fungi/ncbi_dataset/data/GCA_016861735.1/GCA_016861735.1.gbff --asf --clusterhmmer --cc-mibig --tfbs --cb-knownclusters --output-dir /storage/disk1/HRL/Project/SM_in_genome/Fungi_antismash_result/GCA_016861735.1--skip-zip-file --taxon fungi --genefinding-tool none
```

2. Go to antismash result:  file://192.168.1.150/disk1/HRL/Project/SM_in_genome/Fungi_antismash_result/GCA_010093885.1/index.html#r94c1 and file://192.168.1.150/disk1/HRL/Project/SM_in_genome/Fungi_antismash_result/GCA_016861735.1/index.html#r3c3
3. See error

**Screenshots**
file://192.168.1.150/disk1/HRL/Project/SM_in_genome/Fungi_antismash_result/GCA_010093885.1/index.html#r94c1
![image](https://github.com/antismash/antismash/assets/76482251/fbe34e03-5b60-482c-9dc3-aceedc8525d2)
Two protoclusters (NRPS-like and T1PKS), but there is only a neighbouring candidate cluster, no Chemical hybrid, Interleaved or Single candidate cluster.

file://192.168.1.150/disk1/HRL/Project/SM_in_genome/Fungi_antismash_result/GCA_016861735.1/index.html#r3c3
![image](https://github.com/antismash/antismash/assets/76482251/f497da76-e1a4-4a05-b25b-51e3316a18ba)
There is no additional candidate cluster except neighbouring candidate cluster for T1PKS protocluster.

**System (please complete the following information):**
 - Linux version 4.18.0-193.28.1.el8_2.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 8.3.1 20191121 (Red Hat 8.3.1-5) (GCC))

**Additional context**
The version of antismash I used is 7.0.0.

**Comment by SJShaw** [comment]
This is expected behaviour.

In the first example, both of the singles and the neighbouring candidates would all have the same coordinates, so only the neighbouring is used as the rest are duplicate information.

In the second example, only one of the singles has the same coordinates, where the other (the indole) does not have the same coordinates, leaving it present.

**Comment by RuolinHe** [comment]
I got it. Thanks!
