### ISSUE TITLE
https://dl.secondarymetabolites.org/ seems to be down, unable to curl docker image

### ISSUE THREAD

**Issue by kkj15dk** [antismash/antismash#693]
I am unable to curl the docker image, I believe it is because the domain is down.

Using the command "curl -q https://dl.secondarymetabolites.org/releases/latest/docker-run_antismash-full > ~/bin/run_antismash" yields an Error: curl: (6) Could not resolve host: dl.secondarymetabolites.org

I can try the version directly from docker https://hub.docker.com/r/antismash/standalone-nonfree, but the parameter calling might be different than I'm used to.

Or i can try the run_antismash script from bitbucket: https://bitbucket.org/antismash/docker/raw/HEAD/standalone/run_antismash, however I'm not sure if this is up to date.

**Comment by kblin** [comment]
We've had some DNS issues that should be fixed now.
