### ISSUE TITLE
Error: could not parse records from GFF3 file

### ISSUE THREAD

**Issue by egluckthaler** [antismash/antismash#713]
Hi there,

I am running antismash v7.1.0 downloaded via bioconda. I have installed the antismash database using the download-antismash-databases command. When I run the antismash command, I get the following error within 10 seconds whether I provide a gff3 file or not:

```ERROR: could not parse records from GFF3 file```

**To Reproduce**
Here are the two commands that each produce this same error:
```antismash --databases /staging/groups/gluckthaler_group/databases/antismash --cpus 4 --output-basename test --output-dir output/ --taxon fungi --clusterhmmer --verbose --genefinding-tool glimmerhmm fusoxy65.fna```

```antismash --databases /staging/groups/gluckthaler_group/databases/antismash --cpus 4 --output-basename test --output-dir output/ --taxon fungi --clusterhmmer --verbose --genefinding-gff3 fusoxy65.gff3 fusoxy65.fna```

**Screenshots**
contents of database directory: ![database_content](https://github.com/antismash/antismash/assets/27787866/b46a2cc2-0176-413c-aa2d-f8360749f38a)
contents of gff3 and assembly file:
![file_content](https://github.com/antismash/antismash/assets/27787866/c3c4357c-2b4f-4d62-b8ed-37993e0100dd)
GFF error 1:
![gff_error1](https://github.com/antismash/antismash/assets/27787866/79795990-0d4d-4e19-b328-c76ee50a6fcd)
GFF error 2:
![gff_error2](https://github.com/antismash/antismash/assets/27787866/173afa50-5c91-4a7f-ba7e-b8aa214da0db)

**System (please complete the following information):**
CentOS Stream 9

**Additional context**
I also tried installing the databases in their default location within the conda package directory, but I get the same error

What could be going on here? Thanks for your help

**Comment by SJShaw** [comment]
The databases aren't relevant for this issue, as they are only used once parsing is successful.

The only place in the codebase where that error is raised without additional INFO level logging is when the underlying parsing library, `bcbio-gff`, raises an exception itself.

You could try using the latest development version of antiSMASH (i.e. clone the repository and use the `master` branch) which updates some inter-related dependency versions, including the latest `bcbio-gff`. If that still fails, then I'd need to see the full entry of the GFF file to be able to guess what might be wrong.

I'd also try testing each record individually, which would help work out whether it's a systemic issue in the GFF format or an issue with a particular record.

**Comment by egluckthaler** [comment]
Great thank you for that info. I'll try using the latest development version. Just to check though: I get this error even when I do not provide a GFF, and when I specify ```--genefinder-tool glimmerhmm```. Wouldn't this indicate that the issue doesn't have to do with the specific GFF file that I provide?

**Comment by SJShaw** [comment]
There's no path to GFF parsing if `--genefinding-tool` is not set to `gff`, since the only file read will be the FASTA/GBK given.

If it happens with everything, I suspect there's something wrong in how you're running antiSMASH and it's causing some confusion.

**Comment by egluckthaler** [comment]
sorry, I wasn't clear: I do not specify the ```--genefinding-gff3``` option when I specify the ```--genefinding-tool``` option, and I still get the error.

I tried running the following commands using the example data (NCBI Reference Sequence: NC_007194.1) from [the fungismash website](https://fungismash.secondarymetabolites.org/#!/start)

Running with option ```--genefinding-tool glimmerhmm``` fails with ```ERROR: could not parse records from GFF3 file``` as before:
```antismash --databases /staging/groups/gluckthaler_group/databases/antismash --cpus 4 --output-basename test --output-dir output/ --taxon fungi --verbose --genefinding-tool glimmerhmm NC_007194.fasta```

Running with option ```--genefinding-gff3``` fails with ```ERROR: could not parse records from GFF3 file``` and with an additional error (see screenshot):
```antismash --databases /staging/groups/gluckthaler_group/databases/antismash --cpus 4 --output-basename test --output-dir output/ --taxon fungi --verbose --genefinding-gff3 NC_007194.gff3 NC_007194.fasta```

Running without ```--genefinding-tool``` or ```--genefinding-gff3``` using the .gbk only works, demonstrating that antismash can successfully run on my system:
```antismash --databases /staging/groups/gluckthaler_group/databases/antismash --cpus 4 --output-basename test --output-dir output/ --taxon fungi --verbose NC_007194.gbk```

Any thoughts?

![Screenshot 2024-04-26 at 11 06 13](https://github.com/antismash/antismash/assets/27787866/382be48b-efb4-4cc7-a2bf-57b1dbd36e10)

**Comment by zreitz** [comment]
>`module 'Bio.SeqFeature' has no attribute 'SimpleLocation'`

What's your biopython version? The current master branch requires `'biopython == 1.81'` , while the [7.1.0 stable branch](https://github.com/antismash/antismash/tree/7-1-stable) is pinned at `biopython == 1.78`.

**Comment by gguerr001** [comment]
Hi I have been getting the same error running antismash for fungi genomes using my own gff file or using --genefinding-tool glimmerhmm. I managed to avoid it by downgrading the version of  the `bcbio-gff` package from 0.7.1 to 0.7.0

**Comment by egluckthaler** [comment]
thank you Guillermo, that fixed my problem as well!
