### ISSUE TITLE
Feature Request: Discard empty and rRNA/tRNA unique contigs

### ISSUE THREAD

**Issue by adriangeerre** [antismash/antismash#715]
**Is your feature request related to a problem? Please describe.**
I am running antismash v7.1.0 using singularity after creating the sif image from the docker image repository. When I provide the PGAP GenBank annotation files for the bacteria I assembled, the software fails with the error

"ERROR    06/05 16:10:33   Record X contains no genes and no genefinding tool specified"

After cleaning the annotation from empty contigs (without genes) the software still fails. I figure out that it would not accept contigs that only contains tRNA or rRNA genes. Removing them from the annotation allows the software to complete the run succesfully. The main issue is the constant interruption that break the workflow.

**Describe the solution you'd like**
The solution is to parse the contigs and discard empty and rRNA/tRNA unique contigs from the search automatically.

**Describe alternatives you've considered**
Cleaning the assemblies using BioPython or manually.

**Additional context**
A secondary upgrade would be the linearization of circular contigs by reordering the start of the first gene so it would not be part of both start and end.

Thank you, sorry if this was already requested and discarded, and good luck :)

**Comment by zreitz** [comment]
A potential solution for now is to use the `--no-abort-on-invalid-records` flag, which will ignore invalid contigs and continue to process the rest.

**Comment by adriangeerre** [comment]
Thank you for the quick answer! :)

Execution:
singularity exec {image} antismash --taxon bacteria -c {threads} --cb-general --cb-knownclusters --cb-subclusters --asf --pfam2go --smcog-trees **--no-abort-on-invalid-records** --output-dir {out_dir} {genbank}

Resut: The flag does not avoid the issue.

Log:
ERROR    06/05 23:00:50   Record 4 contains no genes and no genefinding tool specified
ERROR: Record 4 contains no genes and no genefinding tool specified

**Comment by zreitz** [comment]
Hmm, perhaps Simon can explain if that flag is only supposed to bypass certain errors or if this is unintended.

But I see you are not using the `--genefinding-tool none` flag. Have you tried it? It alleviates the need to remove empty contigs, and I'd think it'll work generally when there's no CDS features.

**Comment by adriangeerre** [comment]
Yes! Adding both flags allowed me to automatize the process. However, I am afraid that it will skip the circular contigs whose origin is overlapped*. Thank you for your time and help :)

*a gene containing the start of the sequence inside causing it to divide between start and end of the sequence.

**Comment by SJShaw** [comment]
Yeah, there's a distinction between "invalid" records and "empty" records. By the default the genefinding error comes up for empty records, because it's usually something being forgotten rather than a bad input in itself.

The circular contigs won't be skipped, but it will split the gene crossing the origin into two and treat the record as linear. Once #697 is merged, that will no longer be an issue.
