### ISSUE TITLE
Choose File Format for Clusterblast results 

### ISSUE THREAD

**Issue by b-temu** [antismash/antismash#726]
Enable to choose the file formats for the clusterblast results

**Comment by SJShaw** [comment]
What format(s) are you wanting?

For some context on the next release, these changes have been made since 7.1.0:
- #701 removed the SVG output files for clusterblast results, replacing them with dynamically drawn versions in the HTML output (but can still be saved to disk from there)
- #646 removed the raw diamond output files from the output

The only remaining on-disk files including the clusterblast information are the JSON, which can be used by a variety of tools and scripting languages to convert it to your format of choice.

**Comment by b-temu** [comment]
The text files in the clusterblast to be another format and not textfile example is shown below:

```
ClusterBlast scores for c00002_NODE_7_..

Table of genes, locations, strands and annotations of query cluster:
ctg2_8	6052	7498	+		
ctg2_9	7554	8226	-		
ctg2_10	8322	8643	-		
ctg2_11	8880	9147	-		
ctg2_12	9231	9675	-
......
Significant hits: 
1. NZ_LR134265	Streptococcus agalactiae strain NCTC8184 chromosome 1
2. NZ_CP020432	Streptococcus sp. 'group B' strain FDAARGOS_229 chromosome, complete genome
3. NZ_CP007631	Streptococcus agalactiae strain NGBS061, complete genome
4. NZ_CP013908	Streptococcus agalactiae strain GBS-M002, complete genome

......

Details:

>>
1. NZ_LR134265
Source: Streptococcus agalactiae strain NCTC8184 chromosome 1
Type: arylpolyene
Number of proteins with BLAST hits to this cluster: 36
Cumulative BLAST score: 25115

Table of genes, locations, strands and annotations of subject cluster:
EL071_RS09160	EL071_RS09160	1788954	1789738	-	multidrug_ABC_transporter_permease
EL071_RS09205	EL071_RS09205	1795384	1795592	-	hypothetical_protein

Table of Blast hits (query gene, subject gene, %identity, blast score, %coverage, e-value):

ctg2_9	EL071_RS09035	100	431	100.0	5.2e-119
ctg2_10	EL071_RS09040	100	196	100.0	1.7e-48
......

```
Accessing this in another format such as JSON, CSV, TSV...etc

**Comment by SJShaw** [comment]
That is the raw diamond output file that I mentioned has been removed for future versions. We don't intend to keep it around as quite a lot of the results aren't relevant to antiSMASH itself and the file size tends to be much larger than all the other results combined. Those parts of the diamond results that antiSMASH uses are present in the existing antiSMASH JSON output.

If you want all those raw results, you can install [diamond](https://github.com/bbuchfink/diamond), download the [clusterblast dataset](https://dl.secondarymetabolites.org/releases/clusterblast/clusterblast_4.0.tar.xz) that antiSMASH uses, and use the diamond TSV output option. If you have a local install of antiSMASH, you'll already have diamond installed and can use the clusterblast dataset fetched by `download-antismash-databases`.
