### ISSUE TITLE
Database download fails

### ISSUE THREAD

**Issue by jasmezz** [antismash/antismash#737]
**Describe the bug**
The command `download-antismash-databases` fails with a checksum error (see below screenshot):

![image](https://github.com/user-attachments/assets/65a24078-8271-404c-b0d2-88f41310d324)

**Expected behavior**
Executing `download-antismash-databases` downloads databases and checksum tests succeed.

**To Reproduce**
1. Install antismash, run `download-antismash-databases`
2. Wait until Pfam databases have been downloaded and checksum test succeeds
3. Wait until Resfam databases have been downloaded and checksum test fails ("`Resfams.hmm.gz, sha256sum mismatch`")
4. See error (above screenshot)

**System (please complete the following information):**
 - OS: Ubuntu
 - antismash installation: both conda and docker container show the same behaviour

**Additional context**
Example failing run: https://github.com/nf-core/funcscan/actions/runs/10575384160/job/29304607220?pr=413

**Comment by kblin** [comment]
Hi, thanks for letting us know. I'm afraid that is somewhat expected, see https://news.secondarymetabolites.org/2024-august-server-maintenance.html for our note on the ongoing maintenance work.
We've had some hardware outages that we're currently trying to route around, so I'm not sure when we'll be back up again.

**Comment by jasmezz** [comment]
Alright, thank you for replying quickly, and good luck for getting the services back up :mechanical_arm:

**Comment by jasmezz** [comment]
The servers are back since 2 days, closing this.
