### ISSUE TITLE
Biopython Warning about partial codon form NCBI's genome genbank records

### ISSUE THREAD

**Issue by nsarode-joyn** [antismash/antismash#74]
I was testing out antiSMASH (downloaded using Bioconda) using few known pathogens. I downloaded genbank records from NCBI (e.g. Clostridium difficile : GCA_002073735.2 ) and ran antismash with default settings. Got the following warning. This doesn't keep it from generating an output, 
```
/usr/miniconda2/envs/antismash/lib/python2.7/site-packages/Bio/Seq.py:2576: BiopythonWarning: Partial codon, len(sequence) not a multiple of three. Explicitly trim the sequence or add trailing N before translation. This may become an error in future.
```

I downloaded 5 other genomes from NCBI and got the same warning for all of them.

**Comment by SJShaw** [comment]
You are using antiSMASH 4, which is located at https://bitbucket.org/antismash/antismash/. This repository is for antiSMASH 5+ and has already solved the issue you've mentioned.  When it is released and a new bioconda package is built, you won't see that anymore.

**Comment by nsarode-joyn** [comment]
My bad. Thanks for letting me know !
