### ISSUE TITLE
Feature Request: Option to Export antiSMASH Results as Table/CSV or Guidance on Extracting Data from region.js/output.json

### ISSUE THREAD

**Issue by Timmy16** [antismash/antismash#745]
Dear antiSMASH development team,

I am relatively new to the field of bioinformatics and have recently begun using antiSMASH to analyze genomic regions. I am finding the tool incredibly valuable for my research and am eager to learn more about how to interpret its output files.

Currently, I am looking for a way to organize the antiSMASH output into a more accessible format, such as a table or CSV file, that would allow for easier downstream analysis. Specifically, I would like to know if there is an option or method to extract key data from the result files (like region.js or output.json) and present it in tabular form.

Here are a few specific points I’d appreciate feedback on:

    1) Is there an existing feature within antiSMASH that allows for exporting the results directly as a table or CSV file?
    2) If not, could you provide some guidance or examples on how to extract relevant information from the region.js or output.json files and convert it into a table? Any pointers on which fields or sections to focus on would be extremely helpful.
    3) Would it be possible to consider adding this functionality in a future release? Having the ability to export results in a table/CSV format could benefit many users, especially those who are new to the tool and may not be familiar with parsing JSON or JavaScript files.

As someone new to this area, I am keen to learn how best to utilize antiSMASH for my projects, and any help you can provide would be greatly appreciated.

Thank you for your hard work in maintaining and developing this powerful tool. I look forward to hearing from you and continuing to explore antiSMASH further.

Best regards,
Timmy16

**Comment by zreitz** [comment]
Hi Timmy, no, there is not a feature within antiSMASH that will generate a such table, and no, there will not be. [This request comes up occasionally](https://github.com/antismash/antismash/issues/443), but antiSMASH simply produces too much information for a CSV to handle, so it's best for the user to generate their own from the JSON. 

I'll move to [your discussion topic](https://github.com/antismash/antismash/discussions/746) for some alternative options so this can be closed.
