### ISSUE TITLE
How to download antiSMASH database version 3 ?

### ISSUE THREAD

**Issue by Mactarvish** [antismash/antismash#752]
Seems latest antismash will download database version 4, but now I need version 3 and tried `download_databases.py` from `antismash-3.0.4` but the url seems expired.
Any way to download database version 3? Thanks in advance.

**Comment by SJShaw** [comment]
If you want version 3 of the antiSMASH database as used in the clusterblast module, you need to use antiSMASH 6, not antiSMASH 3.
The download script for that version is [here](https://github.com/antismash/antismash/blob/6-1-stable/antismash/download_databases.py#L28).

**Comment by Mactarvish** [comment]
Thanks for the help but I checked out to stable-6-1 and tried `download-antismash-databases` encountered such error:
```
Downloading PFAM version 34.0
Downloading Pfam-A.hmm.gz: 100.00% downloaded.
Creating checksum of Pfam-A.hmm.gz
Extraction of Pfam-A.hmm.gz finished successfully.
Traceback (most recent call last):
  File "/home/mck/anaconda3/envs/p39/bin/download-antismash-databases", line 33, in <module>
    sys.exit(load_entry_point('antismash', 'console_scripts', 'download-antismash-databases')())
  File "/home/mck/Desktop/antismash/antismash/download_databases.py", line 397, in _main
    download(args)
  File "/home/mck/Desktop/antismash/antismash/download_databases.py", line 360, in download
    download_pfam(
  File "/home/mck/Desktop/antismash/antismash/download_databases.py", line 237, in download_pfam
    ensure_database_pressed(filename)
  File "/home/mck/Desktop/antismash/antismash/common/hmmer.py", line 300, in ensure_database_pressed
    raise RuntimeError(msg)
```
My python is 3.9

**Comment by kblin** [comment]
It's a bit hard to tell, because that error message is truncated, but if I had to guess you probably don't have the `hmmer` tools installed. But if all you want is the antiSMASH DBv3 fasta files as used in ClusterBlast, just grab https://dl.secondarymetabolites.org/releases/clusterblast/clusterblast_20201113.tar.xz

**Comment by Mactarvish** [comment]
Sorry for the trunction but luckly stable-6-1 installed finally.
But when I execute `antismash xxx`, new error occured:
```
ERROR    22/10 11:12:30   antismash.modules.t2pks: preqrequisite failure: Failed to locate file: 'blastp'
Traceback (most recent call last):
  File "/home/mck/anaconda3/envs/p39/bin/antismash", line 33, in <module>
    sys.exit(load_entry_point('antismash', 'console_scripts', 'antismash')())
  File "/home/mck/Desktop/antismash/antismash/__main__.py", line 125, in entrypoint
    sys.exit(main(sys.argv[1:]))
  File "/home/mck/Desktop/antismash/antismash/__main__.py", line 113, in main
    antismash.run_antismash(sequence, options)
  File "/home/mck/Desktop/antismash/antismash/main.py", line 674, in run_antismash
    result = _run_antismash(sequence_file, options)
  File "/home/mck/Desktop/antismash/antismash/main.py", line 699, in _run_antismash
    check_prerequisites(options.all_enabled_modules, options)
  File "/home/mck/Desktop/antismash/antismash/main.py", line 604, in check_prerequisites
    raise RuntimeError("Modules failing prerequisites")
RuntimeError: Modules failing prerequisites
```
I tried install blastp:
```
(p39) mck@mck-Legion-Y7000-IRX9:~/Desktop/GXY$ conda install blastp                                                                                                                    
Channels:                                                                                                                                                                              
 - conda-forge                                                                                                                                                                         
 - bioconda                                                                                                                                                                            
 - defaults                                                                                                                                                                            
Platform: linux-64                                                                                                                                                                     
Collecting package metadata (repodata.json): done                                                                                                                                      
Solving environment: failed                                                                                                                                                            
                                                                                                                                                                                       
PackagesNotFoundError: The following packages are not available from current channels:                                                                                                 
                                                                                                                                                                                       
  - blastp                                                                                                                                                                             
                                                                                                                                                                                       
Current channels:                                                                                                                                                                      
                                                                                                                                                                                       
  - https://conda.anaconda.org/conda-forge                                                                                                                                             
  - https://conda.anaconda.org/bioconda                                                                                                                                                
  - defaults                                                                                                                                                                           
                                                                                                                                                                                       
To search for alternate channels that may provide the conda package you're                                                                                                             
looking for, navigate to                                                                                                                                                               
                                                                                                                                                                                       
    https://anaconda.org                                                                                                                                                               
                                                                                                                                                                                       
and use the search bar at the top of the page.                                                                                                                                         
                                                    
```

python is 3.9

**Comment by Mactarvish** [comment]
> Sorry for the trunction but luckly stable-6-1 installed finally. But when I execute `antismash xxx`, new error occured:
> 
> ```
> ERROR    22/10 11:12:30   antismash.modules.t2pks: preqrequisite failure: Failed to locate file: 'blastp'
> Traceback (most recent call last):
>   File "/home/mck/anaconda3/envs/p39/bin/antismash", line 33, in <module>
>     sys.exit(load_entry_point('antismash', 'console_scripts', 'antismash')())
>   File "/home/mck/Desktop/antismash/antismash/__main__.py", line 125, in entrypoint
>     sys.exit(main(sys.argv[1:]))
>   File "/home/mck/Desktop/antismash/antismash/__main__.py", line 113, in main
>     antismash.run_antismash(sequence, options)
>   File "/home/mck/Desktop/antismash/antismash/main.py", line 674, in run_antismash
>     result = _run_antismash(sequence_file, options)
>   File "/home/mck/Desktop/antismash/antismash/main.py", line 699, in _run_antismash
>     check_prerequisites(options.all_enabled_modules, options)
>   File "/home/mck/Desktop/antismash/antismash/main.py", line 604, in check_prerequisites
>     raise RuntimeError("Modules failing prerequisites")
> RuntimeError: Modules failing prerequisites
> ```
> 
> I tried install blastp:
> 
> ```
> (p39) mck@mck-Legion-Y7000-IRX9:~/Desktop/GXY$ conda install blastp                                                                                                                    
> Channels:                                                                                                                                                                              
>  - conda-forge                                                                                                                                                                         
>  - bioconda                                                                                                                                                                            
>  - defaults                                                                                                                                                                            
> Platform: linux-64                                                                                                                                                                     
> Collecting package metadata (repodata.json): done                                                                                                                                      
> Solving environment: failed                                                                                                                                                            
>                                                                                                                                                                                        
> PackagesNotFoundError: The following packages are not available from current channels:                                                                                                 
>                                                                                                                                                                                        
>   - blastp                                                                                                                                                                             
>                                                                                                                                                                                        
> Current channels:                                                                                                                                                                      
>                                                                                                                                                                                        
>   - https://conda.anaconda.org/conda-forge                                                                                                                                             
>   - https://conda.anaconda.org/bioconda                                                                                                                                                
>   - defaults                                                                                                                                                                           
>                                                                                                                                                                                        
> To search for alternate channels that may provide the conda package you're                                                                                                             
> looking for, navigate to                                                                                                                                                               
>                                                                                                                                                                                        
>     https://anaconda.org                                                                                                                                                               
>                                                                                                                                                                                        
> and use the search bar at the top of the page.                                                                                                                                         
>                                                     
> ```
> 
> python is 3.9

Sovled by `sudo apt install ncbi-blast+`

**Comment by kblin** [comment]
I'm not sure what you are trying to do. Are you trying to get the antiSMASH database 3 data, or are you trying to install antiSMASH? If it's the latter, see https://docs.antismash.secondarymetabolites.org/install/ for install instructions
