### ISSUE TITLE
NRP-metallophore type wasn't reported correctly

### ISSUE THREAD

**Issue by RuolinHe** [antismash/antismash#753]
**Describe the bug**

When I run antiSMASH v7 or v7.1 for one Enterobacteriaceae genome (Salmonella bongori, GCF_013138145.1), it's clear that there are enterobactin synthetase (a kind of NRP-metallophore synthetase). However, the product type of this region is only "NRPS", rather than "NRPS and NRP-metallophore".

It meet the rule of NRP-metallophore: (cds(Condensation and AMP-binding) and (EntA and EntC). Why it wasn't reported as NRP-metallophore?

NRP-metallophore: (VibH_like or Cy_tandem or (cds(Condensation and AMP-binding) and ((IBH_Asp and not SBH_Asp) or IBH_His or TBH_Asp or CyanoBH_Asp1 or CyanoBH_Asp2 or IPL or SalSyn or (EntA and EntC) or (GrbD and GrbE) or (FbnL and FbnM) or PvdO or PvdP or (Orn_monoox and not (KtzT or MetRS-like)) or Lys_monoox or VbsL)))

**Expected behavior**

The product type of Region 2 should be "NRPS and NRP-metallophore".

**To Reproduce**
For analysis issues, provide an accession number or a record fragment that can reproduce the problem.

The [antiSMASH result](https://antismash.secondarymetabolites.org/upload/bacteria-acc2158f-e938-481f-923e-54e8f848be14/index.html#r1c2) for GCF_013138145.1 in server.

**Screenshots**
This region contains EntF, EntA and EntC. However, only "NRPS" product type was reported. Why doesn't it meet NRP-metallophore rule?
![1729652127097](https://github.com/user-attachments/assets/79727e41-c456-44cf-b92a-cff52fb07694)
![1729652169840](https://github.com/user-attachments/assets/f7feb87c-d180-4bf1-a3bb-7e73ead51e53)
![1729652204136](https://github.com/user-attachments/assets/2a78ffba-41ef-4461-b82f-39b37c8a9c4b)

**System (please complete the following information):**
 - OS: [e.g. iOS, Ubuntu]
 - Browser [e.g. chrome, safari] (if relevant)

**Additional context**

[Another case](https://antismash.secondarymetabolites.org/upload/bacteria-fd422d5b-cbd4-48c8-9ba2-b5eca2b66c2b/index.html#r1c1): region 1 (GCF_006385635.1) was reported as "NRPS and NRP-metallophore" correctly. Why do some succeed and some fail?

**Comment by zreitz** [comment]
Hi Ruolin, good question. 

The surface-level answer is that while a gene annotated `entA` is present, there was no gene that matched the EntA pHMM above the required threshold. If you compare your second and third screenshots, the `entC` gene has a line on the right side for `(rule-based-clusters) EntC`, but `entA` has no similar line.

So why not? Often the cause for a missed domain is that it is truncated, which would lower the score and cause the match to be discarded. Here are the lengths:
Good entA
![image](https://github.com/user-attachments/assets/b605465c-e633-4044-9df0-9359a0b8b188)
Bad entA
![image](https://github.com/user-attachments/assets/b7e25f63-418e-4729-b7ff-2dc02dfe6a25)

Even though they're similar nucleotide lengths, one translation is much shorter. By BLAST, the shorter has a frameshift mutation that leads to a premature stop codon:
![image](https://github.com/user-attachments/assets/8ad81dc0-02c9-4660-9c1a-30dba9283531)

So antiSMASH did work as expected. I would say this is more a problem with the annotation software, which should have spotted the mutation (and mismatched NT/AA lengths!) and marked this as a pseudogene.

**Comment by RuolinHe** [comment]
Thanks! I understand now.
