### ISSUE TITLE
Error when run antismash 4.2. 

### ISSUE THREAD

**Issue by letunglam1991** [antismash/antismash#93]
I run antismash 4.2 for 10 genomes dowloaded from NCBI. After downloaded, i run prokka then take *.gbk file to run antismash. 9 others file is ok. But 1 file when i run antismash. I had this error

/home/vdsa/software/antismash-4.2.0/run_antismash.py -c 12  --transatpks_da --clusterblast --subclusterblast  --knownclusterblast --smcogs --inclusive --borderpredict --full-hmmer --asf  --tta -v --outputfolder GCA_003945505.1_ASM394550v1_genomic GCA_003945505.1_ASM394550v1_genomic.gbk
INFO    10/01 14:07:55   Loading detection plugins
INFO    10/01 14:07:55   Parsing the input sequence(s)
INFO    10/01 14:07:58   Analyzing record 1 (CP029618.1)
INFO    10/01 14:07:58   Detecting secondary metabolite signature genes for contig #1
INFO    10/01 14:08:12   Detecting secondary metabolite clusters using inclusive ClusterFinder algorithm for contig #1
INFO    10/01 14:08:12   Running whole-genome pfam search
INFO    10/01 14:43:38   Running ClusterFinder HMM to detect gene clusters
INFO    10/01 14:43:50   Running cluster-specific analyses
INFO    10/01 14:43:50   Calculating detailed predictions for Lanthipeptide clusters
INFO    10/01 14:48:04   Calculating detailed predictions for lasso peptide clusters
INFO    10/01 14:48:32   Predicting NRPS A domain substrate specificities with SANDPUMA
INFO    10/01 15:10:25   Predicting PKS AT domain substrate specificities by Yadav et al. PKS signature sequences
INFO    10/01 15:10:37   Predicting PKS AT domain substrate specificities by Minowa et al. method
INFO    10/01 15:10:59   Predicting CAL domain substrate specificities by Minowa et al. method
INFO    10/01 15:11:00   Predicting PKS KR activity and stereochemistry using KR fingerprints from Starcevic et al.
INFO    10/01 15:11:30   Aligning Tans-AT PKS domains
INFO    10/01 15:11:53   TransATPKS: constructing phylogeny tree for each KS domain
INFO    10/01 15:17:49   Phylogenetic analysis: predicting substrate specificity of KS
INFO    10/01 15:17:56   MAFFT: generating pairwise distance matrix of multiple sequence alignment of all domains
INFO    10/01 15:23:19   TRANSATPKS: generating distance matrix of assembly lines
Traceback (most recent call last):
  File "/home/vdsa/software/antismash-4.2.0/run_antismash.py", line 1210, in <module>
    main()
  File "/home/vdsa/software/antismash-4.2.0/run_antismash.py", line 559, in main
    run_analyses(seq_record, options, plugins)
  File "/home/vdsa/software/antismash-4.2.0/run_antismash.py", line 643, in run_analyses
    cluster_specific_analysis(plugins, seq_record, options)
  File "/home/vdsa/software/antismash-4.2.0/run_antismash.py", line 1191, in cluster_specific_analysis
    plugin.specific_analysis(seq_record, options)
  File "/home/vdsa/software/antismash-4.2.0/antismash/specific_modules/nrpspks/specific_analysis.py", line 99, in specific_analysis
    classify_nrpspks_domains_ks(pksnrpsvars, seq_record, options)
  File "/home/vdsa/software/antismash-4.2.0/antismash/specific_modules/nrpspks/nrpspks_classification.py", line 159, in classify_nrpspks_domains_ks
    similar_bgc_per_cluster, new_cluster, new_cluster_index = cdt.run_calculate_distance(data_dir = data_dir, seq_simScore = KS_msa_dist, ksa_per_new_cluster=KS_per_cluster, cutoff_bgc_nr = bgcs_nr)
  File "/home/vdsa/software/antismash-4.2.0/antismash/specific_modules/nrpspks/nrpspksdomainalign/calculate_distance_transATPKS.py", line 494, in run_calculate_distance
    BGCs, DMS, cluster_seq, new_cluster, new_cluster_index = generate_BGCs_DMS(cluster=cluster, cluster_KSindex=cluster_KSindex, pseudo_aa=pseudo_aa, ksa_per_new_cluster=ksa_per_new_cluster)
  File "/home/vdsa/software/antismash-4.2.0/antismash/specific_modules/nrpspks/nrpspksdomainalign/calculate_distance_transATPKS.py", line 119, in generate_BGCs_DMS
    new_cluster, new_cluster_index = _get_new_cluster_index(ksa_per_new_cluster=ksa_per_new_cluster)
  File "/home/vdsa/software/antismash-4.2.0/antismash/specific_modules/nrpspks/nrpspksdomainalign/calculate_distance_transATPKS.py", line 68, in _get_new_cluster_index
    cluster_i_dict_wob[int(index)] = [ksa_index, cluster_i[k][0]]
ValueError: invalid literal for int() with base 10: 'KS?'

**Comment by kblin** [comment]
Hi,
in general we track antiSMASH 4 issues on the antiSMASH 4 bitbucket repository: https://bitbucket.org/antismash/antismash/issues
This repository is for the rewrite that is antiSMASH 5.

That said, you're hit by a bug in the TransAT-PKS domainalign module. This is a known issue with the module data that we unfortunately haven't been able to fix as the original contributor changed jobs and we don't currently have the time to re-generate and validate the data from scratch. If you leave out the `--transatpks_da` parameter, you won't see this crash.
Hope this helps,
Kai

**Comment by lauzee** [comment]
Hi,senior！ It took me 5 days to install antismash 4.2.0（Centos)，Could you please guide me, Thank you very much！Looking forward to your reply！！
